### ISSUE TITLE
Marshaling failure with Ice 3.7.1 C# with Unity 2018 on Android

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#101]
As reported on the [ZeroC forums](https://forums.zeroc.com/discussion/46631/build-ice-3-7-1-with-option-managed-yes-on-macos-or-windows), Ice 3.7.1 doesn't work properly with Unity 2018 on Android. See the forum discussion for details.

**Comment by pepone** [comment]
The marshaling code was fixed in commit bb19cbea549261ba0aca8e1e7f138c4b905de648

**Comment by 12yueqing** [comment]
I'm trying
