### ISSUE TITLE
Slice parser accepts return tuple and out parameter

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1026]
The Slice parser should reject operations that have both a return tuple and out parameters. Out parameters are only supported for backwards compatibility with older version of Ice that did not support return tuples.

Currently, this compiles fine, but should not:
```
(LongSS r1, ShortSS r2, IntSS r3) opShortIntLongSS(ShortSS p1, IntSS p2, LongSS p3, out LongSS p4);
```

**Comment by InsertCreativityHere** [comment]
Fixed in #1032
Now the parser will correctly issue an error for mixing return tuples and out parameters:
`an operation returning a tuple cannot have out parameters`
