### ISSUE TITLE
C# - Replace OSPlatform and RuntimeInformation by OperatingSystem 

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1037]
.NET 5 will deemphasize usage of `OSPlatform ` and `RuntimeInformation` in favor of `OperatingSystem`

We should update our code to use the new methods in `OperatingSystem`. Note that as of now (.NET 5 RC1) these methods have not been implemented so we'll have to wait.

See https://github.com/dotnet/runtime/issues/40111#issuecomment-668771421

**Comment by InsertCreativityHere** [comment]
This was fixed in #1103
