### ISSUE TITLE
Problem trying to find  Slice

### ISSUE THREAD

**Issue by tete17** [zeroc-ice/ice#106]
I cant find the Slice library using cmake.

Here is my error output:
```
/home/miguel/clion-2018.1.3/bin/cmake/bin/cmake --build /home/miguel/CLionProjects/rmg-buildenv/cmake-build-default --target all -- -j 2
rmg-buildenv configuration:
  CMAKE_SYSTEM_NAME=Linux
  LOCAL_BIN_DIR=/usr/local/bin
-- Ice version: 3.7.1
-- Found the following Ice libraries:
--   Ice (required)
--   IceBox (required)
--   IceSSL (required)
-- The following Ice libraries were not found:
--   Slice (required)
CMake Error at /home/miguel/clion-2018.1.3/bin/cmake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Failed to find all Ice components (missing: _Ice_REQUIRED_LIBS_FOUND)
  (found version "3.7.1") `
```
Cmake version 3.10.3 and i installed the ICE 3.7 version through apt
```
miguel@miguel-ThinkPad-T460s:~/CLionProjects$ sudo apt install zeroc-ice-all-dev 
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
zeroc-ice-all-dev ya está en su versión más reciente (3.7.1-1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
```

Thank you in advance

**Comment by bentoi** [comment]
Hi,

I'm not very familiar with Clion but it looks like your project requires the Slice library which is no longer provided with Ice 3.7. You should remove it from your project. It doesn't provide any public APIs that you can use.

Cheers,
Benoit.

**Comment by tete17** [comment]
Thanks for the quick response. Any alternatives to Slice?? You should also update the page regarding updating from Ice 3.6 because i could not findt anything about this change.

**Comment by bentoi** [comment]
Does you program depend on APIs from the Slice library?

The public API is provided by the Ice shared library. The Slice library used to be provided as a shared library with Ice <3.7. It's an internal and un-documented library used by our Slice compilers and scripting language mappings. Starting with Ice 3.7, the Slice compilers are now linked statically with this library so it's no longer provided as a shared library.

**Comment by bentoi** [comment]
@tete17, were you able to fix your build system to no longer look for the Slice library?
