### ISSUE TITLE
bug report : createObjectAdapterWithRouter block 

### ISSUE THREAD

**Issue by cntone** [zeroc-ice/ice#1061]
when network is unreachable，"communicator.createObjectAdapterWithRouter" method will block the connection forever, and ObjectPrx facert invocation is block，Ice RPC Service go to dead.

***************************************
    public Ice.ObjectPrx end_getServerProxy(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getServerProxy_name);
        try
        {           
            if(!__result.__wait())    **/*****************  this line is blocked********************/**
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Ice.ObjectPrx __ret;
            __ret = __is.readProxy();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }
************************************************

**Comment by cntone** [comment]
Ice.RetryIntervals=0  
Clients that establish a session with a Glacier2 router also need to disable retries. To
prevent automatic retries, use a value of -1

**Comment by bernardnormier** [comment]
This is because `createObjectAdapterWithRouter` makes a synchronous remote call to the router, and (presumably) you did not configure an invocation timeout on your router proxy.

Ice 4.0 will offer an async API for this call. See #1169.
