### ISSUE TITLE
Use foreground threads in C#

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#108]
In C#, unlike Java, we use background threads for threads created by Ice.

This switch to background threads was done a long time ago, so that if you forget to destroy your communicator, the application does not hang but exits (see ICE-1586). This was shortsighted as it's easy to destroy your communicator and using foreground threads like in Java removes the need to dedicate a thread to waitForShutdown. With foreground threads, the application keeps running until you destroy the communicator, which terminates all Ice-started threads.

**Comment by pepone** [comment]
This is no longer relevant since we move to use .NET ThreadPool in 4.0
