### ISSUE TITLE
how many  Ice::Communicator one process can create?   

### ISSUE THREAD

**Issue by wubo2018** [zeroc-ice/ice#1096]
how many  Ice::Communicator one process can create?   
in a process I want to  create two Ice:: Communicator to manager publisher and  subscriber?  

is it necessary？

**Comment by wubo2018** [comment]
or one process only can create a  Ice:: Communicator?

**Comment by bernardnormier** [comment]
A process can create any number of communicators. The most common however is to create a single communicator per process.

The reason for creating more than one communicator in a process is to use different configurations for those communicators. Otherwise, there is no benefit.
