### ISSUE TITLE
Replace Ice.Promise with standard JS promise

### ISSUE THREAD

**Issue by spruiell** [zeroc-ice/ice#112]
We removed the documentation for Ice.Promise in 3.7.1 but did not remove it from the code. We should investigate whether we can replace it with the standard type.

Also see ICE-8513.

**Comment by pepone** [comment]
let's keep it for 3.8, We have a large hierarchy of classes derived from Promise

`OutgoingAsync -> OutgoingAsyncBase -> AsyncResult -> Ice.Promise -> Promise` Just removing Promise wouldn't be a big improvement. Refactoring the async mapping would be a much bigger task.
