### ISSUE TITLE
Review __setNoDelete usage pattern

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#116]
__setNoDelete allows to disable the self-deletion of an object when this object's refcount reaches 0 (applies to C++98 handles). It's primarily used in constructors when exceptions can occur. We should review our usage pattern in Ice C++ and make sure it's correct.

See ICE-3791.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/Ice/IPEndpointI.cpp#L534-L566

That seems mostly correct start create a smart pointer to this and without `__setNotDelete` the object will be deleted when start throws. I think the code will be simpler if we move the call to start out of the construct avoiding the need to call `__setNotDelete`

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/3.7/cpp/src/Glacier2/SessionRouterI.cpp#L689-L701

This seems correct we need to call `__setNotDelete` because the `_sessionThread` holds a smart pointer to the object being constructed, but calling `__setNotDelete` from the catch block should be enough

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/Ice/ThreadPool.cpp#L385-L419

That seems correct too if `Thread::start` fails we don't want the smart pointers hold by `EventHandlerThread ` to trigger the deletion of the thread pool that is not yet constructed

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/Ice/Timer.cpp#L23-L39

Those are fine but I think it will be simpler to just call start after the constructor returns at the point we create the timer.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/IceSSL/OpenSSLEngine.cpp#L200-L204

That seems not required, even if constructor throw nothing holds a smart pointer to the object at this point.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/6dee1f8a7a6046910cb027f1cafae79b20b837fc/cpp/src/IceGrid/NodeSessionI.cpp#L148-L180

That seems correct the call to `setSession` create a smart pointer to the object being constructed, and we don't want the destructor being call if there is an exception in the try block.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/6dee1f8a7a6046910cb027f1cafae79b20b837fc/cpp/src/IceGrid/ReplicaSessionI.cpp#L45-L70

Seems correct too the call to `ReplicaCache::add` create a smart pointer to the object being created and we don't want it being deleted if the try blocks ends with an expcetion

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/IceStorm/Instance.cpp#L120-L174

That seems correct the call to `Observers` constructor create a smart  pointer to the object being constructed and we don't want it to trigger the destructor if the try block ends with an exception.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/12c719358659158aa8d3667265eeb5ecaaaa92aa/cpp/src/IceStorm/TopicManagerI.cpp#L242-L308

Correct too several smart pointers to object being constructed are created and we need to avoid them to trigger the call to the desctructor in case that the try blocks end with an exception, `shutdown` call from catch correctly cleanup the objects holding a smart pointer before `setNotDelete` call again.

**Comment by pepone** [comment]
I fixed `OpenSSL::SSLEngine` to not use `__setNotDelete` and simplify `EndpointHostResolver` initialization to not require using `__setNoDelete` the other usages seems correct.
