### ISSUE TITLE
How to subscribe to multiple topics？

### ISSUE THREAD

**Issue by wubo2018** [zeroc-ice/ice#1234]
How to subscribe to multiple topics in one process? and How to publish multiple topics in one process？

**Comment by pepone** [comment]
Hi @wubo2018,

You have to subscribe to each topic using `subscribeAndGetPublisher`, to publish you need to get the publisher for each topic you are interested in, there isn't a separate API to subscribe to several topics. You have to basically repeat the process that is done to subscribe/publish to one topic.

**Comment by wubo2018** [comment]
you mean one topic is a *.ice file ,two topic need two *.ice files.

**Comment by wubo2018** [comment]
there is a nather problem , I subscribe a topic ,some times I can't recv the topic's message.  when i restart the process , I can recv it from the last time.

**Comment by pepone** [comment]
> you mean one topic is a *.ice file ,two topic need two *.ice files.

No, a topic is essentially just a Slice interface, defining the messages that can be published using that topic,  this is well explained in the docs see https://doc.zeroc.com/ice/3.7/ice-services/icestorm/icestorm-concepts

> there is a nather problem , I subscribe a topic ,some times I can't recv the topic's message. when i restart the process , I can recv it from the last time.

Not clear what you mean


Depending on what you are trying to do a single interface might or might not be enough, then the number of topics you create doesn't have any relation to the Slice files or the number of interfaces.

A typical example can be a wether monitor app, you can define a Slice interface to monitor the weather, different weather stations will be represented as different topics but all will be created using the same Slice interface.

```
interface WeatherMonitor
{
    void temperature(long timestamp, float celsiusDegrees);
    void rain(long timestamp, float m2Liters);
}
```

Then in your application, you will create one topic per each of the stations you want to monitor, each station publisher will retrieve the publisher corresponding to it, and use it to publish weather updates. Then each subscriber will subscribe to the topics that represent the stations it wants to monitor.

For other applications having multiple interfaces each representing a different concept would make more sense.

The best is to start by modifying one of the demos, and if you have specific problems just ask for help, see https://github.com/zeroc-ice/ice-demos/tree/3.7/csharp/IceStorm there is similar demos available for other languages.

Cheers,
Jose

**Comment by wubo2018** [comment]
thank you very much
