### ISSUE TITLE
Review SliceData class implementation in all language mappings

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#124]
We have few inconsistencies left in the different mappings related to the SlicedData class:
user exceptions don't provide sliced data in Ruby/PHP (possibly because they were client-side only languages). Objective-C doesn't provide the slice infos. We should consider fixing these inconsistencies.

**Comment by bernardnormier** [comment]
This was fixed in 3.8. In particular, user exception no longer provide SlicedData in any language mapping.

**Comment by bernardnormier** [comment]
@
