### ISSUE TITLE
ice-3.6.1.jar have "Instrumentation" package，but there is no "Instrumentation" package on GitHub

### ISSUE THREAD

**Issue by wei804378140** [zeroc-ice/ice#1243]
Hi：

 ice-3.6.1.jar have "Instrumentation" package，but there is no "Instrumentation" package on GitHub。
![1](https://user-images.githubusercontent.com/7237900/104712921-2c7f1380-575e-11eb-9b2e-654757de3198.png)
![2](https://user-images.githubusercontent.com/7237900/104712923-2e48d700-575e-11eb-8549-af907b5b9178.png)

**Comment by pepone** [comment]
These classes are generated from Slice definitions in [slice/Ice/Instrumentation.ice](https://github.com/zeroc-ice/ice/blob/3.6/slice/Ice/Instrumentation.ice) the generated classes are included in Ice.jar

**Comment by wei804378140** [comment]
thank you very much for your help
