### ISSUE TITLE
Add support for running cross-built binaries from NFS mount

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#125]
It should be possible to cross build ARM tests, NFS mount them on an ARM platform and use `./allTests.py` to run them. Right now this fails because `Util.py` assumes binaries are in `cpp/bin` not `cpp/bin/arm-linux-gnueabihf`. We could add a `--cross` option to indicate `Util.py` that we're running from a cross build or perhaps we should check if this directory exist and if it does use it in priority.

**Comment by bernardnormier** [comment]
I think it would be simpler to look for the binaries in cpp/bin/<platform> and then cpp/bin all the time. This way, no need to add a new flag. We already use `--cross=<mapping>` for cross language-mapping testing.
