### ISSUE TITLE
Looking into improving build time of applications using the new C++11 mapping

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#1255]
Builds of applications using the new C++11 mapping are quite a bit slower than with the C++98 mapping. The increase in template usage is likely to explain the additional compile time. It would be good to investigate whether or not we can improve our use of templates to reduce build times.

**Comment by pepone** [comment]
Moved to 4.0 as this might require bigger changes than what we can do in a patch release

**Comment by bernardnormier** [comment]
As of 3.8, this no longer appears to be an issue.
