### ISSUE TITLE
Remove usage of jcenter

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1273]
JCenter is shutting down. See https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure. We should remove our usage of it in Ice (also in the demos)

```
❯ rg jcenter
java/test/android/controller/build.gradle
7:        jcenter()
50:    jcenter()

java-compat/test/android/controller/build.gradle
7:        jcenter()
51:    jcenter()
```

**Comment by pepone** [comment]
Fixed in https://github.com/zeroc-ice/ice/commit/c1e6f045aa000e376fbd332059e75a8bfe999367
