### ISSUE TITLE
can ice 3.5+ work in Red Hat 7 based on architecture aarch64 ??

### ISSUE THREAD

**Issue by speedlong2008** [zeroc-ice/ice#128]
I'm trying to compile ice 3.7.0 on red hat 7.4 /aarch64，but the architecture  treated as "x64" in ice/config/make.rules.Linux .  Are there some successful examples for  redhat 7 /aarch64？

-------------------------------------------------------------------------------------
else ifneq ($(filter centos rhel fedora,$(linux_id)),)

#
# MultiLib Linux (x64 libraries go in the lib64 directory, x86 executable names are suffixed with 32)
#
supported-platforms     = x64 x86
multilib-platform       = yes

ifeq ($(OPTIMIZE),yes)
# Use default system packaging flags if building with OPTIMIZE and CXXFLAGS/LDFLAGS aren't defined.
# NOTE: We remove the -m32/-m64 flags since we'll add them below.
opt-cppflags = $(if $(CXXFLAGS),,$(filter-out -m32 -m64,$(shell setarch $1 rpm --eval %optflags)))
opt-ldflags  = $(if $(LDFLAGS),,$(shell setarch $1 rpm --eval %?__global_ldflags))
endif

x64_cppflags            := $(call opt-cppflags,x86_64) -m64
x64_ldflags             := $(call opt-ldflags,x86_64) -m64
x64_targetdir           = $(if $(filter %/build,$5),/x64,$(if $(filter-out $($1_target),program),64))
x64_installdir          = $(if $(and $(filter-out $($1_target),program),$(filter-out %64,$5)),64)

x86_cppflags            := $(call opt-cppflags,i386) -m32
x86_ldflags             := $(call opt-ldflags,i386) -m32
x86_targetdir           = $(if $(filter %/build,$5),/x86)
x86_targetname          = $(if $(is-bin-program),32)

# No Slice translators for x86
x86_excludes            = slice2%

**Comment by bentoi** [comment]
We didn't try to build Ice on this architecture. Can you try replacing line 41 in `Make.rules.Linux`: https://github.com/zeroc-ice/ice/blob/7f31702542ce79eaa73489a2f3e0f24653609e78/config/Make.rules.Linux#L41 

With the following line instead:
```
else ifneq ($(and $(filter centos rhel fedora,$(linux_id)),$(filter x86_64 i%86,$(shell uname -m))),)
```
and see if helps building on aarch64?

**Comment by bentoi** [comment]
Commit 961917c45322af39d70ec0c5806cb6e37ed6221b should fix this.
