### ISSUE TITLE
IceUtil::Time::toDateTime() crashes when used on dates 17+ years in the future 

### ISSUE THREAD

**Issue by FabioOsorioMoreira** [zeroc-ice/ice#1283]
**Version(please complete the following information):**
 - Ice Version: 3.7.2 and 3.7.5
 - OS: Only tested on Windows
 -  Language: C++

**Describe the bug**
If you try to use toDateTime to get a readable string on a date that is several years on the future, the function will crash

**Expected behavior**
It should return a String containing a human readable date

**Additional context**
Originally found this issue by configuring a sever to use a certificate that expired 40 years in the future. On the client side I tried to access the sender certificate and display information about it (subjectName, expirationDate, etc). The client would crash every time it got to this line: cert->getNotAfter().toDateTime(). If you run it in Debug mode you can see an assert failing in stftime.

![image](https://user-images.githubusercontent.com/14280413/119880110-4b5a9700-bf02-11eb-87f3-e58030f20473.png)

**Comment by pepone** [comment]
Hi Fabio,

Thanks for the bug report,  it is a problem with `IceUtil::Time::toString` implementation https://github.com/zeroc-ice/ice/blob/4cfc616971da45e1d549db6818e4b9d014fc31cd/cpp/src/IceUtil/Time.cpp#L281

This cast is bogus, it should cast to `time_t` I will push a fix tomorrow with a test.

Cheers,
Jose
