### ISSUE TITLE
Mention Xcode icebuilder requirement

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1285]
I got this error building Xcodesdk configuration, the readme doesn't mention `icebuilder` setup
```
../../../../scripts/ice-builder-xcode-wrapper: line 18: /usr/local/bin/icebuilder: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code
```

**Comment by pepone** [comment]
On mac M1 it goes to `/opt/homebrew/bin/icebuilder` and the build still fails after installing it

**Comment by pepone** [comment]
I updating the builder wrapper script to
```
diff --git a/scripts/ice-builder-xcode-wrapper b/scripts/ice-builder-xcode-wrapper
index b8fd681194..ed72dbc792 100755
--- a/scripts/ice-builder-xcode-wrapper
+++ b/scripts/ice-builder-xcode-wrapper
@@ -15,4 +15,5 @@ else
     FLAGS="--ice-home ../../../.."
 fi
 
-/usr/local/bin/icebuilder $FLAGS "$@"
+
+$(brew --prefix zeroc-ice/tap/ice-builder-xcode)/bin/icebuilder $FLAGS "$@"
```

**Comment by pepone** [comment]
The above works from the command line but not from Xcode

```
../../../../scripts/ice-builder-xcode-wrapper: line 19: brew: command not found
../../../../scripts/ice-builder-xcode-wrapper: line 19: /bin/icebuilder: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code
```
It is not clear to me why /opt/hombrew/bin is not in PATH when using XCode, I saw the same issue with `swiftlint`

**Comment by externl** [comment]
` /opt/hombrew/bin` is not in the default system PATH, I think that `/usr/local/bin` is. One option is to add `/opt/homebrew/bin` to a file in `/etc/paths.d/`. Maybe best to just search a few well known places if it's not in the path.
