### ISSUE TITLE
Python: Error occurs when performing "slice2py"

### ISSUE THREAD

**Issue by ryuujo1573** [zeroc-ice/ice#1287]
**Version:**
 - Ice Version 3.7.5
 - OS: macOS Big Sur 11.3 AArch64
 - Distribution: homebrew

**Describe the bug**
perform "slice2py" with outputs:

> Traceback (most recent call last):
>   File "/Users/*/miniforge3/bin/slice2py", line 5, in <module>
>     from slice2py import main
>   File "/Users/*/miniforge3/lib/python3.9/site-packages/slice2py.py", line 7, in <module>
>     import Ice
>   File "/Users/*/miniforge3/lib/python3.9/site-packages/Ice/__init__.py", line 42, in <module>
>     import IcePy
> ImportError: dynamic module does not define module export function (PyInit_IcePy)

**Additional context**
slice2cs works but this

**thanks for your efforts**

**Comment by ryuujo1573** [comment]
Sorry for the mess.
Just now I noticed that when performing
> where slice2py
 it outputs 
> "/Users/*/miniforge3/bin/slice2py"

It showed that I'm using the wrong exe, but why that piece in miniforge3/bin doesn't work?

**Comment by pepone** [comment]
Hi @ryuujo1573 

How was `"/Users/*/miniforge3/bin/slice2py"` installed? the error just indicates that `IcePy` library cannot be load by the python interpreter.

`slice2cs` is a native executable,  `slice2py` is a python script that needs to import the `IcePy` library, and is this import that is failing. 

Cheers,
Jose
