### ISSUE TITLE
Crash due to AssertionError in in IceBT.TransceiverI.runConnectThread

### ISSUE THREAD

**Issue by thhook** [zeroc-ice/ice#1291]
**Version(please complete the following information):**
 - Ice Version: 3.7.6
 - OS: Android
 - Distribution: https://mvnrepository.com/artifact/com.zeroc/ice/3.7.6

**Describe the bug**
When trying to establish a connection via Bluetooth our app crashes immediately in `IceBT.TransceiverI.runConnectThread()`:
```
E/AndroidRuntime: FATAL EXCEPTION: IceBT.ConnectThread-B4:EC:02:F0:C3:17-c707050e-efae-1449-3913-c191e5bb32dc
    Process: com.bmw.ConnectedRide, PID: 10281
    java.lang.AssertionError
        at IceBT.TransceiverI.runConnectThread(TransceiverI.java:392)
        at IceBT.TransceiverI.access$200(TransceiverI.java:14)
        at IceBT.TransceiverI$1.run(TransceiverI.java:308)
```

Crashing line of code in`IceBT.TransceiverI.java`:
```
//
// Connect succeeded.
//
assert(_exception != null);
```

Looks as if the assert-logic is inverted, should probably be `assert(_exception == null)`.

**Comment by bentoi** [comment]
That's embarrassing. We obviously have an issue with our testing which must disable asserts. We didn't run into this bug when we merged #1264. We'll look into providing a fix asap. The assert is indeed inverted.

**Comment by bentoi** [comment]
We have fixed this issue and pushed an updated IceBT jar file with the version 3.7.6-1 to the maven repository (https://search.maven.org/artifact/com.zeroc/icebt/3.7.6-1/jar).

Can you tell us a bit more about your test environment and how you enable asserts on the Android device?

**Comment by thhook** [comment]
Thank you for the quick fix.

My test environment consists of some Android phone (Google Pixel 4 in this case) and a motorbike instrument cluster on the other side of the BT connection. I'm not explicitly enabling asserts on the device, just running a debug version of the app directly from Android Studio.
