### ISSUE TITLE
iOS15 set socks5 proxy issue

### ISSUE THREAD

**Issue by jsonsnow** [zeroc-ice/ice#1310]
**Version(please complete the following information):**
 - Ice Version：3.6
 - OS: iOS15
 - Distribution: homebrew

**Describe the bug**
* my application set socks5 proxy to delegate connect,on ios15 scoks5 protocol exchange success, but read and write abnormal
* ice tip connect timeout

**Expected behavior**
* by set stream socks5 property all connect proxy to local service
* on ios15 local proxy service read or write fd return 0
* recv errno is EINPROGRESS
**Additional context**

**Comment by pepone** [comment]
Hi @jsonsnow 

Ice only supports SOCKS4 and HTTP proxies

see: 
* https://doc.zeroc.com/ice/3.6/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.6-Ice.SOCKSProxyHost
* https://doc.zeroc.com/ice/3.6/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.6-Ice.HTTPProxyHost

**Comment by jsonsnow** [comment]
> Hi @jsonsnow
> 
> Ice only supports SOCKS4 and HTTP proxies
> 
> see:
> 
> * https://doc.zeroc.com/ice/3.6/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.6-Ice.SOCKSProxyHost
> * https://doc.zeroc.com/ice/3.6/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.6-Ice.HTTPProxyHost

But less than iOS15 is normal
3.7 support?

**Comment by jsonsnow** [comment]
by hook streamOpen func to set stream scoks5 property
* less than ios15 is normal but ios15 error

**Comment by pepone** [comment]
SOCKS5 protocol is not supported, you have to use SOCKS4 or HTTP network proxies
