### ISSUE TITLE
How to package OpenDDS application with ICE 

### ISSUE THREAD

**Issue by Achari-Sumanth** [zeroc-ice/ice#1311]
**Version(please complete the following information):**
 - Ice Version [e.g. 3.7.4]
 - OS: [e.g. Linux, Windows,]
 - Distribution: [e.g. YUM, Apt, Homebrew]

 We are trying to package OpenDDS application with ICE.As OpenDDS and ICE are using different make files, how can we include third party headers to ICE.

Can Ice host the third party application communicating with OpenDDS

**Comment by pepone** [comment]
> We are trying to package OpenDDS application with ICE.As OpenDDS and ICE are using different make files, how can we include third party headers to ICE.

Can you describe what are you trying to accomplish here?

> Can Ice host the third party application communicating with OpenDDS

You can host Ice services with [IceBox](https://doc.zeroc.com/ice/3.7/icebox) and deploy them with [IceGrid](https://doc.zeroc.com/ice/3.7/ice-services/icegrid) and what the service does is up to you and your service implementation, so there is no reason why the service cannot communicate with a third party application using OpenDDS,

**Comment by Achari-Sumanth** [comment]
We are trying to use Ice as a micro service framework to host this application [Sample application (that is communicating with OpenDDS) ](https://github.com/objectcomputing/OpenDDS/tree/master/DevGuideExamples/DCPS/Messenger). 

So, here I am trying to host the messenger application on ICE and the messesnger's publisher and subscriber will be communicating via OpenDDS. The question is that - Is this even possible? 
If so, the Messenger application is using some cmake, make files to compile and the Ice will be using slice and make files. So how can we package this application to generate a common executable that is generated from ICE?

**Comment by pepone** [comment]
>So, here I am trying to host the messenger application on ICE and the messesnger's publisher and subscriber will be communicating via OpenDDS. The question is that - Is this even possible?

It is not clear to me what you mean by "I am trying to host the messenger application on ICE", you can have an Ice application that is also an OpenDDS subscriber, you will have a single `main` entry point that starts both the OpenDDS runtime and Ice. Another option is to implement this as a couple of IceBox services, the application and the subscriber can communicate via Ice protocol and the subscriber can still use OpenDDS.

> the Messenger application is using some cmake, make files to compile and the Ice will be using slice and make files. So how can we package this application to generate a common executable that is generated from ICE?

You can build your Ice application using CMake too, see https://cmake.org/cmake/help/latest/module/FindIce.html and https://forums.zeroc.com/discussion/6462/ice-support-for-cmake

**Comment by pepone** [comment]
As a side note, you can also use Data Storm ZeroC new publish/subscriber framework see https://doc.zeroc.com/datastorm/latest/introduction
