### ISSUE TITLE
Issues with install process

### ISSUE THREAD

**Issue by michael-createc** [zeroc-ice/ice#1314]
I have a Docker container which installs Ice in it as part of the build process, as per the [instructions on the ZeroC website](https://zeroc.com/downloads/ice/3.7/cpp#ubuntu), which up until recently has worked fine. Since last week, I have been getting the following error for Ubuntu 16.04, and a similar one for Ubuntu 18.04:
`W: The repository 'http://zeroc.com/download/Ice/3.7/ubuntu16.04 stable Release' does not have a Release file.`

On Ubuntu 16.04, that is followed by:
`E: Failed to fetch https://zeroc.com/download/Ice/3.7/ubuntu16.04/dists/stable/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`
And Ice fails to install entirely, as it can't find the packages on apt.

On Ubuntu 18.04, the install proceeds as normal, but it is now installing version 3.7.0, whereas before it was installing version 3.7.1, which is an issue for me.

Will this be fixed or are the changes permanent (no more support for Ubuntu 16.04)?

**Comment by externl** [comment]
I suspect this is caused by the the recent expiration of Let's Encrypt's old root CA. 

See https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021.
