### ISSUE TITLE
About ICE feature 

### ISSUE THREAD

**Issue by Achari-Sumanth** [zeroc-ice/ice#1316]
- Ice Version [e.g. 3.7.4]
 - OS: Linux

Do ice framework have any features of storing logs like errors,warnings, info,debug etc, of applications ??

**Additional context**

**Comment by pepone** [comment]
You should use the system logger, Ice on Linux supports both Syslog and Systemd Journal see:

* https://doc.zeroc.com/ice/3.7/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.7-Ice.UseSyslog
* https://doc.zeroc.com/ice/3.7/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.7-Ice.UseSystemdJournal

**Comment by Achari-Sumanth** [comment]
We've video streaming , Object detection applications. Can this system logger feature in Ice store logs of respective application ?

**Comment by pepone** [comment]
You should not use the log as your video store, you can log an event and include the ID of the video that was recorded, but you must store the videos somewhere else in the file system or in a database.

**Comment by Achari-Sumanth** [comment]
Thank you got it. 

Is there any way that , we can collect the logs of an application which is running inside the docker container and store them on host machine using ice ? 

Additional content : 
1. Ice should not be installed inside the docker container.
2. We are using IceBox service to start/stop the container.
3. We have to retrieve and store the logs of the application (running inside the container) using IceBox Service (outside the container).
