### ISSUE TITLE
Why UdpTransceiver destructor never be called?

### ISSUE THREAD

**Issue by yaojibin** [zeroc-ice/ice#1318]
Ice Version [3.7.6]
OS: Win 10

My application uses IceGrid, and all participant uses IceLocatorDiscovery.
when the application begins to run, the IceGridNode(also act as IceGrid Registry) memory and assigned port continued increase,
I go through the ice code, found that  the UdpTransceiver continued construct, BUT THE DESTRUCTOR NEVER BE CALLED.
I know their must be some mistake in my code, but I can't figured out.

So my question is:
when does ICE close UDP port, and call UdpTransceiver‘s destructor？

**Comment by pepone** [comment]
The connection keeps a shared pointer to the transceiver, and the destructor is called after the connection is closed and removed from the connection factory. You can set `Ice.Trace.Network=1` to see when the connection is closed.
