### ISSUE TITLE
GetVersionEx deprecated in Windows 8.1

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#132]
We use that in IceGrid/PlatformInfo.cpp

see [ICE-5464]

**Comment by bernardnormier** [comment]
We should use [GetProductInfo](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getproductinfo), but it's better to fix this minor issue in a non-patch release.

**Comment by bernardnormier** [comment]
There is no direct replacement. Let's worry about it when it's removed.
