### ISSUE TITLE
Building Ice 3.7.7

### ISSUE THREAD

**Issue by j-w-jones** [zeroc-ice/ice#1339]
I'm trying to build Ice from Source for use with C++. I'm using GCC 10.3.0 and have performed the following steps:

make CONFIGS=cpp11-shared V=1 srcs
make install

This built everything ok.

The first thing I noticed is that there are no libraries with "++11" in the filename so I changed my application to link with libIce.so. 

I then get a load of unresolved symbols (some of them are listed below). I am compiling my code with -DICE_CPP11_MAPPING.

When I was compiling with the standard CentOS 7 g++ compiler (v4.8.5 I believe) and using the libraries from your repository everything worked fine. However, when I moved to GCC 10.3 I noticed various segmentation faults occurring within the Ice libraries - this led me to try to compile my own libraries from source.

Any help would be appreciated.

Jason

-------------------

Some of the errors are:

/home/websim/WebSim/WebSim/Server/RemoteControllerExe/remote_controller_exe.cpp:44: undefined reference to `IceUtil::CtrlCHandler::CtrlCHandler(std::function<void (int)>)'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o: In function `Ice::createProperties(int&, char**, std::shared_ptr<Ice::Properties> const&)':
/opt/Ice-3.7.7/include/Ice/Initialize.h:168: undefined reference to `Ice::createProperties(int&, char const**, std::shared_ptr<Ice::Properties> const&)'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o: In function `Ice::Value::Value()':
/opt/Ice-3.7.7/include/Ice/Value.h:31: undefined reference to `vtable for Ice::Value'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o: In function `Ice::Value::~Value()':
/opt/Ice-3.7.7/include/Ice/Value.h:36: undefined reference to `vtable for Ice::Value'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o:(.data.rel.ro._ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE[_ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE]+0x20): undefined reference to `Ice::Value::ice_preMarshal()'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o:(.data.rel.ro._ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE[_ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE]+0x28): undefined reference to `Ice::Value::ice_postUnmarshal()'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o:(.data.rel.ro._ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE[_ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE]+0x38): undefined reference to `Ice::Value::ice_getSlicedData() const'
CMakeFiles/RemoteControllerExe.dir/remote_controller_exe.cpp.o:(.data.rel.ro._ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE[_ZTVN3Ice11ValueHelperIN5IceMX7MetricsENS_5ValueEEE]+0x40): undefined reference to `Ice::Value::_iceWrite(Ice::OutputStream*) const'

 but this didn't fix anythin
This builds everything ok but I am getting a load of unresolved symbols when I link my application to the installed libraries.
Upon further investigation I noticed that there is no libIce++11.so

 I've also noticed that there is an libIceUtil.a library created but I thought later versions of Ice had included that inside libIce.so.

**Comment by pepone** [comment]
I think the problem is that you only set `CONFIGS=cpp11-shared` for the build, 
```
make CONFIGS=cpp11-shared V=1 srcs
make install
```

Here the `install` command triggers a separate build, for the default configuration `shared`, try to run `install` with the `cpp11-shared` configuration:

```
make CONFIGS=cpp11-shared V=1 install
```

**Comment by j-w-jones** [comment]
Hi Jose

That was exactly my problem - everything has compiled now. Many thanks for that tip.

A second problem I have noticed is that it doesn't build the executables for icegridnode, glacier2router or icegridregistry. I need all of these to run my software.

Can these be built from source? Is there another target to 'make'?

Thanks again,

Jason

**Comment by pepone** [comment]
> A second problem I have noticed is that it doesn't build the executables for icegridnode, glacier2router or icegridregistry. I need all of these to run my software.

Those use the C++98 mapping and are only build with the C++98 mapping, but you can use them along applications that use the C++11 mapping.

You can build everything from sources, here you will need both the C++98 and C++11 mappings builds, you can specify both configurations in `CONFIGS` like:

```
make CONFIGS=cpp11-shared,shared install
```

Or to build all supported configurations for your platform try:

```
make CONFIGS=all install
```

This include the static libraries.

> I don't need the GUI or any of the other language mappings.

The GUI is part of the Java source distribution, but you can also install the `zeroc-icegridgui` package this shouldn't conflict with you C++ source builds. 

Cheers,
Jose

**Comment by j-w-jones** [comment]
Thanks again Jose.

I've compiled and installed both configs and everything is working as it should.
