### ISSUE TITLE
Confusion regarding optional values and python

### ISSUE THREAD

**Issue by mattaustin** [zeroc-ice/ice#1359]
**Version(please complete the following information):**
 - Ice Version 3.7.2
 - OS: Debian Buster
 - Distribution: Apt

**Describe the bug**
I'm attempting to update a slice file to add an optional value, following the guidelines at [Optional Operation Parameters and Class Data Members](https://doc.zeroc.com/ice/3.7/client-server-features/versioning/versioning-through-incremental-updates#id-.VersioningthroughIncrementalUpdatesv3.7-OptionalOperationParametersandClassDataMembers).

```slice
sequence<FooInfo> listFoo(int number, bool all, optional(1) string bar);
```

**Expected behavior**
A python client should not be required to provide an optional value. When running my tests I see the error:

> listFoo() missing 1 required positional argument: 'bar'

In the generated python (using slice2py) I can see the `bar` argument is a required positional argument, and I would have expected it to be a keyword argument with a default value of `Ice.Unset`.

Generated:
```python
def listFoo(self, number, all, bar, context=None):
```

Expected:
```python
def listFoo(self, number, all, bar=Ice.Unset, context=None):
```

**Additional context**
Am I misinterpreting how optional values work with the python language mapping? How can I add an additional optional parameter and keep my old python code working (able to call `listFoo` without having to update their codebases (using shared slice sources)?

**Comment by pepone** [comment]
Hi @mattaustin 

Optional here is about on-the-wire-contract, when the runtime marshal and unmarshal the request the parameters are optional, if a client doesn't send the parameter the server sees just an unset parameter, but as you just found they are still required parameter with the python mapping.

An old client is only affected once the Slice files are updated to include new parameters, old clients that keep using old Slice files are unaffected.

I understand that it is convenient to make `Ice.Unset` the default value for optional, we are considering making this change for the `3.7.8` release, this will only apply to optional parameters that are defined after all required parameters, as we cannot have keyword arguments before non-keyword arguments. 

See #1365

**Comment by mattaustin** [comment]
Thank you!
