### ISSUE TITLE
ReferenceError: T is not defined

### ISSUE THREAD

**Issue by Akatroj** [zeroc-ice/ice#1361]
**Version(please complete the following information):**
 - Ice Version 3.7.71
 - OS: Windows
 - Distribution: npm

**Describe the bug**
Trying to use Ice version 3.7.71 with node.js produces an error:
 
```
node_modules\ice\src\Ice\ModuleRegistry.js:46
type = T[components[i]];
^

ReferenceError: T is not defined
```
**Expected behavior**
the library is not fucking broken and actually works

**Additional context**
I can just downgrade to 3.7.60 and it works for me, but I think shipping broken code is a bad idea guys

**Comment by externl** [comment]
Hi @Akatroj, we are sorry to hear that you are frustrated. However, your tone and language is are not very constructive. Please update your issue with kinder words and we'll be happy to help.
