### ISSUE TITLE
Deprecate SessionFactoryHelper setRouterIdentiy

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#137]
It will be more convenient to have setRouterInstanceName/getRouterInstaceName methods instead of setRouterIdentity/getRouterIdentity, as far as i see the router identity name is always "router" and is hard coded in "Glacier2/SessionRouterI.cpp"

We should deprecate "setRouterIdentity/getRouterIdentity" and add "setRouterInstanceName/getRouterInstaceName"

**Comment by bernardnormier** [comment]
We removed the SessionHelper for 3.8.
