### ISSUE TITLE
C++ tests should print stack traces

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#138]
In the C++ testsuite there are case where exception gets printed to cerr, will be good to always used the logger classes and to also enable stack traces for all tests

@bernardnormier  comment

For release builds, we could also give the option to enable stack traces with https://doc.zeroc.com/display/Ice37/Miscellaneous+Ice.*+Properties#MiscellaneousIce.*Properties-Ice.PrintStackTraces.

[ICE-8070]

**Comment by bernardnormier** [comment]
I fixed it when I included in the stack trace in `operator<<` for exceptions.
