### ISSUE TITLE
Problem on using ice in MATLAB

### ISSUE THREAD

**Issue by fresh-ji** [zeroc-ice/ice#1389]
i m studying using ice in MATLAB and i want to compile my .m file into exe. so i use "mcc", but the exe goes wrong. Could you give me some advice.
Thanks!
<img width="823" alt="Screenshot 2022-08-30 103259" src="https://user-images.githubusercontent.com/25540984/187397624-e362397a-a7ad-4949-8da7-9e0ebcc5a2d4.png">
<img width="370" alt="Screenshot 2022-08-30 103345" src="https://user-images.githubusercontent.com/25540984/187397642-aff1db0f-8e0d-4a4c-b9c6-459a582f0a39.png">

**Comment by pepone** [comment]
Can you try adding the Ice toolbox to your PATH environment variable, or just copy the DLL and MEXW64 files next to your executable?

**Comment by fresh-ji** [comment]
in fact i have copied all these files in my executable folder   -_-

<img width="749" alt="Screenshot 2022-08-31 085712" src="https://user-images.githubusercontent.com/25540984/187569802-13a274c2-c983-4194-8d94-90e3ab9c43fc.png">
