### ISSUE TITLE
How to solve the upCast error in Zero C Ice 3.4.2 compilation? - Gcc - 4.8.5 compile with clang

### ISSUE THREAD

**Issue by wangzb26** [zeroc-ice/ice#1390]
**Version(please complete the following information):**
 - Ice Version [3.4.2]
 - OS: [CentOS 7.9]
 - GCC: [4.8.5]

 I have to build old Server Project. Old Server Project use ZeroC Ice 3.4.2 in its framework. I tried making Old Server Project and got stuck in a compilation error.

The error is as follows:
  file included from../Ice/AcceptorF.h:15:0
from./Ice/Acceptor.h:14 from Acceptor.cpp:10:
./../include/Ice/Handle.h:In instantiation of 'IceInternal::Handle<T>::Handle(T*) [with T = Ice::Communicator]':
/include/Ice/0utgoingAsync:49:16: required from here 
1../include/Ice/Handle.h:66:30:错误:'upcast’was not declared in this scope, and no declarations were found by argument-depend[-fpermissive]
upCast(this-> ptr)->incRef);
In file included from./Ice/Networkh:19:0
from/Ice/Acceptor.h:16， from Acceptor.cpp:10:
../include/Ice/LogqerF.h:64:29:附注:'Ice::Local0biect* IceInternal::upCast(Ice::Logger*)’ declared here, later in the transla ICE API ::Ice::LocalObject* upCast(::Ice::Logger*);
In file included from ../Ice/AcceptorF.h:15:0
from../Ice/Acceptor.h:14 from Acceptor.cpp:10:
1../include/Ice/Handle.h:In instantiation of 'IceInternal::Handle<T>::~Handle() [with T = Ice::Communicator]':
:/include/Ice/OutgoingAsynch49:16: required from here 
./include/Ice/Handle.h:106:30:错误:'upcast’was not declared in this scope, and no declarations were found by arqument-depen[-fpermissivel
upCast(this-> ptr)-> decRef():

I tried Googling several times and was stuck with just two links. None of them is solving my problem. 

I visited the website address ：
https://zeroc.com/forums/patches/5647-patch-compiling-ice-clang-gcc4-7-a.html
an error:     Internal Server Error.

Thanks for providing the patch download address.

**Comment by pepone** [comment]
https://forums.zeroc.com/discussion/5799/patch-for-compiling-ice-with-clang-and-gcc4-7

**Comment by cloud-yd** [comment]
Both of the above links are dead

**Comment by externl** [comment]
> Both of the above links are dead

The second link (https://forums.zeroc.com/discussion/5799/patch-for-compiling-ice-with-clang-and-gcc4-7) should be working again now.

**Comment by cloud-yd** [comment]
> > 以上两个链接都已失效
> 
> 第二个链接（https://forums.zeroc.com/discussion/5799/patch-for-compiling-ice-with-clang-and-gcc4-7）现在应该再次工作。

Thank you for the link, but I have upgraded to 3.6.5
