### ISSUE TITLE
Create SPM plug-in to run slice2swift compiler

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1431]
Now that SPM finally has support for plug-ins we should add a plug-in that runs the slice2swift compiler, and get rid of the SPM distribution (which includes the generated code).

See the feature presentation at [wwdc 2022](https://developer.apple.com/videos/play/wwdc2022/110401/)

**Comment by externl** [comment]
This was implemented in f476bb0a8c5f2c7d9c5999709f528335f2675e7f
