### ISSUE TITLE
Refactor IceSSL to be a core plug-in built-in Ice library

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#146]
Now that IceSSL use the default SSL implementation for each OS and doesn't depend on third party libraries will be worth bundle it with Ice library.

One thing to keep in mind is that we want to support separate IceSSL implementation, specially on Windows we support SChannel (default system impl) and OpenSSL

We want to do this for all languages that support IceSSL

see [ICE-3247]

**Comment by bernardnormier** [comment]
Fixed in C#.
