### ISSUE TITLE
Add support for Linux binary wheels?

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#147]
See https://www.python.org/dev/peps/pep-0513 and https://www.python.org/dev/peps/pep-0571

The major annoyance with providing these wheels is that it will require to embed OpenSSL with the wheel given that OpenSSL isn't part of the external libraries that the module is allowed to link with. This imply that we would need to update the binary wheel whenever OpenSSL needs be patched for security issues.

**Comment by pepone** [comment]
IMO we should not do that, embedding OpenSSL seems really bad and build the pip package in a Linux distribution is really simple, besides we also provide Python packages for supported distributions

**Comment by bernardnormier** [comment]
We should not embed our own copy of OpenSSL and support for SSL/TLS is a must have. 

So let's postpone this work until there is a manylinux platform tag with OpenSSL, or some other solution for using the system's OpenSSL library.
