### ISSUE TITLE
Upgrading in Java from 3.5.1 to 3.7.8 issues

### ISSUE THREAD

**Issue by sergiocapozzi77** [zeroc-ice/ice#1473]
**Version(please complete the following information):**
 - Ice Version 3.7.8
 - OS: windows
 - Distribution: [e.g. YUM, Apt, Homebrew]

I have upgraded my project ice version from 3.5.1 to 3.7.8
All of the generated proxies are giving me an error that Ice is not found.
I did notice that the 3.5.1 package has all the package like Ice, IceInternal in its root. While 3.7.8 has them inside com.zeroc

How to fix the issue?

Thanks

**Comment by pepone** [comment]
Hi @sergiocapozzi77 

With Ice 3.7 there are two Java mappings see:

- https://doc.zeroc.com/ice/3.7/language-mappings/java-mapping/selecting-the-java-mapping
- https://doc.zeroc.com/ice/3.7/release-notes/upgrading-your-application-from-ice-3-6#id-.UpgradingyourApplicationfromIce3.6v3.7-JavaChanges
- https://doc.zeroc.com/ice/3.7/release-notes/upgrading-your-application-from-ice-3-5#id-.UpgradingyourApplicationfromIce3.5v3.7-Javachanges

Let us know if you still have problems after revising these links.

Cheers,
Jose

**Comment by sergiocapozzi77** [comment]
Hi,

I was already using the compat flag, but can't really see any progress even removing or adding these flags back.

This is my package structure:
![16806086999324648214848934063477](https://user-images.githubusercontent.com/44396279/229781702-d5b1abe8-310e-4ba8-bad1-93a7c685830c.jpg)
 And this the issue package Ice does not exist 
![16806087311244578419494883957327](https://user-images.githubusercontent.com/44396279/229781774-546a51e6-d69d-4d39-8617-b01680af9d51.jpg)

**Comment by pepone** [comment]
`ice-3.7.8.jar` is the Ice JAR for the new Java mapping, for the compact mapping your project must use `ice-compact-3.7.8.jar`

In your screenshot, I see you are using `icegrid:3.5.1` and `ice-3.7.8`, you cannot mix Ice JARs version like this, you should upgrade all Ice JARs to 3.7.8, or better use 3.7.9, which was released a few days ago.

If you are using Gradle your dependencies will look something like:

```
implementation 'com.zeroc:ice-compat:3.7.9'
implementation 'com.zeroc:icegrid-compat:3.7.9'
```
