### ISSUE TITLE
Unable to automatically resume bidirectional communication after network reconnection

### ISSUE THREAD

**Issue by qinrhx** [zeroc-ice/ice#1479]
### Version

Ice 3.7.3
OS Ubuntu TLS 20.3

### Describe the bug

When using Glacier2's Callback or Connection's createProxy for bidirectional communication, if the network is interrupted and restored, the client will recreate the TCP connection. 

However, the callback previously created by the server will become invalid, which means that the client cannot initiate requests actively and must explicitly reinitialize the bidirectional communication instance. 

TCP connections can be restored without awareness, but bidirectional communication requires explicit reinitialization, which is obviously unreasonable.

Is there a way to automatically recover the callback of bidirectional communication after reconnecting the network?

### Expected behavior

I hope that after TCP reconnection, two-way communication can also be restored without perception

**Comment by bernardnormier** [comment]
This is the expected (and documented) behavior:
https://doc.zeroc.com/ice/3.7/ice-services/glacier2/callbacks-through-glacier2#id-.CallbacksthroughGlacier2v3.7-CallbacksandConnectionClosure

In other words, if you use "bidir callbacks" with Glacier2 or plain [bidir connections][bidir], you are associating state with your connections. If the connection drops, you need to re-associate this state when you reconnect, even if this reconnection is automatic. 

Ice provides callbacks to detect connection closure--see [using connections][using-connections].

I agree it would be nicer if bidir callback registration could somehow survive connection closure/reconnection. However, it's not an easy problem to solve.

All the best,
Bernard

[bidir]: https://doc.zeroc.com/ice/3.7/client-server-features/connection-management/bidirectional-connections
[using-connections]: https://doc.zeroc.com/ice/3.7/client-server-features/connection-management/using-connections
