### ISSUE TITLE
ARM64 / Aarch64

### ISSUE THREAD

**Issue by sandip-shah** [zeroc-ice/ice#1483]
### Version

- Ice version 3.7.9
- OS - macOS Ventura 13.4 on M2 processor
- Distribution - Source code / PIP

### Describe the bug

pip install zero-ice fails.

When I try to download the src code and install it from there it fails.

It fails with the error - 'readlink' is implicitly declared in the following two files:

src/ice/mcpp/system.c
src/ice/cpp/src/Slice/SliceUtil.cpp

I had to insert line 45 (shown below) for it to compile and install the egg file:

44 #include    "unistd.h"              /* For getcwd(), readlink() */
45 int readlink(const char *pathname, char *buf, size_t bufsiz);
46 #elif   HOST_COMPILER == MSC || HOST_COMPILER == LCC

Thanks.

### Expected behavior

pip install zero-ice should have worked.

### Additional context

seems like for 64 bit versions implicit declarations are not allowed and one has to do an explicit declaration which the line 45 above does.

**Comment by pepone** [comment]
Hi @sandip-shah,

Thanks for bringing this to our attention, we have published new versions of pip, gem, and npm packages that were affected by this issue:

- https://pypi.org/project/zeroc-ice/3.7.9.1/
- https://www.npmjs.com/package/slice2js
- https://rubygems.org/gems/zeroc-ice/versions/3.7.9.1
