### ISSUE TITLE
How do I download an ICE library that supports both X86 and arm64 through Home brew

### ISSUE THREAD

**Issue by hongshao361** [zeroc-ice/ice#1485]
### Version

-3.7.9
- Mac OS
- How do I download an ICE library that supports both X86 and arm64 through Home brew

### Describe the bug

How do I download an ICE library that supports both X86 and arm64 through Home brew

### Expected behavior

How do I download an ICE library that supports both X86 and arm64 through Home brew

**Comment by externl** [comment]
@hongshao361 Could you describe what issue you're trying to solve here? Is this a development issue, or a deployment/packing issue? Are you using the `ice` formula from the core Homebrew tap or the zeroc-ice tap?

Homebrew formulae are either built from source directly on your machine or will download a pre-compiled "bottle" for the architecture of your machine (If one exists). Ice doesn't provide fat binaries that support multiple architectures. 

Apple's Rosetta Translation Environment will allow for x64 code to run on Apple Silicon (arm64). There is tool that works the  reverse direction. If this is what you need you can tell Homebrew to [install a specific bottle arch](--bottle-arch) (I didn't test this).

**Comment by hongshao361** [comment]
> @hongshao361 Could you describe what issue you're trying to solve here? Is this a development issue, or a deployment/packing issue? Are you using the `ice` formula from the core Homebrew tap or the zeroc-ice tap?
> 
> Ice doesn't provide fat binaries that support multiple architectures. Homebrew formulae are either built from source directly on your machine or download a pre-compiled "bottle" for the architecture of your machine (If one exists).
> 
> Apple's Rosetta Translation Environment will allow for x64 code to run on Apple Silicon (arm64). There is no tool that works in the reverse direction. If this is what you need you can tell Homebrew to [install a specific bottle arch](--bottle-arch) (I didn't test this).

I deployed ICE-3.7.9 in X86 environment, but an error "Undefined symbols for architecture arm64:" was reported when packaging, Build Active Architecture Only select YES to package. This will cause computers that cannot run on the M1 and M2 to fail

**Comment by hongshao361** [comment]
> @hongshao361 Could you describe what issue you're trying to solve here? Is this a development issue, or a deployment/packing issue? Are you using the `ice` formula from the core Homebrew tap or the zeroc-ice tap?
> 
> Ice doesn't provide fat binaries that support multiple architectures. Homebrew formulae are either built from source directly on your machine or download a pre-compiled "bottle" for the architecture of your machine (If one exists).
> 
> Apple's Rosetta Translation Environment will allow for x64 code to run on Apple Silicon (arm64). There is no tool that works in the reverse direction. If this is what you need you can tell Homebrew to [install a specific bottle arch](--bottle-arch) (I didn't test this).
![767A32165E776311FEEECF7D02FFE51A](https://github.com/zeroc-ice/ice/assets/38657410/e0cca8c2-76b1-4ad3-9101-d52d822a2e39)

**Comment by hongshao361** [comment]
> @hongshao361 Could you describe what issue you're trying to solve here? Is this a development issue, or a deployment/packing issue? Are you using the `ice` formula from the core Homebrew tap or the zeroc-ice tap?
> 
> Ice doesn't provide fat binaries that support multiple architectures. Homebrew formulae are either built from source directly on your machine or download a pre-compiled "bottle" for the architecture of your machine (If one exists).
> 
> Apple's Rosetta Translation Environment will allow for x64 code to run on Apple Silicon (arm64). There is no tool that works in the reverse direction. If this is what you need you can tell Homebrew to [install a specific bottle arch](--bottle-arch) (I didn't test this).
<img width="500" alt="WeChatac9fb900ac925816bd47b32b9f571455" src="https://github.com/zeroc-ice/ice/assets/38657410/75733a9a-f0d6-43a6-b3f3-a71362ecfe59">

**Comment by hongshao361** [comment]
> @hongshao361 Could you describe what issue you're trying to solve here? Is this a development issue, or a deployment/packing issue? Are you using the `ice` formula from the core Homebrew tap or the zeroc-ice tap?
> 
> Ice doesn't provide fat binaries that support multiple architectures. Homebrew formulae are either built from source directly on your machine or download a pre-compiled "bottle" for the architecture of your machine (If one exists).
> 
> Apple's Rosetta Translation Environment will allow for x64 code to run on Apple Silicon (arm64). There is no tool that works in the reverse direction. If this is what you need you can tell Homebrew to [install a specific bottle arch](--bottle-arch) (I didn't test this).

How to solve this problem

**Comment by pepone** [comment]
@hongshao361 Please don't post the same question over multiple threads.

As @externl pointed out Ice doesn't provide fat binaries. 

You can do as @externl mention, build for x64, and use Apple's Rosetta Translation Environment to run the application in other architectures.

Another alternative would be to create an XCFramework with the required platforms and link with this, we don't provide such a framework for C++, check [Apple docs](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle)

Note we provide XCFramework with the [Swift language mapping](https://github.com/zeroc-ice/ice/tree/3.7/swift) and the Cartage packaging.

**Comment by hongshao361** [comment]
> @hongshao361 Please don't post the same question over multiple threads.
> 
> As @externl pointed out Ice doesn't provide fat binaries.
> 
> You can do as @externl mention, build for x64, and use Apple's Rosetta Translation Environment to run the application in other architectures.
> 
> Another alternative would be to create an XCFramework with the required platforms and link with this, we don't provide such a framework for C++, check [Apple docs](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle)
> 
> Note we provide XCFramework with the [Swift language mapping](https://github.com/zeroc-ice/ice/tree/3.7/swift) and the Cartage packaging.

thanks，Apple Store audit needs to adapt to ARM64, but the ICE library does not support, whether all items using the ICE library can not be put on the store
