### ISSUE TITLE
Improve SSL testing

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#149]
We should look into testing the following if we don't already do:
- Certificate expiration
- Certificate chains
- OCSP
- Revocation
- Mismatching/insecure client/server cipher suites

**Comment by bentoi** [comment]
We should also get rid of of tests for legacy/deprecated features/protocols such as DSA, TLS 1.1 ... we'll need to decide what SSL protocol we want to support first.

**Comment by pepone** [comment]
We already test:

Certificate expiration
Certificate chains
OCSP
Revocation

> Mismatching/insecure client/server cipher suites

I don't think we need extra tests for this. For example mismatching ciphers are handled at the TLS protocol level. The insecure ciphers are disabled by default on most systems, but it depends on the SSL Engine and the OS.
