### ISSUE TITLE
Static windows build vcxproj library naming

### ISSUE THREAD

**Issue by jvbsl** [zeroc-ice/ice#1502]
### Version

- Ice Version 3.7.9
- OS: Windows

### Describe the bug

When building static Ice library using vcxproj(by changing DynamicLibrary to StaticLibrary) the resulting library name is Ice++11.lib, but FindIce.cmake searches for Ice37++11.lib which then of course can not be found.
If we use cmake to build the static library the naming is Ice37++11.lib and can be found by FindIce.

### Expected behavior

Vcxproj also generating Ice37++11.lib like Cmake does.

### Additional context

So my question would be, would it make sense to add it to the vcxproj:
https://github.com/zeroc-ice/ice/blob/badafe8b848181a720ab96b48da6abc170fd918c/cpp/msbuild/ice.cpp.props#L257
We could basically add it here, or remove the Condition of it being a DynamicLibrary so that the naming of StaticLibrary and DynamicLibrary would be uniform.

Thank you very much in advance

**Comment by bernardnormier** [comment]
We'll fix this static library naming in the next patch release (3.7.10).

Note that we don't support / test building Ice as static libraries on Windows.  It should work, and it apparently does, which is great.

**Comment by jvbsl** [comment]
Great to hear, any special requirements? Want me to do a PR?

**Comment by bernardnormier** [comment]
We'll fix it together with #1503. As you can see, this name computation is entangled with the UWP support.

**Comment by jvbsl** [comment]
Alright thank you very much for your help
Just found out some time ago that the vcpkg port needs work in the library finding department anyway, so we can workaround that naming with that work then for 3.7.9 already^^

**Comment by jvbsl** [comment]
I was just made aware that I had a little mixup, there of course is no cmake for zeroc-ice. The cmake version was in a fork for mumble https://github.com/mumble-voip/ice
So there really is no naming discrepancy between CMake and vcxproj, sorry about that.

**Comment by jvbsl** [comment]
Thank you very much for all the work ;)
At least for cpp11 mappings(which is everything I need) it looks promising
