### ISSUE TITLE
Remove UWP support

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1503]
UWP is dead; we should remove all UWP-related code.

**Comment by dg0yt** [comment]
Is it really dead? The microsoft staff at vcpkg still maintains (and even upgrades) the UWP CI.
AFAIU it is still useful in connection with the Windows Store. 
(And recently they added xbox targets which also present a restricted API.)
However, most vcpkg ports don't use separate msbuild files for UWP.

**Comment by bernardnormier** [comment]
We stopped shipping uwp NuGet packages years ago:
https://www.nuget.org/packages?q=zeroc.ice.uwp

Nobody requested them back.
