### ISSUE TITLE
Add cross-build instructions

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#151]
We should document how to cross-build some of the Ice components/demos with the make build system.

**Comment by khoinguyen90** [comment]
@bentoi How is your progress of cross-build instructions ?
Currently, i want to run ice on my udoo quad board (arm-linux-gnueabihf) but i can not find any complete íntructions to do it.
Do you have any advice for me ?

**Comment by bentoi** [comment]
On Ubuntu, I recommend to just use the armhf or arm64 packages that we started publishing with Ice 3.7.2 (Ubuntu 18.04).

See the following links for instructions on how to install Ice:
- https://zeroc.com/downloads/ice#ubuntu
- https://doc.zeroc.com/ice/3.7/release-notes/using-the-linux-binary-distributions

**Comment by khoinguyen90** [comment]
@bentoi  Thank you,
Actually, i want o cross compile it. Is there any way to do that.
I tried to compile on ARM device and then copy binaries to ubuntu to used for cross-compiling.
But there are some problem because gcc version differences (gcc on ARM device is too old)

**Comment by bentoi** [comment]
For which target and build platform/operating systems exactly do you want do cross-compilation?

Do you want to cross-compile Ice or just your application using the already available ARM packages that we provide for Ubuntu 18.04?

**Comment by khoinguyen90** [comment]
My target is udoo quad board (armv7l GNU/Linux) and i want to cross-compile ice on ubuntu 16.04.

**Comment by khoinguyen90** [comment]
It is very detailed. I succeeded in running ice on armhf.
Thank you very much.

**Comment by bernardnormier** [comment]
While the 3.7 build system supports cross-compiling (with some caveat, see above), it's an uncommon feature and we plan to drop it for Ice 4.0, so no need to document cross-compiling for 3.7.

**Comment by qw54216** [comment]
> 
> 
> It is very detailed. I succeeded in running ice on armhf.
> Thank you very much.

@khoinguyen90   I know you had succeeded in running ice on your udoo quad board (armv7l GNU/Linux),could you tell me the detailed progress of cross-compiling? My platform is AM3352 board.Thank you very much.

**Comment by khoinguyen90** [comment]
> > It is very detailed. I succeeded in running ice on armhf.
> > Thank you very much.
> 
> @khoinguyen90 I know you had succeeded in running ice on your udoo quad board (armv7l GNU/Linux),could you tell me the detailed progress of cross-compiling? My platform is AM3352 board.Thank you very much.

Just follow @bentoi above instruction, you will have library at `ice/cpp/lib/arm-linux-gnueabihf$` to use for cross compile.

**Comment by qw54216** [comment]
> 
> 
> > > It is very detailed. I succeeded in running ice on armhf.
> > > Thank you very much.
> > 
> > 
> > @khoinguyen90 I know you had succeeded in running ice on your udoo quad board (armv7l GNU/Linux),could you tell me the detailed progress of cross-compiling? My platform is AM3352 board.Thank you very much.
> 
> Just follow @bentoi above instruction, you will have library at `ice/cpp/lib/arm-linux-gnueabihf$` to use for cross compile.
@khoinguyen90  According the aboce steps ,when  sudo apt-get install crossbuild-essential-armhf  ,error occurs , "E: Unable to locate package crossbuild-essential-armhf",but why? my OS  is Ubuntu 14.04.5.TKS

**Comment by pepone** [comment]
The package is new in 16.04 see https://packages.ubuntu.com/search?keywords=crossbuild-essential-armhf+&searchon=names&suite=all&section=all

I don't remember if there was a cross compile package available for 14.04, you should try updating your distribution if possible, we only test 18.04 (Bionic) and 16.04 (Xenial) with 3.7

**Comment by qw54216** [comment]
> 
> 
> The package is new in 16.04 see https://packages.ubuntu.com/search?keywords=crossbuild-essential-armhf+&searchon=names&suite=all&section=all
> 
> I don't remember if there was a cross compile package available for 14.04, you should try updating your distribution if possible, we only test 18.04 (Bionic) and 16.04 (Xenial) with 3.7

thank you very much.I will try it.

**Comment by qw54216** [comment]
I have aleady update my distribution with 16.04 successfully.but when  I make PLATFORMS="amd64 armhf" SKIP=slice2%[armhf-static] -j4 ,    an error occurs which indicate:
src/IceUtil/UtilException.cpp: In constructor ‘IceUtil::FileLockException::FileLockException(const char*, int, int, const string&)’:
src/IceUtil/UtilException.cpp:774:102: error: declaration of ‘path’ shadows a member of 'this' [-Werror=shadow]
 IceUtil::FileLockException::FileLockException(const char* file, int line, int err, const string& path):
                                                                                                      ^
cc1plus: all warnings being treated as errors
Makefile:25: recipe for target 'src/IceUtil/build/arm-linux-gnueabihf/static/UtilException.o' failed
make[1]: *** [src/IceUtil/build/arm-linux-gnueabihf/static/UtilException.o] Error 1
make[1]: Leaving directory '/home/dabid/RPC/ice-3.7/cpp'
Makefile:21: recipe for target 'all' failed
make: *** [all] Error 1

Have you ever met this situation?Thank you very much!!

**Comment by qw54216** [comment]
I have aleady update my distribution with 16.04 successfully.But when  I make PLATFORMS="amd64 armhf" SKIP=slice2%[armhf-static] -j4, an error occurs,which discribes  as follows:

Compiling [armhf-shared] src/IceUtil/Unicode.cpp
src/IceUtil/Options.cpp: In member function ‘IceUtilInternal::Options::StringVector IceUtilInternal::Options::parse(const StringVector&)’:
src/IceUtil/Options.cpp:694:32: error: declaration of ‘optArg’ shadows a member of 'this' [-Werror=shadow]
                         string optArg = args[i].substr(p + 1);
                                ^
Compiling [armhf-shared] src/IceUtil/OutputUtil.cpp
Compiling [armhf-shared] src/IceUtil/UUID.cpp
cc1plus: all warnings being treated as errors
Makefile:25: recipe for target 'src/Ice/build/arm-linux-gnueabihf/shared/pic/Options.o' failed
make[1]: *** [src/Ice/build/arm-linux-gnueabihf/shared/pic/Options.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/dabid/RPC/ice-3.7/cpp'
Makefile:21: recipe for target 'all' failed
make: *** [all] Error 1

Have you ever met this situation and how can you solve this problem?Thank you very much!!
