### ISSUE TITLE
Better map C++ exceptions to Python exceptions

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#152]
IcePY converts C++ IceUtil::Exception to python Ice.UnknownException, for example:
testing object adapter with router... 
```
exception ::Ice::UnknownException
{
    unknown = src/Ice/ObjectAdapterI.cpp:724: ::IceUtil::IllegalArgumentException: can't set published endpoints on object adapter associated with a router
}
```
It would be better to find a more appropriate native python exception for IceUtil exceptions.

In Objective-C, we raise `NSException exceptionWithName:NSInvalidArgumentException` for InvalidArgumentException and `NSException exceptionWithName:@"std::exception"` for others.

With Python, we could use ValueError to map InvalidArgumentException and RuntimeError for all other IceUtil exceptions?

**Comment by bentoi** [comment]
Mark:
This is a pretty simple fix. However, I noticed that the extension is currently trapping IllegalArgumentException in a few places (for example) and raising RuntimeError. ValueError seems more appropriate here but I'd be concerned about changing these occurrences in a patch release.
So we can either
a) postpone all of this to 3.8
b) change the general exception translation to raise ValueError and RuntimeError as proposed above but leave existing handling of IllegalArgumentException alone, which is inconsistent but less likely to cause problems
c) change all occurrences of IllegalArgumentException to ValueError and raise other IceUtil exceptions as RuntimeError

**Comment by bentoi** [comment]
Bernard:
Let's postpone this fix to 3.8.
See also ICE-7884. For C++11, we throw now mostly (only?) std::invalid_argument, while for C++98 we throw both IllegalArgumentException and std::invalid_argument.
The correct mapping in Python for both IllegalArgumentException and std::invalid_argument is indeed ValueError. It's however debatable that IllegalArgumentException is the correct way to report "you should not call this operation" as in Benoit's original example. In C++, a more correct error would be std::logic_error, but there is no equivalent in Python.

**Comment by bentoi** [comment]
ICE-8677

**Comment by pepone** [comment]
@bernardnormier what should we do here? do we need a special mapping for `invalid_argument`? with the current convert exception implementation it is converted to `Ice::LocalException`.

**Comment by bernardnormier** [comment]
I think the latest behavior is fine.
