### ISSUE TITLE
IceGridGUI build failure with JDK 8

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1523]
Some problems were found with the configuration of task ':test:compileJava' (type 'JavaCompile').
  - Gradle detected a problem with the following location: 'C:\Users\jose\source\repos\3.7.9\ice\java\lib\ice-3.7.9.jar'.

    Reason: Task ':test:compileJava' uses this output of task ':IceGridGUI:copyTmpJars' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':IceGridGUI:copyTmpJars' as an input of ':test:compileJava'.
      2. Declare an explicit dependency on ':IceGridGUI:copyTmpJars' from ':test:compileJava' using Task#dependsOn.
      3. Declare an explicit dependency on ':IceGridGUI:copyTmpJars' from ':test:compileJava' using Task#mustRunAfter.

**Comment by bernardnormier** [comment]
Why are we building IceGridGUI with JDK 8?

**Comment by pepone** [comment]
> Why are we building IceGridGUI with JDK 8?

I was just testing the supported JDK, see #1522

This error only happens with Gradle 8 upgrades from #1521, in the 3.7 branch is just a warning that we ignore, so far I just pushed a fix for this into #1521
