### ISSUE TITLE
Glacier2 address filtering doesn't allow wildcard ports

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1528]
### Version

```
❯ glacier2router -v
3.7.9
```

### Describe the bug

We document on https://doc.zeroc.com/ice/3.7/property-reference/glacier2#Glacier2.*-Glacier2.Filter.Address.Accept 
that the `Glacier2.Filter.Addrss.Accept` property is a list of address-port pairs. Additonally that

> Each pair is of the form address:port. The address or port number portion can include wildcards ('*') or value ranges or group

However, when you use  a `*` for the port selection Glacier2 issues an error and does not start

```
❯ glacier2router --Ice.Config=config.glacier2 --Glacier2.Filter.Address.Accept='callback:*'
!! 09/26/23 12:10:01.947 glacier2router: error: Glacier2 initialization failed:
   invalid `Glacier2.Filter.Address.Accept' property:
   expected number
```

### Expected behavior

Glacier2 should accept wildcard ports as documented. 

### Additional context

Using a wildcard for the host works fine.

**Comment by externl** [comment]
Not obvious from the documentation but a `:port` is not required. Not having the port seems to give wildcard port behavior.

**Comment by bernardnormier** [comment]
You should use the 3.7 or latest doc:
https://doc.zeroc.com/ice/latest/property-reference/glacier2#Glacier2.*-Glacier2.Filter.Address.Accept

Is this really a documentation bug?

I think it would be fine to not allow `*` for port numbers and fix the doc to match the implementation.
