### ISSUE TITLE
Sometimes findAdapterById is slow

### ISSUE THREAD

**Issue by free-wind-0** [zeroc-ice/ice#1529]
### Version

-Ice Version 3.7.5
-OS Centos 7.9

### Describe the bug

I wrote a client process test, found that sometimes the connection is slow, I set Ice.Trace.Protocol = 1,  found these information，It seems that the icegrid findAdapterById operation is slow，how do I check if there is an icegrid configuration problem?

Code snippet:
```
Ice::InitializationData initData;
initData.properties->setProperty("Ice.Trace.Protocol", "1");
initData.properties->setProperty("Ice.Default.Locator", "IceGrid/Locator:default -h 192.168.7.228 -p 22000");
ic = Ice::initialize(initData);

auto start_time = std::chrono::steady_clock::now();

app_service = Ice::checkedCast<CommonServicePrx>(ic->stringToProxy("commonService"));

auto end_time = std::chrono::steady_clock::now();
std::cout << "Cost: " << std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count() <<  std::endl;
```

Protocol trace info:
-- 09/28/23 16:55:37.023 Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 09/28/23 16:55:37.024 Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 73
   request id = 1
   identity = IceGrid/Locator
   facet =
   operation = findObjectById
   mode = 1 (nonmutating)
   context =
   encoding = 1.1
-- 09/28/23 16:55:37.024 Protocol: received reply
   message type = 2 (reply)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 71
   request id = 1
   reply status = 0 (ok)
   encoding = 1.1
-- 09/28/23 16:55:37.025 Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 82
   request id = 2
   identity = IceGrid/Locator
   facet =
   operation = findAdapterById
   mode = 1 (nonmutating)
   context =
   encoding = 1.1

-- 09/28/23 16:55:40.039 Protocol: received reply
   message type = 2 (reply)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 71
   request id = 2
   reply status = 0 (ok)
   encoding = 1.1
-- 09/28/23 16:55:40.041 Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 09/28/23 16:55:40.041 Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 100
   request id = 1
   identity = commonService
   facet =
   operation = ice_isA
   mode = 1 (nonmutating)
   context =
   encoding = 1.1
-- 09/28/23 16:55:40.042 Protocol: received reply
   message type = 2 (reply)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 26
   request id = 1
   reply status = 0 (ok)
   encoding = 1.1

Cost: 3021

Connect Ice Server OK
-- 09/28/23 16:55:40.042 Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 99
   request id = 2
   identity = commonService
   facet =
   operation = invoke
   mode = 0 (normal)
   context =
   encoding = 1.1
-- 09/28/23 16:55:40.050 Protocol: received reply
   message type = 2 (reply)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 83
   request id = 2
   reply status = 0 (ok)
   encoding = 1.1
{"paramValue":"11279b5f73ca46b4a9442c6ed92cdde7"}
-- 09/28/23 16:55:40.050 Protocol: sending close connection
   message type = 4 (close connection)
   compression status = 1 (not compressed; compress response, if any)
   message size = 14
-- 09/28/23 16:55:40.050 Protocol: sending close connection
   message type = 4 (close connection)
   compression status = 1 (not compressed; compress response, if any)
   message size = 14

### Expected behavior

Fast every time, or slow every time

### Additional context

icegridadmin shows that there are 10 adapter on registry

**Comment by bernardnormier** [comment]
The trace output you pasted shows two parts:

1) the resolution of well-known proxy "commonService" over the connection to your IceGrid registry

2) the call to your "commonService" object over a separate connection

Each connection gets its own request IDs - starting with request ID 1 since request ID 0 is reserved for one-way requests.

1) is pretty slow (like 3 seconds). I don't have enough information to tell you why. Maybe IceGrid starts the server that hosts commonService and this start-up takes a few seconds.

2) is fast, which makes sense. Your client talks to the server directly, not through IceGrid.

> Fast every time, or slow every time

It's not clear what your concern is.

For example, if 2 clients connect to the same server through IceGrid, and the first client triggers the on-demand activation of the server, it would make sense that the first client is much slower than the second.

Then, for a given client, the Ice client runtime keeps a "locator cache". If this client has already resolved an adapter ID or well-known proxy, it doesn't need to make a remote call to IceGrid to resolve again, which is much faster than a remote call.

**Comment by free-wind-0** [comment]
@bernardnormier 

This has something to do with our exception design (see https://github.com/orgs/zeroc-ice/discussions/1533#discussion-5681306), Each time an exception is caught, Communicator and checkCast are re-initialized, maybe this design doesn't make sense.

I initially thought that destroying Communicator took a long time, but the test results showed that checkCast occasionally appeared slowly, I just want to find the reason for the occasional slow in order to optimize it

**Comment by bernardnormier** [comment]
@free-wind-0: please don't create bugs for issues/questions with your own design.

**Comment by free-wind-0** [comment]
@bernardnormier 
Ok, but we're not talking about the design, just because this design found the checkCast slow problem, like the demo code I described at the top, it has nothing to do with the design.

I repeated the execution of the program many times, checkCast fast or slow seems not to be the problem of cache, may be related to icegrid configuration or ice server configuration, sometimes even more than 5 seconds received timeout exception, Is there any way to analyze whether this time is normal?
