### ISSUE TITLE
Improve Glacier2 category randomness

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#153]
The Glacier2 category is generated from 20 random bytes and by keeping the remainder of the division by 94 of each byte in order to get a printable character. There's a modulo bias there and the probability of getting char between 33-99 is less than the ones in the range 100-126. It would be good to check if we can get rid of this bias. We should also add a comment to explain why we just don't use a UUID string there (we want the category to be a printable string and minimize the number of characters of the string).

ICE-8842

**Comment by aikoven** [comment]
How about Nano ID? Although it doesn't seem to have C++ implementation (https://github.com/ai/nanoid#other-programming-languages), it seems to fit the needs — it's printable and short, and its randomness is well-tested.

**Comment by bentoi** [comment]
Thanks for the suggestion!

**Comment by pepone** [comment]
For C++11 compilers the simple is to use `uniform_int_distribution` https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution for C++98 compilers we can keep the current code
