### ISSUE TITLE
Typo on documentation for installing Ice

### ISSUE THREAD

**Issue by oscaracena** [zeroc-ice/ice#1531]
### Version

All

### Describe the bug

The page at https://zeroc.com/ice/downloads/3.7/python describes the installation process. In the scripts to add a Debian repository, the added URL has in the url `zeroc.com/ice3.7/`, but it should be `zeroc.com/ice/3.7/`. Otherwise, when running `apt update`, you will get the following error:

```
Err:45 https://download.zeroc.com/ice3.7/ubuntu22.04 stable InRelease              
  403  Forbidden [IP: 18.154.48.24 443]
```

### Expected behavior

The correct url.

### Additional context

![image](https://github.com/zeroc-ice/ice/assets/4654094/8a824205-106c-4347-8e24-996ab5f1adbe)

**Comment by externl** [comment]
Thanks for reporting this @oscaracena, it should be fixed now!
