### ISSUE TITLE
Rename C++98 and C++11 mappings

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1534]
The terms "C++98 mapping" and "C++11 mapping" are confusing as they give the impression these mappings are tied to specific versions of the C++ standard.

https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/selecting-the-c++11-mapping

In practice, the C++98 mapping--really, Ice's original C++ mapping--is compatible with most C++ compilers, including older pre-C++11 compilers and new, modern C++ compilers, even when these compilers are in c++11 or higher mode.

The C++11 mapping--Ice's newer C++ mapping--requires a modern C++ compiler. In Ice 3.7, this C++ compiler must support c++11 and be in c++11 mode (or greater). For 3.8, we should use c++17 features (like std::optional) and up the requirement to c++17 or greater. But at the end of the day, it's still the same mapping, the second incarnation of Ice's C++ mapping.

These mapping names affect the documentation, the macro name (3.7 uses ICE_CPP11_MAPPING) and the SO names (3.7 uses ++11).

We could for example rename C++98 to "original mapping" and C++11 to "new mapping":
```
#define ICE_ORIGINAL_MAPPING  // what Ice 3.7 calls the C++98 mapping
// when not defined, you get the new C++ mapping that requires c++17 or higher
```

And simplify the SO names:
 - no `++` = library for original mapping, e.g. libIce.so.38 (similar to 3.7)
 - `++` suffix  = new mapping, e.g. libIce++.so.38

**Comment by pepone** [comment]
We decided to have a single C++ mapping in 3.8.
