### ISSUE TITLE
Remove support for serializable objects in C#

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1549]
See https://doc.zeroc.com/ice/3.7/language-mappings/c-sharp-mapping/client-side-slice-to-c-sharp-mapping/serializable-objects-in-c-sharp

This feature relies on BinaryFormatter and the runtime support for BinaryFormatter was removed from .NET 8.0. 
See https://aka.ms/binaryformatter

**Comment by pepone** [comment]
This was done as part of #1583
