### ISSUE TITLE
load balancing of application replica group displayed <unknown load balancing policy> when configured with ordered type 

### ISSUE THREAD

**Issue by sepcity** [zeroc-ice/ice#1567]
### Version

- Ice Version: 3.7.9
- OS: Windows

### Describe the bug

when use icegridadmin
application describe myapp

displays
    replica groups
    {
        id = `my_replica_group' load balancing = `<unknown load balancing policy>'
    }

but the load balancing type of the replica group configure with "ordered"

### Expected behavior

displays
    replica groups
    {
        id = `my_replica_group' load balancing = `ordered'
    }

### Additional context

![图片](https://github.com/zeroc-ice/ice/assets/3038572/2acc11e9-9932-4850-a1b3-6878a4e32bfa)

**Comment by pepone** [comment]
Hi @sepcity 

Thanks for reporting this, seems like there is a missing `if` check for `OrderedLoadBalancingPolicy` in https://github.com/zeroc-ice/ice/blob/177766e4b33fe753a3fb46c1a31fd350260a3f47/cpp/src/IceGrid/DescriptorHelper.cpp#L3106

**Comment by sepcity** [comment]
Yeah, You are right!
