### ISSUE TITLE
Consider providing asynchronous version of blocking Ice APIs

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#157]
We still have few APIs which can potentially block:
- object adapter creation
- object adapter activation/deactivation (only if a locator is enabled I believe)
- communicator initialization

While it can be useful in some circumstances, I don't think making `createObjectAdapter` non-blocking is a top-priority, typically object adapters are created at the application initialization where it's ok to make blocking calls. The `activate/deactivate` methods however can typically be used from servant dispatch and here it would be desirable to make sure these 2 don't block (we currently only provide the guarantee that `hold()` won't block).

For the API, we should decide whether or not we want "async" versions of the `createObjectAdapter/active/deactivate` methods or if having `waitForCreate/waitForActivate/waitForDeactivate` is sufficient (we currently have `waitForHold/waitForDeactivate` already so it would be more consistent to go with `waitForCreate/waitForActivate`).

The OA creation might require to block for several reasons right now:
- resolving DNS names for the OA endpoints (Endpoints property)
- getting the router server endpoints for routed OAs

The `waitForCreate` method would be useful to wait for the completion of the OA creation... We would have to decide how `createDirectProxy` (potentially indirectly called by addXxx methods or createProxy depending on whether or not the OA is direct/indirect) behaves if it's called before the OA creation completes. It could raise a new `Ice::ObjectAdapterNotInitializedExcetion` exception (but this could potentially break existing applications...). This wouldn't be a problem if we provided an async version of `createObjectAdapter` instead.

The same goes for communicator initialization. Right now, it could block on file access (e.g.: loading certificates, property file), creation of the admin adapter, etc. On some platforms (UWP), we have to workaround some APIs that check for blocking calls from the UI thread... to allow initializing the communicator.

**Comment by bernardnormier** [comment]
An async version of `Communicator::waitForShutdown` could be useful as well. This would allow a server to insert post-shutdown cleanup code without blocking the main thread on waitForShutdown.

This would be mostly interesting in Java and C# where returning from main doesn't necessarily exit. See #108 and https://github.com/zeroc-ice/ice-demos/blob/3.7/java/IceStorm/clock/Subscriber.java.

**Comment by pepone** [comment]
>While it can be useful in some circumstances, I don't think making createObjectAdapter non-blocking is a top-priority, typically object adapters are created at the application initialization where it's ok to make blocking calls. The activate/deactivate methods however can typically be used from servant dispatch and here it would be desirable to make sure these 2 don't block (we currently only provide the guarantee that hold() won't block).

One issue is associating the router with the adapter,  this is only done when the adapter is created, for a GUI application that dynamically configure the router, based on a hostname or some other input, there isn't an API to create this router.

For Glacier2 client applications there is also the case that you recreate the router, to add the servants with the new client category, you can remove the old servants and add the new ones but recreating the adapter is simpler, and it was we did with the helper classes.

I think it might be worth adding it, we might need to split ObjectAdapter construction into a separate InitAsync method, as there is no async constructor and add Async overloads for createObjectAdapter.

**Comment by bernardnormier** [comment]
Fixed in C#.
