### ISSUE TITLE
3.7.10 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [zeroc-ice/ice#1571]
👋 it looks like 3.7.10 release did not get completed, ie no release notes for it. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/153553

**Comment by Dessa** [comment]
also, though that might be a non-factor its not a "release" on github, that might be intentional though as there was a delay of about a week between the git tag and the marking as release on GH in the past.

**Comment by pepone** [comment]
We will be adding the GitHub release page shortly, we just have to publish the new release notes on our website first, so that all links work as expected.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/releases/tag/v3.7.10

**Comment by chenrui333** [comment]
Thanks all!
