### ISSUE TITLE
使用ice3.6.5，icetouch3.6 编译iOS项目生成错误代码

### ISSUE THREAD

**Issue by fuchenming900116** [zeroc-ice/ice#1573]
### Version

xcode 13.2.1 ； mac os 11.7.6;

### Describe the bug

![WX20231128-174458](https://github.com/zeroc-ice/ice/assets/3928370/db82fc00-4c1e-488e-b422-b581f711c2ff)

### Expected behavior

![WX20231128-174252](https://github.com/zeroc-ice/ice/assets/3928370/ab898c39-c14e-4abb-bbee-671701221cde)

**Comment by pepone** [comment]
Xcode 13 is not supported with Ice 3.6, please upgrade to Ice 3.7 and Xcode 15

See supported platforms in https://doc.zeroc.com/ice/3.7/release-notes/supported-platforms-for-ice-3-7-10

**Comment by fuchenming900116** [comment]
OK。Thanks！
