### ISSUE TITLE
illumos: ../cpp/config/Make.rules:20: *** invalid platforms .  Stop.

### ISSUE THREAD

**Issue by Pawlicker** [zeroc-ice/ice#1614]
### Version

Version: 33b7534a599c1b37b3c0fb540a894e8f83287cb8 (the current 3.7 branch release)
OS: [illumos](https://illumos.org) (formerly OpenSolaris/Solaris/SunOS)
Distribution: [OmniOS ](https://omnios.org)omnios-r151048
uname -a: SunOS nect110g 5.11 omnios-r151048-553e69d9fe i86pc i386 i86pc

### Describe the bug

When trying to build using gmake, it throws an error about "invalid platforms" because illumos literally does not exist in the world. I have a feeling this might happen with other *nix operating systems such as the *BSDs as well.
`lain@nect110g:~/ice/cpp$ gmake V=1 -j4 srcs`
`../cpp/config/Make.rules:20: *** invalid platforms .  Stop.`
`lain@nect110g:~/ice$ uname -a`
`SunOS nect110g 5.11 omnios-r151048-553e69d9fe i86pc i386 i86pc`

### Expected behavior

something to actually happen

### Additional context

I'm using https://pkgsrc.joyent.com/ for additional packages.

**Comment by bernardnormier** [comment]
The behavior you're seeing is expected and correct: the Ice build system does not support Solaris (SunOS, Illumos...) and therefore stops immediately.

We used to support Solaris but removed this support a while ago.
