### ISSUE TITLE
Ease certificate verifier requirements

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#162]
An IceSSL certificate verifier implementation is required to not block as its being called by the Ice runtime where only non-blocking activity is expected to occur. It also can't make Ice requests.

We should consider if we can remove some of these restrictions or not.

**Comment by pepone** [comment]
We reworked the way verification callbacks are set with 3.8, but we still them to be non blocking. I think it is fine it would be too complicated to support doing non-blocking io.
