### ISSUE TITLE
Fix messages around tag / optional in the Slice grammar

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1623]
We support 'tag' as an alias for 'optional' in the Slice  grammar, however, the standard term remains 'optional' and therefore that's what error messages should produce.

Unfortunately, https://github.com/zeroc-ice/ice/pull/1590 incorrectly replaced several 'optional' by 'tag'.

**Comment by InsertCreativityHere** [comment]
This was implemented in #2177
