### ISSUE TITLE
Should we Further Relax Underscores in Identifiers?

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#1636]
As of #1631, we now allow users to use underscores in their identifiers without needing a special metadata.
But I think we could go further. The parser still disallows:
- trailing underscores: `cool_`
- leading underscores: `_cool`
- multiple underscores in a row: `cool__stuff`

I could see a case for keeping the restriction on leading underscores, since that has a special meaning in some languages.
But restricting trailing and double underscores just seems unnecessary to me. I agree they're weird, but why should the parser care? Removing these restrictions is backwards compatible, and would let us remove and simply more logic in the scanner.

**Comment by pepone** [comment]
I think double underscores are reserved in C++ https://en.cppreference.com/w/cpp/language/identifiers

**Comment by bernardnormier** [comment]
We should keep these remaining restrictions.
