### ISSUE TITLE
IceStorm retryCount is only support for two-way subscribers

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#164]
We should consider supporting it as well for one-way subscribers. It's unclear why we restrict it to two-way subscribers right now. Connection failures can also be reported by one-way subscribers.

ICE-3226

**Comment by bernardnormier** [comment]
Currently the retryCount for oneway subscribers and batch subscribers must be 0: other values are rejected through an exception (>0) or an assert. "0" is implemented correctly, meaning that any error is fatal and takes the subscriber offline for good.
