### ISSUE TITLE
Reject optional class in Slice

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1644]
The Slice compiler should reject optional parameters and fields with classes, just like slicec does.

Rationale:
despite our best efforts, we could not find a way to encode correctly such parameters/fiedsl.

**Comment by InsertCreativityHere** [comment]
This was primarily implemented by #2211

But the following PRs were also involved in cleaning up our usage of optional classes:
#2089, #2094, #2139, #2201, #2199, #2215, #2264, #2262, and #2271.
