### ISSUE TITLE
Run rake from Swift CI

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1669]
Swift CI currently does not run rake.

As a result, a PR that changes to the list of C++ files included in the C++ build needs to run rake and include the generated Xcode project files (10,000+ lines of changes). This skews the size/complexity of the PR.

For example: https://github.com/zeroc-ice/ice/pull/1668
These Xcode project aside, this PR changes only about 200 lines of code.

The solution is for the Swift CI to run rake. We should also consider _not_ checking in these Xcode project files and always require `rake`.

**Comment by externl** [comment]
I think the simplest is to remove these files from source control and have `Make` generate them.
