### ISSUE TITLE
Set .NET runtime version when running tests

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1673]
The .NET test suite build targets .net6.0, running the test requires .net6 runtime which is not installed by default if you are using .NET 8 SDK.

We can set ` --fx-version` to specify the runtime to use, the python script can check the available runtimes by running `dotnet --list-runtimes`

**Comment by bernardnormier** [comment]
Could we use instead:
```
--roll-forward Major
```

It seems much simpler.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet

**Comment by bernardnormier** [comment]
Maybe we should update the project files and not the Python scripts:
https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-runtime-roll-forward

**Comment by pepone** [comment]
```
diff --git a/csharp/msbuild/ice.common.props b/csharp/msbuild/ice.common.props
index f08768f661..2ec88086a6 100644
--- a/csharp/msbuild/ice.common.props
+++ b/csharp/msbuild/ice.common.props
@@ -23,6 +23,7 @@
     <PublishRepositoryUrl>true</PublishRepositoryUrl>
     <RepositoryUrl>https://github.com/zeroc-ice/ice</RepositoryUrl>
     <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
+    <RollForward>LatestMajor</RollForward>
   </PropertyGroup>
```

This works for all tests except for IceBox/*

**Comment by pepone** [comment]
The IceBox failures seem unrelated to this.

**Comment by bernardnormier** [comment]
I believe the fix is incorrect. We should set RollForward to Major, not LatestForward.
