### ISSUE TITLE
IceUtil Options incorrectly paring multiple short options

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#168]
The code in `IceUtil::Options` incorrectly parse multiple short options, using `-dE` only the last `E` is interpreted as an option and `d` is ignore.

That is easy to reproduce using one of the slice compilers if you run

```
slice2cs.exe -vE test.ice
```
This print the preprocessor output

```
slice2cs.exe -Ev test.ice
```
This print the compiler version

**Comment by pepone** [comment]
Fixed the code so that multiple short options should be specified separately, for example `-dE` will be rejected and is only valid to use `-d -E` this is more consistent with how other compilers work.

**Comment by bentoi** [comment]
I'd rather not add a restriction on option parsing in a patch release.  I think the intent of the our option parsing function was to match GNU parsing https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html
