### ISSUE TITLE
Review if unaligned memory access can be used with ARM64

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1688]
We define `ICE_UNALIGNED` when unaligned memory access is supported

https://github.com/zeroc-ice/ice/blob/d25deea3be3c813ea43ed5ceeac794ba5dbc2f89/cpp/src/Ice/InputStream.cpp#L24C9-L28

We should review if ARM64 can be added here, we should also a comment to explain what this define is about, and ensure there are tests for this feature.

See also https://stackoverflow.com/questions/38535738/does-aarch64-support-unaligned-access

**Comment by bernardnormier** [comment]
I propose that we don't support unaligned access on ARM. It's more trouble than anything else.

**Comment by pepone** [comment]
`ICE_UNALIGNED` is now opt-in as #2529
