### ISSUE TITLE
Move the generated C++ files into the same directories as the non-generated files

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1699]
We currently have two different header include paths. Local source builds look in an additional folder `generated`. Binary builds copy the generated headers into the common `include` folder. Having these inconsistent locations means that "Foo.h" based includes do not work.

I think we should move the generated code along side the rest of cpp code and just simply .gitignore it. Now that local slice has been removed there aren't too many of these files to worry about.

**Comment by bernardnormier** [comment]
After further discussion, we decided not do that, and just keep the current structure as-is.
