### ISSUE TITLE
Consider switching to use _t types.

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1787]
I think we should consider switch our numeric types to use `_t` types (Is there a better name for these?). 

* https://en.cppreference.com/w/cpp/types/integer
* https://en.cppreference.com/w/c/numeric/math/float_t

| Old Type | New Type|
|----------|----------|
|`typedef unsigned char Byte` | `uint8_t` |
|`typedef short Short;` |`int16_t`|
|`typedef int Int;` | `int32_t`|
|`typedef long long int Long;` | `int64_t`|
|`typedef float Float;` | `float_t`|
|`typedef double Double;` | `double_t`|

**Comment by bernardnormier** [comment]
We should check how compatible this proposed change here with the CI platforms.

**Comment by externl** [comment]
Did a preliminary test on macOS. Updated the compiler to generate these types and changed nothing else. Going to test MSVC and GCC next.

**Comment by externl** [comment]
So, macOS and Windows work, however Ubuntu's GCC typedefs int64_t to `unsigned long`, whereas we require `unsigned long long`.

I personally still think this change is worth making. Yes, users that are upgrading will have to make some changes. I think that's fine as it will bring us more inline with what modern C++ code should look like. 

https://google.github.io/styleguide/cppguide.html#Integer_Types

**Comment by pepone** [comment]
I agree on updating this to use _t types.

> however Ubuntu's GCC typedefs int64_t to unsigned long

I assume they would use `long int` in 64bits platforms and `long long int` in 32bit platforms see https://stackoverflow.com/a/60391237/491807

**Comment by externl** [comment]
This was done in #1806

**Comment by externl** [comment]
In the end we only did with fixed with types, so we did not use `float_t` or `double_t`.
