### ISSUE TITLE
NullPointerException in IceBT

### ISSUE THREAD

**Issue by thhook** [zeroc-ice/ice#181]
Using IceBT (v3.7.0) in an Android app I get the following crash report in Google Play Console rather often:

> java.lang.NullPointerException: 
  at IceBT.AcceptorI.runAccept (AcceptorI.java:185)
  at IceBT.AcceptorI.access$000 (AcceptorI.java:16)
  at IceBT.AcceptorI$1.run (AcceptorI.java:84)

In my code I'm doing the following (simplified):
```java
// endpoints string
String endpoints = "bt -u " + getDeviceUUID();

// set Properties
Properties properties = Util.createProperties();
properties.setProperty("Ice.Plugin.IceBT", "IceBT.PluginFactory");
properties.setProperty("AppName.Endpoints", endpoints);
// ...
InitializationData initializationData = new InitializationData();
initializationData.properties = properties;

Communicator communicator = Util.initialize(initializationData);
ObjectAdapter adapter = communicator.createObjectAdapterWithEndpoints("AppName", endpoints);
```

By looking at the Ice sources this is what I found out:
In `IncomingConnectionFactory.createAcceptor()`, `_acceptor.listen()` (which is `IceBT.AcceptorI.listen()` in my case) is called before `_adapter.getThreadPool().initialize(this)`. `IceBT.AcceptorI.listen()` creates a new thread that eventually tries to access the field `_readyCallback` - which is only set in `ThreadPool.initialize()`, which might get called _after_ the Acceptor's sub-thread tries to access the then uninitialized field.

**Comment by bentoi** [comment]
Thanks, there's indeed a race condition here. We'll look into fixing this! Safest is probably to wait in `runAcceptor` for `_readyCallback` to be set (and also check for `_closed` in the wait)

**Comment by thhook** [comment]
@bentoi Thank's for fixing this.
While looking at the changes I noticed that you omitted the line 
`_pending.clear();`
 at the very end of `runAccept()` in the java-compat version. Was this on purpose - or is this a problem anyway?
