### ISSUE TITLE
Update service & plugin implementations to use non-nullable proxies

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1820]
C++ proxies can now be non-nullable (e.g. ObjectPrx, RouterPrx) or "nullable" (`std::optional<ObjectPrx>`, `std::optional<RouterPrx>`).

The implementation of the services is now using primarily / only nullable proxies because this was the most straightforward translation from the previous representation (`shared_ptr<XxxPrx>`). We want to update these implementations to use the new proxy syntax and non-null semantics where appropriate. 

This update should also include replacing calls to uncheckedCast by calls to the Prx constructor.

- [ ] IceGrid
- [ ] IceStorm
- [ ] Glacier2
- [ ] IceBridge
- [ ] IceDiscovery
- [ ] IceLocatorDiscovery
- [ ] IceBox

(nothing to do for the transport plugins)

**Comment by pepone** [comment]
Fixed in separate PRs:

- #1889
- #1910
- #1933
