### ISSUE TITLE
Remove cpp11 references in vcxproj project files

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1822]
We still have many many references to cpp11 in our project files:

```
% rg -i cpp11 -g \*proj
src/IceBox/msbuild/iceboxlib/iceboxlib.vcxproj
100:      <HeaderOutputDir>$(IceSrcRootDir)\include\generated\cpp11\$(Platform)\$(Configuration)\IceBox\</HeaderOutputDir>
136:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Debug\IceBox\ServiceManager.h">
142:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Release\IceBox\ServiceManager.h">
148:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Debug\IceBox\ServiceManager.h">
154:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Release\IceBox\ServiceManager.h">

src/IceStormLib/msbuild/icestorm/icestorm.vcxproj
87:      <HeaderOutputDir>$(IceSrcRootDir)\include\generated\cpp11\$(Platform)\$(Configuration)\IceStorm\</HeaderOutputDir>
149:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Debug\IceStorm\IceStorm.h">
155:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Debug\IceStorm\Metrics.h">
161:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Release\IceStorm\IceStorm.h">
167:    <ClInclude Include="..\..\..\..\include\generated\cpp11\Win32\Release\IceStorm\Metrics.h">
173:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Debug\IceStorm\IceStorm.h">
179:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Debug\IceStorm\Metrics.h">
185:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Release\IceStorm\IceStorm.h">
191:    <ClInclude Include="..\..\..\..\include\generated\cpp11\x64\Release\IceStorm\Metrics.h">
...

```

**Comment by pepone** [comment]
We should decide where we want to place these generated files. Our dist builds take advantage of using different locations for different configurations. Otherwise, when you use a compiler from a different configuration you always have to regenerate all Slice files. That is in part related to how we compute when these files are generated. We always regenerate header/sources if the Slice compiler changes (its timestamp is more recent than the generated files).

**Comment by bernardnormier** [comment]
I would just remove cpp11, i.e. put them in
```
 <ClInclude Include="..\..\..\..\include\generated\Win32\Debug\IceStorm\IceStorm.h">
```
and friends.

A related issue is #1699. I think the solution for Windows builds is to include the individual generated directories (-Igenerated/.../Debug/Ice) when building and NOT the enclosing directory (.../Debug).

**Comment by bernardnormier** [comment]
> A related issue is #1699. I think the solution for Windows builds is to include the individual generated directories (-Igenerated/.../Debug/Ice) when building and NOT the enclosing directory (.../Debug).

Actually we should not do that. See #375.
