### ISSUE TITLE
Map Slice byte to std::byte and not std::uint8_t?

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1825]
Since we're changing the C++ mapping for Slice byte: should it be to std::byte, and not uint8_t?

**Comment by externl** [comment]
The usage of `std::byte` vs `uint8_t` is really about intent. In the docs we actually distinguish between byte and the other integer types. 

https://doc.zeroc.com/ice/3.7/the-slice-language/basic-types#BasicTypes-Bytes

After some discussion here in the office, the proposal is as follows:

- map a  Slice`byte` to `std::uint8_t`
- map a Slice `sequence<byte>` to `std::vector<std::byte>>`
