### ISSUE TITLE
cpp:view-type for decoded parameters

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1849]
The cpp:view-type can be applied to string, sequence and dictionary parameters.

Per the [Ice 3.7 manual](https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/customizing-the-c++11-mapping/the-cpp-type-and-cpp-view-type-metadata-directives-with-c++11#id-.Thecpp:typeandcpp:viewtypeMetadataDirectiveswithC++11v3.7-Avoidingcopieswithcpp:view-type):

> With cpp:view-type, the compiler changes the mapping only when it's safe to use a view-type, namely:
> Input parameters, on the client-side and **on the server-side**
> Out and return parameters provided **by the Ice run-time** to [AMI](https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/client-side-slice-to-c++11-mapping/asynchronous-method-invocation-ami-in-c++11) callbacks
> Out and return parameters provided to [marshaled results](https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/server-side-slice-to-c++11-mapping/parameter-passing-in-c++11) or [AMD](https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/server-side-slice-to-c++11-mapping/asynchronous-method-dispatch-amd-in-c++11) callbacks

I find these rules impractical. It's ok to change the mapping for parameters that the application provides to Ice, but it's not ok to change the mapping for parameters decoded by Ice and provided to the application.

In the "decoded" case, the view-type's underlying memory is necessarily the Ice unmarshaling buffer, and this memory may not be what the type needs (e.g. a string that needs to be converted) or this memory may not be properly aligned.  It's also inconsistent with the C++ mapping rules where the decoded parameters are passed by value so that the application can adopt their memory.

Proposal 1: restrict view-type to parameters that are marshaled (aka written/encoded), and don't use cpp:view-type for unmarshaled (aka read/decoded) parameters.

On the other hand, we wouldn't change the semantics for cpp:array (on sequences): cpp:array keeps applying to both marshaling and unmarshaling. InputStream includes special logic to allocate an array or vector "on demand" when zero-copy doesn't work. For example:
https://github.com/zeroc-ice/ice/blob/bf991f4f7604869517f9211f18a6048239521551/cpp/src/Ice/InputStream.cpp#L565
https://github.com/zeroc-ice/ice/blob/bf991f4f7604869517f9211f18a6048239521551/cpp/include/Ice/InputStream.h#L659

Proposal 2: drop cpp:view-type for string parameters
Since string parameters are already mapped to [w]string_view (see #1847), there is no real need for customization.

**Comment by externl** [comment]
Ii lean towards option 2.
