### ISSUE TITLE
Replace test script uwp and dotnet flags with targets option

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#186]
The test driver script should be fixed to support a new option: `--targets=uwp|android|dotnetcore|xamarin-ios|xamarin-uwp|xamarin-android`
This will replace `--dotnetcore` and `--uwp` options and we'll no longer have separate `allTests.py` scripts for running Java Android or C# Xamarin tests

**Comment by bentoi** [comment]
I've refactored the code but didn't add the `--targets` option and instead kept the `--dotnetcore`, `--uwp` options:

- use `--dotnetcore` to run .NET Core tests on Windows (it's implied for Linux/macOS)
- use `--android` to run Java, Java-Compat or CSharp Xamarin tests
- use `--uwp` to run C++, CSharp Xamarin tests
- use `--platform=iphonesimulator` or --platform=`iphoneos` to run the C++, Objective-C or CSharp Xamarin tests

There's no need for a Xamarin option.
