### ISSUE TITLE
Update or remove appbundler

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#188]
We currently using appbundler from our deprecated nexus repo: https://github.com/zeroc-ice/ice/blob/3ba590d12addb8c662e822c8f820059370f8db45/java/build.gradle#L46

We should either update this dependency to use a different repository or remove this dependency if it's not available anywhere.

**Comment by joshmoore** [comment]
We recently deprecated ours in favor of `com.panayotis`: https://github.com/ome/appbundler/issues/5#issuecomment-393363757

**Comment by bentoi** [comment]
Thanks Josh. Turns out that we already use this app bundler: https://github.com/zeroc-ice/ice/blob/59743ed8b477624fe354f543f75d55d07b9fc5ba/java/src/IceGridGUI/build.gradle#L56) 

We just forgot to remove the reference to the 3rd party repo.
