### ISSUE TITLE
Nested module definition such as com::zeroc::Demo

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#189]
Many Slice files on GitHub use deeply nested modules, probably because the authors were not familiar with the [java:package](https://doc.zeroc.com/ice/3.7/language-mappings/java-mapping/client-side-slice-to-java-mapping/customizing-the-java-mapping#id-.CustomizingtheJavaMappingv3.7-packages) metadata directive.

We could improve this situation by simplifying the syntax to open a deeply nested submodule. This way, authors and maintainers of such Slice files could easily make their code more readable without changing type-ids or introducing new configuration properties in their Java apps.

Proposed syntax:
```
module com::zeroc::Demo { ... }
```

This would be equivalent to
```
module com { module zeroc { module Demo
{
...
}
}}
```

**Comment by bentoi** [comment]
I'm fine with this but users should be aware that deeply nested modules increase the on-the-wire cost when transmitting Slice classes... so I'd rather not use this in our demos.

**Comment by bernardnormier** [comment]
Changed title to match the corresponding C++17 feature, nested namespace definition.

**Comment by InsertCreativityHere** [comment]
This was added in #841.
