### ISSUE TITLE
Should we Add More Windows Testing to CI?

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#1967]
On one hand, CI already takes a while, and we don't want to abuse it too heavily for our testing.
But on the other hand, #1966 shows that the windows builds have been broken, probably for a while.

These broken builds weren't caught because we only test C# and Java on Ubuntu, which uses an entirely different build system.

**Comment by bernardnormier** [comment]
We should also add 32-bit Windows testing for C++.
