### ISSUE TITLE
Thousands separator and stringified proxies

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#197]
The C++ proxy stringification code generates incorrect strings when a thousands separator is set. Likewise, the un-stringification code requires this thousands separator.

How to reproduce:
* add `std::locale::global(std::locale("en_US.UTF-8"));` as the first line of your main function
* stringify/unstringify some direct proxies

This bug should not be fixed in a patch release in case some applications rely on this round-trip working fine, with stringified proxies stored in a database.

**Comment by bernardnormier** [comment]
We should double-check if this issue exists in other languages (C#, Java, JS) as well.

**Comment by pepone** [comment]
Java, C# and JavaScript are doing locale independent conversion with the default toString.
