### ISSUE TITLE
Unable to create temporary channel from ICE interface

### ISSUE THREAD

**Issue by daveoon** [zeroc-ice/ice#198]
Can anyone advise how to create a temporary channel from ICE interface? I m using the methods describe below but it doesn't create a temporary channel but a permanent one. Is it only working on the client side mumble.protocol only?
```
const channel_id = await server.addChannel('temp', 0)
const channel = await server.getChannelState(channel_id)
channel.name = 'Temp'
channel.temporary = true
await server.setChannelState(channel)
```

**Comment by bentoi** [comment]
You will probably have better chances of getting a response if you submit your question on the Mumble forums as this doesn't appear to be related to Ice.

**Comment by daveoon** [comment]
oh yes, im so sorry. can i delete this issue?
