### ISSUE TITLE
An object adapter with a router should not have endpoints

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1986]
Currently it is possible to create an adapter that has endpoints and a router, but in practice should be one or the other. For 3.8 we want to make this two options incompatible.

- [x] C++
- [x] C#
- [x] Java
- [x] JavaScript
- ~[] Python~ (from C++)
- ~[ ] Swift~ (from C++)

https://github.com/zeroc-ice/ice/pull/1983#discussion_r1538126164

**Comment by bernardnormier** [comment]
The title and description of this task/proposal are not the same.

Making Endpoints and Router incompatible is easy.

More interesting is the second part, that can be more clearly expressed as:
 - the parameter of Connection::setAdapter must be an endpoint-less object adapter

**Comment by bernardnormier** [comment]
I fixed the description and limited the scope of this issue to router / endpoints. In the existing code, an OA with a router would simply ignore the configured endpoints, if any.

> the parameter of Connection::setAdapter must be an endpoint-less object adapter

This change could break existing code without any real benefit, so let's not do it.

**Comment by bernardnormier** [comment]
JS: see #2746.
