### ISSUE TITLE
Ice.ServerIdleTime in tests

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2025]
A number of tests configure Ice.ServerIdleTime, however, it's not clear why they do it and no test appears to actually verify that Ice.ServerIdleTime works.

Keep in the mind the default value for Ice.ServerIdleTime is 0 - meaning, the communicator is not shutdown automatically when inactive.

**Comment by externl** [comment]
When implementing this I also found several issues which affected primarily Apple platforms.
