### ISSUE TITLE
Update MATLAB action to 2024a

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2037]
https://github.com/zeroc-ice/ice/blob/59392d7b35720e42a07951beeada22e3a60cfa29/.github/actions/setup-dependencies/action.yml#L95-L109

We hardcode the 2023b version, but the setup is already installing 2024a

```
/usr/bin/chmod +x /home/runner/work/_temp/mpm
  /home/runner/work/_temp/mpm install --release=r2024a --destination=/opt/hostedtoolcache/MATLAB/2024.1.999/x64 --products MATLAB
  Installing with the following parameters:
  --destination=/opt/hostedtoolcache/MATLAB/2024.1.999/x64
  --doc=false
  --release=R2024a
  --products=MATLAB
```

MATLAB fails to build because we end up using the wrong PATHs

```
/bin/sh: 1: /opt/hostedtoolcache/MATLAB/2023.2.999/x64/bin/matlab: not found
```

**Comment by externl** [comment]
It would be nice to figure out what the latest installed version is from some env variable or something.

**Comment by externl** [comment]
I've tried updating to 2024a in https://github.com/zeroc-ice/ice/pull/2073 but the build hangs on Linux. @pepone is going to try locally.
