### ISSUE TITLE
Not available on Xcode10

### ISSUE THREAD

**Issue by ZhangCrow** [zeroc-ice/ice#204]
It works and works well on Xcode9. But not available on Xcode10.

This is the build log on Xcode10

> ld: library not found for -lIceObjC
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bernardnormier** [comment]
We are updating Ice 3.7 to build with Xcode 10. 

An updated Ice 3.7.1 will be available from homebrew soon.

See also https://github.com/zeroc-ice/ice/tree/v3.7.1-xcode10 and https://github.com/zeroc-ice/ice/commit/e0a0f0c5b6a5e5680f6687b5c7a447c9f7f370ac

**Comment by bernardnormier** [comment]
See also https://github.com/zeroc-ice/ice-demos/issues/25

**Comment by bernardnormier** [comment]
The latest ice on homebrew and the latest ice-demos are compatible with Xcode 10.
