### ISSUE TITLE
deprecated metadata on operation broken in C++

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2085]
There are at least two issues:

- the generated code does not compile when an operation is marked deprecated

```cpp
src/IceGridLib/generated/Admin.cpp:5498:11: error: 'keepAlive' is deprecated: is deprecated [-Werror,-Wdeprecated-declarations]
    this->keepAlive(request.current());
```

From:
```slice
["deprecated"] idempotent void keepAlive();
```

- the C++ deprecated attribute message with no message should not be "is deprecated":

```cpp
 [[deprecated("is deprecated")]] virtual void keepAlive(const ::Ice::Current& current) = 0;
```

**Comment by externl** [comment]
Once this is fixed we also need to do: https://github.com/zeroc-ice/ice/pull/2087#pullrequestreview-2031264169

**Comment by InsertCreativityHere** [comment]
This was fixed in #2288.

**Comment by InsertCreativityHere** [comment]
But I'm leaving this open, because it's still broken in other languages.
Once it's 'un-broken' it sounds like we want to deprecate:
`Glacier2::Router::refreshSession` and `IceGrid::Admin::keepAlive`

I suspect we'll also want to deprecate `IceGrid::Session::keepAlive`.

Anything else?

**Comment by bernardnormier** [comment]
> But I'm leaving this open, because it's still broken in other languages.

Please open a new issue. A number of Slice operations are marked deprecated:
```
```
IceGrid/Admin.ice
757:        ["deprecated"]
758-        idempotent void keepAlive();

IceGrid/Registry.ice
116:        ["cpp:const", "deprecated"] idempotent int getSessionTimeout();
117-    }

IceGrid/Session.ice
30:        ["deprecated"]
31-        idempotent void keepAlive();
```
