### ISSUE TITLE
Add deprecated as an alias for deprecate

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2093]
Currently the metadata for a deprecated definition in Slice is "deprecate" and not the more common "deprecated".

I propose to keep "deprecate" but add "deprecated" as an alias. This way, you can use either and the result in the same.

**Comment by InsertCreativityHere** [comment]
I'd be fine with adding this, although I'm not sure how much value it'll provide.

**Comment by InsertCreativityHere** [comment]
So, we aren't even consistent ourselves.
The metadata you use to mark something deprecated is `deprecate`
But the string you pass in to ignore deprecation warnings is `deprecated`

Should we also let `suppress-warning` support `deprecate`?

**Comment by bernardnormier** [comment]
No, we should standardize on deprecated, not add more support for 'deprecate'.

**Comment by InsertCreativityHere** [comment]
This was implemented in #2166.
