### ISSUE TITLE
Mismatched default value for IceGrid.Registry.AdminSessionFilter

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2134]
We document that the default value is `1`. https://doc.zeroc.com/ice/3.7/property-reference/icegrid#id-.IceGrid.*v3.7-IceGrid.Registry.AdminSessionFilters

However, in code we have `0`.
https://github.com/zeroc-ice/ice/blob/aae5161459b914c72afdeb4f5f102a2ae9c752b8/cpp/src/IceGrid/AdminSessionI.cpp#L475

Which is correct?

**Comment by pepone** [comment]
Seems we forget to upgrade the docs after this fix https://github.com/zeroc-ice/ice/commit/9a34c65221b56dc4b7941c18a0c8a0f9b634d7b6

**Comment by externl** [comment]
Thanks, I updated the docs!
