### ISSUE TITLE
Document or remove undocumented IceGrid.Registry.RequireXXXCertCN

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2135]
I can't find any documentation for these properties and I'm not sure how useful they are. These days CN is not that relevant for hostname verification.

https://github.com/zeroc-ice/ice/blob/aae5161459b914c72afdeb4f5f102a2ae9c752b8/config/PropertyNames.xml#L530-L531

I'm in favor of removing these.

**Comment by bernardnormier** [comment]
If we remove them, we should also remove the associated code in IceGrid.

**Comment by pepone** [comment]
@externl  I added a fix for this in https://github.com/zeroc-ice/ice/pull/2144 because this allows keeping DistinguisedName internal.

**Comment by pepone** [comment]
Fixed in https://github.com/zeroc-ice/ice/pull/2144
