### ISSUE TITLE
Remove `IceSSL.SchannelStrongCrypto` property 

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2143]
https://github.com/zeroc-ice/ice/blob/f1ccd030150b6030b58e996bc5ea87ceec8289dd/cpp/src/Ice/SSL/SchannelEngine.cpp#L428

Currently this property is set to `0` by default. I think we should just remove the property, use strong crypto by default and let the user change this programmatically if they need to.

**Comment by pepone** [comment]
I think we should:

- Configure Schannel to use strong crypto by default
- Remove the `IceSSL.SchannelStrongCrypto` property

I the rare case that you need to set this, just use the native API.
