### ISSUE TITLE
The default for ConsoleListener is undocumented. It's 1 in the code (C# only).

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2148]
The default for ConsoleListener is undocumented. It's 1 in the code (C# only).

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2146#discussion_r1595913121_

**Comment by bernardnormier** [comment]
It's now documented in https://github.com/zeroc-ice/ice/blob/fca2f2dd2b2bb697c8729b5025b15066a7d47bda/config/PropertyNames.xml#L87
