### ISSUE TITLE
How to bubble up Java Runtime exceptions

### ISSUE THREAD

**Issue by skhandelwalv** [zeroc-ice/ice#2224]
I saw this on the documentation https://doc.zeroc.com/ice/latest/language-mappings/java-mapping/server-side-slice-to-java-mapping/raising-exceptions-in-java but when I encounter an outOfMemory error I want the Service to crash and just restart instead of keeping the out of memory in that thread. Is there a way to do that?

**Comment by pepone** [comment]
Closing this, you already create a discussion for the same issue in https://github.com/orgs/zeroc-ice/discussions/2225
