### ISSUE TITLE
Fix CA2008 diagnostics in CodeAnalysis.Base.globalconfig

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2263]
CA2008 is listed twice with different values.  Which is the one we want?

https://github.com/zeroc-ice/ice/blob/4675c80836d70753d9e00db6583492c6f8969130/csharp/msbuild/CodeAnalysis.Base.globalconfig#L327-L328

**Comment by pepone** [comment]
Fixed in bb81a9e4339334619d1a88e14b189232927e68a0
