### ISSUE TITLE
Review handling of OutOfMemoryError in Java

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2276]
The Ice for Java runtime as of 3.7 traps OutOfMemoryError or AssertionError thrown by servants, and logs it. See [Raising Exceptions in Java]

This behavior is not configurable; some applications would prefer to deal with this using a different strategy, for example, letting the application crash.

For 3.8 we can move this behavior to an [UncaughtExceptionHandler] for the server thread pool threads, and allow the users to provide their own UncaughtExceptionHandler when creating an adapter or with InitiliazationData.

See also [Discussion 2225]

[Raising Exceptions in Java]: https://doc.zeroc.com/ice/latest/language-mappings/java-mapping/server-side-slice-to-java-mapping/raising-exceptions-in-java
[Discussion 2225]: https://github.com/orgs/zeroc-ice/discussions/2225
[UncaughtExceptionHandler ]: https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F/java/lang/Thread.UncaughtExceptionHandler.html

**Comment by bernardnormier** [comment]
This special behavior is only about synchronous exceptions that bubble up in the dispatch.

With a "CompleteStage" dispatch, where the returned completion stage is completed by an error, there is not much we can do. Just kill the current thread when we get an Error? Abort the JVM? This doesn't seem realistic.

See also #2291.

**Comment by bernardnormier** [comment]
I propose that we supply an ErrorHandlerMiddleware that the user can install. This middleware will just callback the user-supplied Consumer. Something like:
```java
public final class ErrorHandlerMiddleware implements Object {
    public ErrorHandlerMiddleware(Object next, Consumer<Error>) { ... }

}

public final class ObjectAdapter {
    public ObjectAdapter useErrorHandler(Consumer<Error> handler) { ... }
}
```

The ErrorHandlerMiddleware doesn't "handle" the error in any way. It just gives it to handler, which can print a message to the Console,  send a Slack message, abort the application (...).

Then, regardless of the installation of this error handler middleware, all errors are treated like miscellaneous exceptions:  logged as error (by the internal Logger middleware) and marshaled as UnknownException. They never kill the dispatch thread.
