### ISSUE TITLE
Ice for Java: merge the IceInternal package into the Ice package

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2306]
The IceInternal package (namespace in C++) corresponds to undocumented "Ice internal" APIs.

Unfortunately in Java, putting these APIs in a separate package means we have to use public visibility for many Ice and IceInternal APIs - we can't use the package private visibility. We even to export this IceInternal package are some of these "Ice internal" symbols are used by the generated code and plug-ins.

I propose we refactor this code by merging the IceInternal package into the Ice package. And then we can adjust the visibility of many internal classes and methods to be package private. The remaining public "Ice internal" classes in package Ice can be documented as "for internal Ice use".

**Comment by InsertCreativityHere** [comment]
This was fixed in #2770.
