### ISSUE TITLE
WSS on NodeJs

### ISSUE THREAD

**Issue by tete17** [zeroc-ice/ice#231]
Hey guys i wanted to ask a question before I got my hands dirty with the code.

I trying the ice mapping to javascript (in reality we are using typescript). We are building a small server in nodejs that uses ice as a client and it is a shame we do not have any form of encrypted communication.

I want to implement the web sockets interface for nodejs, but i am not sure if it can be done without the help of a 3 party library.

Would you guys accept a pull-request adding such dependency? Or do you guys recommend to do it in a different way?.

Thanks in advance

**Comment by pepone** [comment]
Hi @tete17 ,

Using a third-party library is probably the only reasonable way to add ws/wss support to Ice for JavaScript with nodejs. 

Which library would you use? We are very careful with the licensing terms of all our dependencies.

We will be willing to accept such a pull-request providing that you can sign our contributors agreement, please review https://github.com/zeroc-ice/ice/blob/3.7/CONTRIBUTING.md

Cheers,
José

**Comment by tete17** [comment]
Hola Jose

My idea was to use the library 'ws' (https://www.npmjs.com/package/ws) with an MIT license.
But there is also another option with a APACHE-2.0 license.

Let me know if that works for you.

Un Saludo
Miguel

**Comment by tete17** [comment]
Im algo having issues running the test for the js mapping:
```
miguel@miguel-XPS-15-9560:~/CLionProjects/ice/js$ python allTests.py 
*** [1/28] Running js/Slice/escape tests ***
[ running client test - 10/05/18 23:01:40 ]
testing enums... ok
testing structs... ok
testing proxies... ok
testing classes... ok
*** [2/28] Running js/Slice/macros tests ***
[ running client test - 10/05/18 23:01:41 ]
testing Slice predefined macros... ok
*** [3/28] Running js/Ice/acm tests ***
[ running client/server test - 10/05/18 23:01:41 ]
[Errno 2] No such file or directory

test in Ice/acm failed:
[Errno 2] No such file or directory

Ran 3 tests in 1.01 seconds
2 succeeded and 1 failed:
- Ice/acm
  [ running client/server test - 10/05/18 23:01:41 ]
  
  test in Ice/acm failed:
  [Errno 2] No such file or directory
```

**Comment by pepone** [comment]
Hi Miguel,

> My idea was to use the library 'ws' (https://www.npmjs.com/package/ws) with an MIT license.

That seems good for us, let us know if you hit any issues with the implementation.

```
*** [3/28] Running js/Ice/acm tests ***
[ running client/server test - 10/05/18 23:01:41 ]
[Errno 2] No such file or directory`
```
Seems like you have not build the C++ tests, JavaScript tests suite use some C++ servers too, try to run with `--debug` to see the actual command that failed.

**Comment by pepone** [comment]
Hi Miguel,

did you make any progress with ws NodeJS implementation, let us know if you need any helpe.

Best regards,
José
