### ISSUE TITLE
Use optional type for Reference compress

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2368]
It would be cleaner to use a `bool?` here.

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2366#discussion_r1657837589_

**Comment by bernardnormier** [comment]
We should do the same in C++ with a `std::optional<bool>`. See:

https://github.com/zeroc-ice/ice/blob/69a59072e496c2e13d1cfe79baf779905f731e6e/cpp/src/Ice/Reference.h#L160
and
https://github.com/zeroc-ice/ice/blob/69a59072e496c2e13d1cfe79baf779905f731e6e/cpp/src/Ice/Reference.h#L61
