### ISSUE TITLE
`Ice/proxy` MATLAB failure

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#2391]
This test failure was being hidden by #2385.

*** [14/17] Running matlab/Ice/proxy tests ***
...
testing opaque endpoints... Error using Ice.ObjectPrx/ice_ping (line 185)
::Ice::ConnectTimeoutException

Error in AllTests.allTests (line 818)
                p1.ice_encodingVersion(Ice.EncodingVersion(1, 0)).ice_ping();

Error in Client (line 15)
    myClass = AllTests.allTests(helper);

Error in runTest (line 28)
        Client(varargin);

**Comment by bernardnormier** [comment]
This bug was fixed by #2395.
