### ISSUE TITLE
Ignore Ice.Plugin.IceSSL for compatibility with 3.7

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2397]
What will happen if the user keep this property in his config file? Do we have any validation of plug-in names with an Ice prefix?

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2388#pullrequestreview-2154678837_

We should review, but I think we should probably ignore the property.

**Comment by externl** [comment]
There are already lots of changes. We're removing deprecated properties, etc. I don't think we should specially ignore a single property just for version sharing.

**Comment by bernardnormier** [comment]
My understanding is IceSSL remains a plugin in Ice 3.8, just like TCP is a plugin, UDP is a plugin etc. 

https://github.com/zeroc-ice/ice/blob/d6e44874ca8d6892f96a6b7b07fcba08b7bb47e2/cpp/include/Ice/RegisterPlugins.h#L48

So presumably `Ice.Plugin.IceSSL=1` should be valid, just like `Ice.Plugin.IceUDP=1` is valid.

**Comment by bernardnormier** [comment]
I verified it works fine in C++.
