### ISSUE TITLE
Add comment describing who can throw these exceptions

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2419]
It would be nice to add a comment describing who can throw these exceptions.

The NotExist exceptions and Unknown exceptions: 
 - application code
 - Ice for Python code
 - IcePy C++ extension code

All the other exceptions: only the IcePy C++ extension code?

Maybe users who implement a ValueFactoryManager are expected to throw AlreadyRegisteredException as well from their Python code? 
(seems undesirable - it's better if we can avoid having users throw local exceptions)

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2417#discussion_r1667030816_

**Comment by bernardnormier** [comment]
I believe the following local exceptions can be thrown by application code:

## client-only mapping (MATLAB, Ruby, PHP)

- `AlreadyRegisteredException` from a custom ValueFactoryManager

## client-server mapping (C++, C#, etc.)

- `AlreadyRegisteredException` from a custom ValueFactoryManager
- the 6 special marshalable local exceptions (*NotExistException and Unknown*Exception)
