### ISSUE TITLE
Does Ice Grid provide customization of forward rule from application layer?

### ISSUE THREAD

**Issue by Kiddinglife** [zeroc-ice/ice#252]
Hi mate,

I expect icegrid having rpc interfaces or plugin system so that  an application server can communicate with icegrid to dynamically start/stop forwards of particular packets to itself or other application servers with the user-defined forward rules. eg. the packet id or application logic.

thanks.

**Comment by bentoi** [comment]
Hi,

Yes, IceGrid provides an administration interface to allow remote clients to manage servers hosted by IceGrid.

See https://doc.zeroc.com/ice/3.7/ice-services/icegrid/icegrid-administrative-sessions for information on how to create an administrative session with IceGrid and https://doc.zeroc.com/api/ice/3.7/slice/interfaceIceGrid_1_1Admin.html for information on the administrative interface.

Cheers,
Benoit.
