### ISSUE TITLE
Simplify user exception mapping

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2527]
User exceptions are more like result failures (see https://docs.icerpc.dev/slice2/language-guide/result-types) than actual exceptions.

As a result, a mapped user-exception does not need:
 - the ability to set a custom error message during construction
 - the ability to set an inner exception

Furthermore, a client-side application does not need to ever create a user exception. So we don't need to provide/document a constructor/initializer for mapped user exceptions in client-only mappings (MATLAB, PHP, Ruby).

Fixed in:
- [x] C++
- [x] C#
- [x] Java
- [x] JavaScript
- [x] MATLAB
- [x] PHP
- [x] Python
- [x] Ruby
- [x] Swift

**Comment by pepone** [comment]
JavaScript fixed in #2574

**Comment by pepone** [comment]
Python PR in #2606

**Comment by InsertCreativityHere** [comment]
The Java side of this was implemented in #2639.
