### ISSUE TITLE
Remove type check when marshaling proxies in Python, Ruby, PHP

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2546]
When we marshal a proxy in a scripting languages (Python, PHP or Ruby) (+ maybe JavaScript), we should not verify the type. The only thing the marshaling engine needs is a proxy.

Removing this type-check will allow us to remove extraneous uncheckedCast in server-side Python code such as:
https://github.com/zeroc-ice/ice/blob/dea58dd1012ddbce133a6cf804106f5a5196628b/python/test/Ice/admin/TestI.py#L95

**Comment by pepone** [comment]
The PHP code seems to do this already:

https://github.com/zeroc-ice/ice/blob/3007323d113e09d64ffa33a9839437b0d36ccbd1/php/src/Types.cpp#L2557-L2559

We check that the value is an instance of `proxyClassEntry`.

**Comment by pepone** [comment]
The JavaScript code doesn't validate the proxy types, it just uses "ObjectPrx.write" for marshaling all proxy types.
