### ISSUE TITLE
Remove InputStream::setSliceValues

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2547]
This function/method is available in C++, Java and C#, and allows you to turn-off slicing when _unmarshaling_.

I don't find this feature meaningful. It's also not tested.

```
rg setSliceValues
cpp/include/Ice/InputStream.h
276:        void setSliceValues(bool b);

cpp/src/Ice/InputStream.cpp
284:Ice::InputStream::setSliceValues(bool on)

csharp/src/Ice/InputStream.cs
318:    public void setSliceValues(bool b)

java/src/Ice/src/main/java/com/zeroc/Ice/InputStream.java
340:  public void setSliceValues(boolean b) {

```

**Comment by InsertCreativityHere** [comment]
It was added in 2004, no tests, no call sites, even back then: https://github.com/zeroc-ice/ice/commit/314e2bde2bb2588d6f1a32271beb16ce782b8867
