### ISSUE TITLE
Never include stack trace in Unknown exception messages

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2571]
The Unknown exception message (UnknownLocalException and UnknownException), which often reports an unhandled exception, should not include the unhandled exception stack trace.

Fixed in:
- [x] C++
- [x] C#
- [x] Java
- [x] JavaScript
- [x] Python
- [x] Swift

**Comment by bernardnormier** [comment]
C#: fixed by #2563.

**Comment by pepone** [comment]
JavaScript fixed in: #2582
