### ISSUE TITLE
Simplify OutputStream constructor

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2595]
We have too many OutputStream constructors. And OutputStream should not hold onto instance.

To fix in:
 - [x] C++
 - [x] C#
 - [x] Java
 - [x] JavaScript
 - [x] MATLAB
 - [x] Swift 

C#: see #2594

**Comment by bernardnormier** [comment]
C++: #2609

**Comment by bernardnormier** [comment]
JavaScript, MATLAB, Swift: #2618

**Comment by pepone** [comment]
Java fixed in b9a1036e56f2c2213d721d951225ae3d75e6387e
