### ISSUE TITLE
Ice 3.6 for Gentoo and tests

### ISSUE THREAD

**Issue by Dessa** [zeroc-ice/ice#27]
(apologies for the long post)

hello

i am the current gentoo maintainer of the Ice Package.
as part of the stabilization process we do run the testsuite, keep in mind that we are still at 3.6.3, i plan to update that but i still need the current revision marked stable.

the first and foremost question, which will make the rest of the report obsolete, i suppose, is are we actually *supposed* to run tests? some upstreams dislike that.

onto the test failures then:

these i have encountered myself and filtered out as a result:

a little word about the sandbox Ice is build in.
its to avoid the clobber the system during the build be it filesystem or network wise, it normally run as root (this *can* be changed but it is not usually done)

no internet access in the sandboxed build environment / limited udp support in the sandbox (IIRC) so: no upstream issue in failing:

- Ice/udp
- IceSSL

works with OPTIMIZE=yes, fails with OPTIMIZE=no

- IceUtil/stacktrace

these were tested with latest 3.6 git branch

now are these which appeared in the gentoo bugtracker, these i have not encountered myself so no idea about them.

- IceStorm/Single https://bugs.gentoo.org/show_bug.cgi?id=636834
- IceGrid/Admin https://bugs.gentoo.org/show_bug.cgi?id=649850
- IceBox/Configuration https://bugs.gentoo.org/show_bug.cgi?id=654070

IceGrid/Admin has kind of failed on me once but never again, i see that there is 0a37d62cd9ce62de708f685cfa0fc30058ab83ac so thats probably ok to be filtered?
IceBox/Configuration feels odd. we use a patch from pld-linux which removes ${binsuffix} so why is this even happening? see https://github.com/gentoo/gentoo/blob/master/dev-libs/Ice/files/Ice-3.6.3-no-arch-opts.patch for the patch

this was with 3.6.3

for 3.7 i'm not sure how to handle the tests yet and i'm currently not near my dev machine to check how i did that, but i think i had to call allTests.py for every phase which is kind of sad when it worked just fine before with make test, but yes i *do* know you revamped the build system with 3.7

**Comment by bernardnormier** [comment]
Hello Dessa,

Thank you for taking care of Ice for Gentoo. You could start by upgrading to the latest Ice 3.6 patch version, Ice 3.6.4: https://github.com/zeroc-ice/ice/releases/tag/v3.6.4.

This simple upgrade could actually resolve some of your test failures.

If you need to make any fix, please contribute them. We'd like to see you build Ice without any patch!

Building and running the test suite can take a long time. The test suite has options to make the testing more comprehensive (such as --all, --all-cross) and also to speed up the test run (--workers=count). I would not force users to build and run the test suite every time they install Ice from source. Maybe you can make this testing optional?

Our expectation is to see all tests run successfully, so any failure should be investigated. If after investigation a test is expected to fail in your build environment, you should skip it with --rfilter. See for example:
https://github.com/zeroc-ice/ice-debian-packaging/blob/master/debian/rules#L127

For IceBox/Configuration, your build system patch removes the icebox 32 suffix from the build but not from the test scripts. You need to do both:
https://github.com/zeroc-ice/ice/blob/3.6/scripts/TestUtil.py#L820

Best regards,
Bernard

**Comment by Dessa** [comment]
it is optional. users will need to explicitly enable it and this is only done by the testers who then give the package stable keywords.
thanks for the IceBox pointer, i didn't think of looking at this file.

**Comment by bernardnormier** [comment]
As of 3.7.1, we're supporting C# again on Linux (with .NET Core 2.0).
