### ISSUE TITLE
Implement Connection.MaxDispatches in JS

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2725]
We need to implement Connection.MaxDispatches in JS. It's already implemented in all other languages.

**Comment by pepone** [comment]
The max dispatches implementation works by stop reading from the connection once the limit is reached. This in turn applies back-pressure to peer.

For JavaScript the WebSocket API is event based, and has no built in support for back pressure. There is no way to pause read, and continue later. There is a `message` event if you register a listener it gets notified, if you don't the message is discarded.

We can implement max dispatches by queueing the messages, while dispatch count reaches max dispatches and continue processing them once it drops below it, maybe using a stream.

But doing this it will not add back pressure to the peer and I see little value in implementing max dispatches in JavaScript given web-socket limitations.

**Comment by bernardnormier** [comment]
MaxDispatches has two main purposes:
 - putting back pressure on the peer (by not reading off the connection)
 - limiting the amount of memory consumed by pending incoming requests

If we just queue pending requests in a stream, we're not limiting the amount of memory they consume. 

So I agree, it sounds like implementing MaxDispatches in JS wouldn't be useful.
