### ISSUE TITLE
[js][feature] 3.7.10 why not js icestorm

### ISSUE THREAD

**Issue by stan1334** [zeroc-ice/ice#2733]
### Version

3.7.10

### Describe the bug

feature
i want use javascript es6 be Client, sub icestorm,recv datas refresh uitableview

https://github.com/zeroc-ice/ice-demos/tree/main
i cannot find js storm demo

### Expected behavior

need javascript sub/pub storm

### Additional context

banckend c++/java pub storm produce datas
ui javascript sub storm recv datas

**Comment by pepone** [comment]
Hi,

IceStorm definitions are included in the ice 3.7.10 npm package.

Creating a publisher is similar to what you will do with other language mappings.

For the subscriber you would have to use a router object adapter with Glacier2, as JavaScript mapping doesn't support incoming connections.

**Comment by stan1334** [comment]
> 你好
> 
> IceStorm 定义包含在 ice 3.7.10 npm 包中。
> 
> 创建发布者类似于使用其他语言映射执行的操作。
> 
> 对于订阅者，您必须将路由器对象适配器与 Glacier2 一起使用，因为 JavaScript 映射不支持传入连接。

thanks reply。
