### ISSUE TITLE
Switch to fixed property names for Ice plugins and IceStorm

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2798]
Many (but not all) Ice plugins currently use "variable" property names, where the prefix is the name of the plug-in, as specified by Ice.Plugin._name_ in configuration.

For example:

(variable)
https://github.com/zeroc-ice/ice/blob/7499111a7357500768d3a87b8a078a96b2b23e26/cpp/src/IceLocatorDiscovery/PluginI.cpp#L202

(fixed)
https://github.com/zeroc-ice/ice/blob/7499111a7357500768d3a87b8a078a96b2b23e26/cpp/src/IceBT/StreamSocket.cpp#L258

The logic of the variable property names is you could load multiple plugin instances (each with a different name) in the same communicator, and then each instance can get its own configuration. However, in practice, there is no reasonable use-case for these multiple instances of the same plugin - at least not for any of the plugins we provide.

We have the same logic for IceStorm (an IceBox service, not a plugin): all the IceStorm properties are prefixed by the service name, not "IceStorm":
https://doc.zeroc.com/ice/3.7/property-reference/icestorm-properties

This allows you to load multiple IceStorm instances in the same IceBox while sharing the same communicator... a non-existent use-case. With a fixed name, you could still load multiple IceStorm instances in the same IceBox server, just not share the same communicator (not sharing the communicator is already the default).

I propose to simplify by switching to fixed property names for all Ice plugins and IceStorm. It's easier to understand, easier to document, easier to validate, easier to implement, with no loss of functionality.

**Comment by externl** [comment]
One potential issue for IceStorm is that the IceGrid templates rely on this behavior and generates properties for the service name. 

https://github.com/zeroc-ice/ice/blob/main/cpp/config/templates.xml/#L66-L82

IceStorm also uses the service name for its database location (defaulting to "IceStorm"). 

https://github.com/zeroc-ice/ice/blob/main/cpp/src/IceStorm/Instance.cpp/#L306-L310

**Comment by bernardnormier** [comment]
Why is this an issue? 

Switching to a fixed name would simplify the templates.

And if we can keep the default database location behavior for IceStorm:
"The default for IceStorm.LMDB.Path is the IceStorm service name, which is usually IceStorm".

**Comment by externl** [comment]
> Why is this an issue?
> 
> Switching to a fixed name would simplify the templates.
> 
> And if we can keep the default database location behavior for IceStorm: "The default for IceStorm.LMDB.Path is the IceStorm service name, which is usually IceStorm".

More of an upgrade issue than anything.
