### ISSUE TITLE
Continue simplifying the streaming API

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#280]
There are several features in the stream APIs that Ice no longer use or never used:
- nested encapsulations, none of our Slice types use that
- encapsulation-less streaming (it's possible to stream a type without calling startEncaps/endEncaps)

I believe the later is still used by Freeze for writing data to the databases. It might also be used by the lmdb layer (to be verified). 

Removing support for these features would simplify the streaming API and could even improve performances a bit. We could for example get rid of the encapsulation structure and stack if we remove support for nested encapsulations, we would no longer need to allocate a separate encapsulation structure with the output/input stream.

Removing this means that we could potentially break user code that somehow rely on these features so we need to consider this as well before deciding to remove them.

**Comment by bentoi** [comment]
We should also remove the _encaps pointer from the `EncapsDecoder` class.

**Comment by bentoi** [comment]
Also, we do actually use nested encapsulation to encode endpoints so we still need support for them.

**Comment by bernardnormier** [comment]
We could simplify further with a single encaps per stream (or stream reset where we support stream reuse). I don't think the generated code ever reads or writes a sequence of encaps from/into the same stream.

This would mean no more startEncapsulation, endEncapsulation, readEncapsulation, skipEncapsulation. An InputStream resp. OutputStream would always represent a single encapsulation.

InputStream would get:
- a ctor (reset) that takes a  bytes buffer, and then read size and encoding from this buffer
- another ctor (reset) that takes encoding, size and a separate buffer, and then treat the byte buffer as bytes encoded with encoding up to specified size

Likewise OutputStream would get:
- a ctor (reset) that specifies its buffer starts with encoding/size
- another ctor (reset) that specifies its buffer doesn't include encoding/size

**Comment by bernardnormier** [comment]
With respect to nesting, there is ever only one level - a main encaps that can contain one of more endpoint encaps. An endpoint encaps doesn't contain any other encaps.

We may be able to create a lightweight InputStream/OutputStream for endpoint marshaling/unmarshaling that writes/reads into the main stream's buffer.
