### ISSUE TITLE
brew install zeroc-ice/tap/icetouch@3.6   ERROR

### ISSUE THREAD

**Issue by PaulWyw** [zeroc-ice/ice#2808]
### Version

Mac OS 14.3.1
Xcode  15.4
brew install zeroc-ice/tap/icetouch@3.6  

### Describe the bug

yanweiwu@localhost ~ % brew install zeroc-ice/tap/icetouch@3.6  
==> Fetching zeroc-ice/tap/icetouch@3.6
==> Cloning https://github.com/zeroc-ice/icetouch.git
Updating /Users/yanweiwu/Library/Caches/Homebrew/icetouch@3.6--git
==> Checking out tag v3.6.4
HEAD is now at 5f8ab96 Update ice submodule to v3.6.4
HEAD is now at 5f8ab96 Update ice submodule to v3.6.4
Entering 'ice'
/Users/yanweiwu/Library/Caches/Homebrew/icetouch@3.6--git/ice
==> Installing icetouch@3.6 from zeroc-ice/tap
==> make install prefix=/opt/homebrew/Cellar/icetouch@3.6/3.6.4 OPTIMIZE=yes MCPP_HOME=/opt/homebrew/opt/mcpp
Last 15 lines from /Users/yanweiwu/Library/Logs/Homebrew/icetouch@3.6/01.make:
ld: symbol(s) not found for architecture x86_64
  "_mcpp_use_mem_buffers", referenced from:
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../lib/IceTouch/Cpp/bin/slice2cpp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [../../lib/IceTouch/ObjC/bin/slice2objc] Error 1
make[1]: *** [install] Error 1
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/zeroc-ice/homebrew-tap/issues

### Expected behavior

icetouch@3.6   install  succcess

**Comment by externl** [comment]
IceTouch 3.6 does not support macO 14. Please update to Ice 3.7 (IceTouch was merged into Ice)
