### ISSUE TITLE
Fix createServerProps in csharp/IceSSL/configuration

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2818]
I find this conversion logic unexpected - and ideally we should fix it and just "convert" with:
https://github.com/zeroc-ice/ice/blob/2846e40a8ea07d870d762d89b2075071ab04aba2/csharp/src/Ice/Properties.cs#L285

This is however not the focus of this PR.

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2812#discussion_r1780165712_

**Comment by bernardnormier** [comment]
We actually have the same code in the C++ IceSSL/configuration - it's not C# specific.

**Comment by pepone** [comment]
Not clear that we should use `getPropertiesForPrefix` here, this method is just getting the SSL certs default dir, the default host, and the IPv6 settings. We don't want to accidentally set other SSL properties that can influence the test case.

**Comment by bernardnormier** [comment]
Ok, I am leaving this as-is.
