### ISSUE TITLE
Custom DataStorm CallbackExecutor

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2891]
It would be nice to allow the application to customize the CallbackExecutor used by DataStorm.

It could be the custom executor registered with the underlying Ice communicator. Or a separate customization point.

See https://github.com/zeroc-ice/datastorm/issues/26#issuecomment-2407873013

**Comment by pepone** [comment]
Fixed in #2960

Added a `customExecutor` parameter to the node constructors.
