### ISSUE TITLE
Add DataStorm properties to PropertyNames.xml

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2922]

**Comment by bernardnormier** [comment]
Should we first eliminate the Adapters "namespace"?

https://github.com/zeroc-ice/ice/blob/ff1bcfaab9ce8c49a14740468a7394dbec6797c5/cpp/src/DataStorm/Instance.cpp#L27

**Comment by pepone** [comment]
> Should we first eliminate the Adapters "namespace"?

I think we need to do both together, otherwise, you cannot have `DataStorm.Node.Server.Enabled` and use `DataStorm.Node.Server` as the adapter name.

I think this the reason we have the Adapters namespace to avoid the warnings of unknown adapter properties with 3.7.
