### ISSUE TITLE
Replace getIceProperty exception by fatal error in Swift

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2946]
getIceProperty in Swift should not throw an exception but terminate immediately with a fatal error.

It's odd and unexpected to have a 'try' in simple code like:
```swift
let host = try communicator.getProperties().getIcePropertyAsInt("Ice.IPv6") != 0 ? "::1" : "127.0.0.1"
```

**Comment by externl** [comment]
I think `preconditionError` may be more appropriate. 
- https://www.swiftbysundell.com/articles/picking-the-right-way-of-failing-in-swift/
- https://www.vadimbulavin.com/assert-vs-precondition-vs-fatalerror/
