### ISSUE TITLE
documentation-deprecated-sync for C++ dispatch operations

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2963]
We are adding `@deprecated` to the C++ dispatch operations, but we are not marking them as deprecated.

I think `@deprecated` is wrong, as we only want to deprecate the proxy methods to warn users when they use a deprecated operation.

**Comment by bernardnormier** [comment]
It looks like we removed the `[[deprecated]]` from the generated "disp" functions but forgot to fix the generated doc-comment.
