### ISSUE TITLE
Broken dev container

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3068]
https://github.com/zeroc-ice/ice/blob/40171af6057781f3fd07817c02875cebd525df54/.devcontainer/Dockerfile#L16-L32

The Java setup fails locally when trying to create a dev container.

The downloaded jdk.tgz just contains an HTML with a 404 messeage.

**Comment by externl** [comment]
Hmm it was working recently. I'll try a full rebuild.

**Comment by externl** [comment]
https://github.com/oracle/docker-images/commit/c7f1db999b20abff8fb87ac755bd8d26e6d0f914

**Comment by externl** [comment]
| JDK 17 is no longer available under no fee-term-and-conditions so it now requires users to download the binary first

I'm going to switch us to https://adoptium.net. 

See https://whichjdk.com
