### ISSUE TITLE
Reduce number of InputStream constructors

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#3073]
In C#, InputStream has 26 public constructors, which very much over to top. We need to reduce this number. It's also like some (like 1 or 2) constructors should be internal, not public.

This InputStream constructor overload is not limited to C#.

**Comment by InsertCreativityHere** [comment]
Java also has 26 public constructors. We should also reduce this number.
Since this is the exact same number as C#, the constructors are probably the same.

**Comment by bernardnormier** [comment]
Fixed.
