### ISSUE TITLE
Investigate how to strip Debug.assert calls from JavaScript

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3088]
It would be good to figure how to remove the asserts from "production" builds. Different es6 module bundler provide different options. At the very least document how to do this with the most common ones.

**Comment by pepone** [comment]
For rollup see https://github.com/rollup/plugins/tree/master/packages/strip

**Comment by pepone** [comment]
With esbuild you can use drop labels, strip also support this option

https://esbuild.github.io/api/#drop-labels

This would require to write `DEV: Debug.assert(...)`.

Terser used with WebPack terser plugin supports a `pure_funcs` option which can be configure to remove functions marked as pure, the other option provided by terser is `drop_console` but it would require to use `console.assert` in place of `Debug.assert`

https://terser.org/docs/options/

vite uses esbuild, so the same options apply there.

I wonder if we should upgrade the code to use `console.assert` instead of `Debug.assert`, our custom assert has the advantage of stoping the process when using NodeJS, but it makes a bit harder for WebPack users to strip asserts.

And then also use a label for all the asserts, like `DEV: console.assert(...)`, which works better with esbuild than a plain drop.

**Comment by externl** [comment]
`console.assert` sounds good to me!
