### ISSUE TITLE
Remove property defaults which are really just fallbacks for a computation

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#3140]
Should we simply set the default IceGrid.InstanceName in PropertyNames.xml to empty?

There is no point setting a default value in PropertyNames.xml if it's never read.

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/3136#discussion_r1838406077_

**Comment by bernardnormier** [comment]
Another related example:

```csharp
        if (ipv4 && !preferIPv6)
        {
            address = properties.getPropertyWithDefault("IceDiscovery.Address", "239.255.0.1");
        }
        else
        {
            address = properties.getPropertyWithDefault("IceDiscovery.Address", "ff15::1");
        }
```

and https://github.com/zeroc-ice/ice/blob/aaaf89dc8e93f65e342d560b7d6933152dd6c758/config/PropertyNames.xml#L181

Why not rewrite this code as:
```csharp
address = getIceProperty("IceDiscovery.Address"); // no default, and we rely on the getIceProperty check

if (address.Length == 0) // not set, use "computed" default
{
    address = ipv4 && !preferIPv6 ? "239.255.0.1" : "ff15::1";
}
```
