### ISSUE TITLE
.NET Core 3 preview

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#322]
.NET Core 3 preview has been released few days ago. I gave it a quick try, the build appears to work but running the tests doesn't. It complains about not find the .NET Core 2.x framework.

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
...
```

It would be good if 3.7.2 supported it without additional modifications.

**Comment by pepone** [comment]
Fixed with f87580189e3462bc36280291a5c92ddbf2d81bfb
