### ISSUE TITLE
Is There a Point to Supporting Both `["deprecated"]` Metadata and the `@deprecated` Comment Tag?

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#3225]
And if there is, is there some clear guidance we should offer users as to what the difference is between:

```
/// Does a cool thing.
["deprecated:you shouldn't use this thing"]
myOperation();
```
vs
```
/// Does a cool thing.
/// @deprecated you shouldn't use this thing
myOperation();
```

----

To me, it feels like only having one of these would be sufficient.
And I would especially like to avoid requiring users to do this:
```
/// Does a cool thing.
/// @deprecated you shouldn't use this thing
["deprecated:you shouldn't use this thing"]
myOperation();
```

**Comment by bernardnormier** [comment]
The deprecated metadata and optional message has two purposes:
 - issue a warning (+ message) during Slice compilation
 - generate a corresponding attribute on the mapped C++, C#, Java etc. API

On the other hand, the @deprecated doc-comment tag is about:
 - generating documentation for the Slice API (with doxygen)
 - generating the corresponding doc comment tag in the mapped C++, Java etc. API
This doesn't work for all languages. For example, there is no "deprecated" XML doc-comment in C#, so we don't map it in C#.

 C++ with doxygen just like Slice supports both a `[[deprecated]]` attribute and an `@deprecated` doc-comment tag.
