### ISSUE TITLE
Util.cpp:212:18: error: call of overloaded ‘DbEnv(int)’ is ambiguous      DbEnv dbEnv(0);

### ISSUE THREAD

**Issue by fangxian** [zeroc-ice/ice#325]
On ubuntu16.04, gcc7.3
when I compile Ice3.6.1, I got the error: 
error: call of overloaded ‘DbEnv(int)’ is ambiguous
     DbEnv dbEnv(0);

after  I use a integer variable which equal 0 to replace it, Ice can be compiled success.

**Comment by pepone** [comment]
Hi @fangxian 

We support Ice 3.6 with Ubuntu Xenial (16.04) see here for instructions of installing the official packages https://zeroc.com/downloads/ice/3.6#ubuntu

The default compiler for Ubuntu Xenial (16.04) is G++ 5.4 that is what we use and what we support for building Ice.

If you need support for more recent compilers or if you are just starting a new project is best to use Ice 3.7 (latest stable release), that support most moderm C++ compilers and includes a new [C++11 mapping](https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/selecting-the-c++11-mapping).

**Comment by bernardnormier** [comment]
Note that this failure corresponds to Freeze code (DbEnv is a Berkeley DB API).

As of Ice 3.7, Freeze is in a separate repository and Ice no longer depends on Berkeley DB.

Are you using Freeze? 

If not, then upgrading to Ice 3.7 will resolve your issue. If you are using Freeze and you encounter issues building Freeze 3.7 (https://github.com/zeroc-ice/freeze), please give us a more detailed error message (with line numbers), and also tell us the version of Berkeley DB you're using.
