### ISSUE TITLE
Review IceSSL protocol defaults

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#332]
We should review our IceSSL protocol defaults. We bake in (as of 3.7.1) defaults instead of using platform defaults. In the past this was because SSLv3 as still enabled by default on many platforms. 

If we move back to using system defaults it would maybe resolve future issues with new protocols such as https://github.com/zeroc-ice/ice/issues/330. 

If we keep using our own defaults we should remove `TLSv1.0`, as it's no longer recommended for use.

**Comment by pepone** [comment]
For C# using SsslProtocols.None will allow IceSSL negotiate the connection using system defaults

**Comment by pepone** [comment]
With 3.8 we removed `IceSSL.Protocols`, and use system defaults in all platforms. The only way to change the SSL protocols in 3.8 is either use the new SSL native APIs, or change the system wide defaults.
