### ISSUE TITLE
How can I configure a servant run in a same thread per connection? 

### ISSUE THREAD

**Issue by duo2005duo** [zeroc-ice/ice#333]
How can I configure a servant run in a same thread per connection? It will avoid the concurrency problem as  each data bound to a connection.Is there any solution？

**Comment by bentoi** [comment]
We don't provide a configuration to allow dispatching with a thread-per-connection model. This is something you could however implement using the [Ice dispatcher API](https://doc.zeroc.com/ice/3.7/client-server-features/the-ice-threading-model/dispatching-requests-to-user-threads). 

The dispatcher implementation would dispatch requests to threads allocated for each connection. The connection is provided as an argument of the dispatcher. To cleanup threads, you can register a [connection close callback](https://doc.zeroc.com/ice/3.7/client-server-features/connection-management/using-connections).
