### ISSUE TITLE
IceBoxNet should print version to stderr

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#341]
https://github.com/zeroc-ice/ice/blob/06c8e24df0f7abb6d23e9d4d6bee21febad27a0f/csharp/src/IceBox/Server.cs#L67

Version should go to stderr like other command line tools, but better not change this in a patch release.

**Comment by bernardnormier** [comment]
I think all versions should actually go to stdout. See #306.

**Comment by pepone** [comment]
right I was checking what we do, but if we plan to fix #306 no need to change that
