### ISSUE TITLE
Custom mapping for values

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#351]
Values (class instances) can be manufactured by user-registered factories:
https://doc.zeroc.com/ice/3.7/the-slice-language/classes/value-factories

The actual C++/C#/Java (...) classes created by these value-factories derive from the C++/C#/Java classes generated by the Slice compilers. Currently, the generated APIs only show the generated classes--not the "custom classes" manufactured by the value factories. So users have to downcast the operation parameter (or data member) to get to these classes.

We can probably remap parameters and data members to these custom classes through metadata. The  generated code would then do the downcast for the user. For example:
```
["protected"] class TimeData 
{
    long millis;
}

interface TimeKeeper
{
    ["cpp:type:myutil::Time"] TimeData remoteTime();
}
```

In C++11, the mapped proxy member function would return a `std::shared_ptr<myutil::Time>`, with the assumption that:
*  `myutil::Time` derives from TimeData
*  the application registers a value factory for `TimeData` that returns a `myutil::Time`

In C++, there is a potential difficulty with include ordering. In the example above, the full declaration of `myutil::Time` probably needs to be visible in the generated header file. And this generated header defines Time's base class (`TimeData`).

**Comment by pepone** [comment]
For C# the need for custom classes can be avoid taking advantage of partial classes.

For C++ the custom class will have to be forward declared in the generated header, and fully visible in the generated source, we will need a new metadata to allow adding the required headers to generated source.

There is also problems with inheritance if you have Slice classes `A` -> `B` and then map `A` to `CustomA` and `B` to `CustomB` in languages with single inheritance you cannot pass `CustomB` for a method expecting `CustomA`

See also #374 , moving to 4.0 for now
