### ISSUE TITLE
Move splitScopedName to Slice/SliceUtil.cpp

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#364]
We have implementations of this copied in almost all Slice compilers

https://github.com/zeroc-ice/ice/search?q=splitScopedName&unscoped_q=splitScopedName

**Comment by InsertCreativityHere** [comment]
This was originally implemented in 5c8eff5ec4a64b640ce07567602cba8a3589cfbb,
which was backported to 3.8 by #1588
