### ISSUE TITLE
Remove nonmutating metadata 

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#370]
The `nonmutating` keyword was deprecated in Ice 3.2 and removed in Ice 3.3. As of Ice 3.7, we keep limited support for nonmutating with the nonmutating metadata. This allows interop with Ice <= 3.2 servers still using this keyword.

Ice 3.2 is very old now so we can remove this metadata. We still need to keep the OperationMode Nonmutating enumerator since Ice 3.7 and earlier send the  Nonmutating operation mode with various operations including `ice_isA` and `findAdapterById`.

**Comment by InsertCreativityHere** [comment]
This was removed in 3 parts:
#2023 #2121 #2127
