### ISSUE TITLE
Make colon (:) an alias for extends

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#372]
Slice uses `extends` and `implements` for inheritance just like Java: a Slice interface can extend other Slice interfaces, and a Slice class can implement Slice interfaces and extend another Slice class.

A Slice class implementing an interface is rare and is deprecated since Ice 3.7, so `extends` is in effect the only inheritance keyword in Slice. It would be nice to support `:` as an alias for `extends`.

**Comment by InsertCreativityHere** [comment]
Added in 7315a2c8e81a24994480466313fdc4b1880e4f4b
