### ISSUE TITLE
["swift:class"] and Hashable

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#384]
When you map a Slice structure to a class with ["swift:class"], the generated class should never adopt Hashable.

**Comment by pepone** [comment]
How should we handle the case of structure with ["swift:class"] used as a dictionary key type. I think the best is to check for ["swift:class"] in https://github.com/zeroc-ice/ice/blob/swift/cpp/src/Slice/Parser.cpp#L5240

Other option is to get rid of "swift:class" and only use the class mapping for structs when the struct contains class members, in which case is not a valid dictionary key

**Comment by bernardnormier** [comment]
I think the simplest is the eliminate `["swift:class"]`.

If we keep `["swift:class"]`, I wouldn't enforce the dictionary key constraint in the parser but when the Slice compiler is about to generate code for a `dictionary<ValidKeyStructWithClassMapping, V>`.

**Comment by pepone** [comment]
Removed `[swift:class]` https://github.com/zeroc-ice/ice/commit/a1193f42c67bd023409352766cb6d46beb64c7b6
