### ISSUE TITLE
Remove Ice exception cloning

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#385]
Ice exceptions can be cloned in most language mappings even though this cloning is not used or useful.

Ice C++ uses exception cloning to capture a thrown exception and store it in a data member for later use. This can most likely be replaced by a `std::exception_ptr` captured with `std::current_exception()`.

Needs to be fixed in:
- [x] C++
- [x] C#
- [x] Java
- [x] JavaScript
- [x] MATLAB
- [x] PHP
- [x] Python
- [x] Ruby
- [x] Swift

**Comment by bernardnormier** [comment]
Already fixed in C++.

**Comment by pepone** [comment]
There was no exception clone in Python and JavaScript.

**Comment by InsertCreativityHere** [comment]
The Java side was implemented in #2641
