### ISSUE TITLE
Unmarshalling "enumerator out of range" when Enum has undefined 0 value in Slice definition

### ISSUE THREAD

**Issue by LukaszSolo** [zeroc-ice/ice#388]
Hi,

Version: Ice 3.7.2 (from the website)

I've encountered an issue/bug when working with C++ communication.
If Enum is defined in Slice file that there is no enum defined for the `0` value, the code generation and compilation will pass, but there will be `protocol error: error during marshaling or unmarshaling: enumerator out of range` when we try to send object without the enum field having set a value (so the field will be initialized with 0 value).
I will use `printer` example from C++ repo to illustrate the issue.

I've added Enum whose first field is 1, thus there is no field that corresponds to `0` value.

If we change the Slice definition of `Printer.ice` to:
```
module Demo
{
  enum EnumType {
  FieldOne = 1,
  FieldTwo	
  }

  class EnumClass {
    EnumType enumField;
  }

  interface Printer
  {
   void CallMethod(EnumClass s);
  }
}
```

Next in the client.cpp, call the `CallMethdod`

```
auto p = make_shared<EnumClass>();
//p->enumField = EnumType::FieldOne;
printer->CallMethod(p);
```
will trigger the error
(notice the commented setting of enumField value above)

I'm not sure if we should treat this behaviour as a bug, but it's confusing. Maybe when compiling to c++ there should be an error that Enum doesn't have value for 0, and there will be error during marshalling. #

**Comment by bernardnormier** [comment]
This is the expected behavior, see https://doc.zeroc.com/ice/3.7/language-mappings/c++11-mapping/client-side-slice-to-c++11-mapping/c++11-mapping-for-classes#id-.C++11MappingforClassesv3.7-ClassConstructorswithC++

In particular the note about enumerated types:

> This is especially true for enumerated types as the member's default value may be outside the legal range for the enumeration, in which case an exception will occur during marshaling unless the member is explicitly set to a legal value.

You can give a default value to your enumField data member (in Slice) to get the desired behavior:
```
class EnumClass {
    EnumType enumField = FieldOne;
  }
```

Best regards,
Bernard

**Comment by LukaszSolo** [comment]
Ahhh, thanks! Makes perfect sense. Do you think it would make sense to mention this, or to point to this doc, in the enum documentation e.g. `C++ Mapping for Enumerations` ? I think now, knowing where to look, I can see where my confussion come from as the Python side of the documentation states that for enum, default value is `First enumerator in enumeration ` so when I was testig it with Python, it worked, but didn't from C++, with the same Slice definition.

Thank you for quick response!

**Comment by bernardnormier** [comment]
Thanks for the suggestion! I added a "tip" on the [C++11 Mapping for Enumerations](https://doc.zeroc.com/pages/viewpage.action?pageId=30218504) page.

Cheers,
Bernard
