### ISSUE TITLE
Change C++ APIs that accept durations to use std::chrono::duration

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#396]
This will allow using duration literals, for example: `prx->ice_timeout(2s)`

**Comment by pepone** [comment]
For the locator cache timeout current have:

 -  0 disable cache
 -  -1 cached entries never expire (infinite TTL)
 -  Other values is the TTL in seconds

For invocation timeout:
-  -1 disable invocation timeouts
- Any other values less than 1 is invalid
- Other values greater or equal to 1 is the invocation timeout in milliseconds

I was thinking about using `optional<chrono::seconds>` and `optional<chrono::milliseconds>` for locator cache timeout and invocation timeout respectively.

But not clear what nullopt should be used for the locator cache case, maybe using a non optional is clear. any thoughts?

**Comment by bernardnormier** [comment]
Should we also fix the other languages? For example:

https://github.com/zeroc-ice/ice/blob/96a4f99c87443a76b51a27438d4163fb5df95e15/csharp/src/Ice/Proxy.cs#L226

**Comment by bernardnormier** [comment]
Maybe we should add overloads to the setters (with std::chrono::duration, C# TimeSpan etc.) and keep the existing setter for backwards compatibility. The getters (presumably called less often) should return the new types.

**Comment by pepone** [comment]
Fixed C++/Java/C# has now overloads that use the native duration types.

C++ #2794
Java #2801
C# #2809
