### ISSUE TITLE
Can support rust language？

### ISSUE THREAD

**Issue by rainwolfchen** [zeroc-ice/ice#397]
Now rust language is becoming more and more popular， zeroc-ice can support rust？ Thanks！

**Comment by ta32** [comment]
rust is a great system building language please support it. Support it over languages like matlab lol

**Comment by pepone** [comment]
Hi,

Thanks for the suggestion, we will consider supporting rust if there is more demand for it.

**Comment by Paulswith** [comment]
+1. Rust is a great program language, please support it.

**Comment by grembo** [comment]
+1, Rust support would be really cool.

**Comment by xujq1** [comment]
+1, Rust is a great program language, please support it.

**Comment by hbzhouwei** [comment]
+1, Rust is a great program language, please support it.

**Comment by cclienti** [comment]
+1, Rust support would be really nice

**Comment by reison1218** [comment]
+1,i use zeroc in java before,now i really hope zeroc can support rust!

**Comment by liyunde** [comment]
During container development,go and rust is the most common, suggestion Support one of them,thanks

**Comment by smandy** [comment]
+1

**Comment by zamazan4ik** [comment]
Any updates? Could you reopen the issue please? Thanks in advance!

**Comment by fwt11** [comment]
+1

**Comment by bold84** [comment]
+1

**Comment by Silmerias** [comment]
+1 RUST

**Comment by pepone** [comment]
The current plan is to add Rust support in [IceRPC](https://zeroc.com/icerpc).

We are still in the initial state of creating the IceRPC Rust mapping.

See also https://github.com/orgs/icerpc/discussions/4
