### ISSUE TITLE
Incorrect generated code for class implements interface (C++11)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#406]
slice2cpp 3.7.2 does not generate correct code for:
```
module M
{
    class A
    {
        int x;
        // void opA();
    }

    interface Intf
    {
        void opIntf();
    }

    class B extends A implements Intf
    {
        void opB();
    }
}
```

For the C++11 mapping code, the generated BPrx should derive from IntfPrx (but does not). Likewise, BDisp should derive from Intf but does not.
Other language mappings don't seem affected by this bug - checked C++98, C#, Java, MATLAB and Python.

**Comment by pepone** [comment]
Matlab generated code is also bogus there is an extra `APrx` in `BPrx` constructor

```
function obj = BPrx(communicator, encoding, impl, bytes)
    obj = obj@M.APrx(communicator, encoding, impl, bytes);
    obj = obj@M.IntfPrx(communicator, encoding, impl, bytes);
end
```
