### ISSUE TITLE
Combine with spring And read old server code(even updated)

### ISSUE THREAD

**Issue by MHeartRain** [zeroc-ice/ice#409]
I have some problems . help me.

1、How to integrate IceBox and IceGrid with Spring
2、I started the server and changed its processing code( servant ), it will still execute the old code process. just like having some server cache .

I don't know how to do it ?

**Comment by bentoi** [comment]
Can you describe a little more your existing architecture and what you are trying to do? I'm afraid otherwise it's difficult to help.

**Comment by MHeartRain** [comment]
When the icebox is started, use spring to inject the instance, but it does not succeed. I feel that this is two containers.

**Comment by bentoi** [comment]
I don't know very well Spring... IceBox is a container tailored for running IceBox services not Spring services or beans. Are you trying to run a Spring container from an IceBox service? 

Why do you want to use IceBox to run Spring?

**Comment by MHeartRain** [comment]
> I don't know very well Spring... IceBox is a container tailored for running IceBox services not Spring services or beans. Are you trying to run a Spring container from an IceBox service?
> 
> Why do you want to use IceBox to run Spring?

I am not using icebox to run spring, I just use ice to integrate spring, but it failed. Because I use spring to manage other instances, and in the icebox I want to use spring (annotation) to call other services.

**Comment by MHeartRain** [comment]
> I don't know very well Spring... IceBox is a container tailored for running IceBox services not Spring services or beans. Are you trying to run a Spring container from an IceBox service?
> 
> Why do you want to use IceBox to run Spring?

I tried to use icegrid to integrate spring, but it also failed.

**Comment by bentoi** [comment]
Can spring annotations be used outside the context of a spring container? 

IceBox and IceGrid don't support any specific Spring integration... they just run regular Java code either through an IceBox java service or Java process. 

Since your issue is more related to using Spring components outside the context of a Spring container, I recommend to seek for help on Spring forums instead.

**Comment by MHeartRain** [comment]
> Can spring annotations be used outside the context of a spring container?
> 
> IceBox and IceGrid don't support any specific Spring integration... they just run regular Java code either through an IceBox java service or Java process.
> 
> Since your issue is more related to using Spring components outside the context of a Spring container, I recommend to seek for help on Spring forums instead.

Will the future integrate with spring?

**Comment by MHeartRain** [comment]
> Can spring annotations be used outside the context of a spring container?
> 
> IceBox and IceGrid don't support any specific Spring integration... they just run regular Java code either through an IceBox java service or Java process.
> 
> Since your issue is more related to using Spring components outside the context of a Spring container, I recommend to seek for help on Spring forums instead.

thank you very much  :)

**Comment by bentoi** [comment]
We don't have plans to provide Spring integration in the future so far. It's unclear what this integration could be actually... My understanding is that to be able to use Spring annotations you have to run your code inside a Spring container. I don't really see why you'd want to use Spring annotations with another type of container such as IceBox.

Note that you should be able however to use Ice from your Spring code (as long as it's running in a Spring container) and make invocations on regular Ice servers (either implemented as regular Java processes, IceBox Java services or even implemented in other languages such as C++, C#, etc).

**Comment by MHeartRain** [comment]
> We don't have plans to provide Spring integration in the future so far. It's unclear what this integration could be actually... My understanding is that to be able to use Spring annotations you have to run your code inside a Spring container. I don't really see why you'd want to use Spring annotations with another type of container such as IceBox.
> 
> Note that you should be able however to use Ice from your Spring code (as long as it's running in a Spring container) and make invocations on regular Ice servers (either implemented as regular Java processes, IceBox Java services or even implemented in other languages such as C++, C#, etc).

In fact, I tried to use spring annotations in the servant

**Comment by bentoi** [comment]
Hosting Ice servants within a Spring container should be possible. You will need to create the Ice communicator, an Ice object adapter and register the servant with the Ice object adapter. You will need to do this from a Spring component hosted by the Spring container.

**Comment by MHeartRain** [comment]
> Hosting Ice servants within a Spring container should be possible. You will need to create the Ice communicator, an Ice object adapter and register the servant with the Ice object adapter. You will need to do this from a Spring component hosted by the Spring container.

Just like rewriting the source code of the icebox, is it just managed with spring?

**Comment by bentoi** [comment]
No, there's no need to rewrite IceBox within the context of Spring, you just need to write the code necessary for hosting an Ice servant within a Spring container... 

It's just few lines of code as demonstrated by the Ice minimal Java server demo here:

https://github.com/zeroc-ice/ice-demos/blob/3.7/java/Ice/minimal/Server.java

**Comment by MHeartRain** [comment]
> No, there's no need to rewrite IceBox within the context of Spring, you just need to write the code necessary for hosting an Ice servant within a Spring container...
> 
> It's just few lines of code as demonstrated by the Ice minimal Java server demo here:
> 
> https://github.com/zeroc-ice/ice-demos/blob/3.7/java/Ice/minimal/Server.java

thanks a lot
