### ISSUE TITLE
Question: How to passing class/struct instances by reference on ice 3.7

### ISSUE THREAD

**Issue by khoinguyen90** [zeroc-ice/ice#410]
As i know that `Passing class instances by reference is deprecated on Ice 3.7`
I want to pass an instance of struct/class as an argument inside a method from c++ to c# and then c# server will change member value inside that instance. So, is there way to do that on Ice 3.7.

**Comment by bentoi** [comment]
You can still pass a Slice struct or class instance through a Slice method of an interface. For example, you could use the following Slice contract:

```
// Slice
module Demo {
     struct MyStruct { 
         int a;
     }

     class MyClass {
          int b;
     }

     interface MyInterface {
          void updateStruct(MyStruct s);
          void updateClass(MyClass s);
     }
}
```

Does this answer your question or are you trying to do something else?

**Comment by khoinguyen90** [comment]
I tried to do like that but it is passing struct as value, not as reference

I want like as following.
```
// Slice
module Demo {
     struct MyStruct { 
         int a;
     }

     interface MyInterface {
          void updateStruct(MyStruct s);
     }
}

// Server c#
void updateStruct(MyStruct s, Current current = null)
{
    s.a = 10;
}

// Client c++
const std::shared_ptr<MyStruct > sharedInstance = std::make_shared<MyStruct >();
MyInterfaceInstance->updateStruct(sharedInstance);
// After that value of sharedInstance->a will be changed to 10

```

Current my solution is `void updateStruct(MyStruct inStruct, out MyStruct outStruct);`

**Comment by bentoi** [comment]
Ok, we never really supported this. Ice doesn't allow passing structs or classes by reference, they can only be passed by value. You could use the following Slice to update your struct "by reference":
```
// Slice

struct MyStruct
{
    int a;
    long b;
}

interface MyStructUpdater
{
    void updateA(int newValue);
    void updateB(long newValue);
}

interface MyInterface
{
    void updateStruct(MyStructUpdater* updater);
};
```

The C# server can use the updater to update the struct:

```
// C#
void updateStruct(MyStructUpdaterPrx updater, Current current)
{
    updater.setA(10);
    updater.setB(5);
}
```

Note however that this code has a number of drawbacks:
- you don't provide the struct initial value to the server
- the server has to make nested invocations to update the struct data members
- it results in more remote invocations

You have to carefully consider the pros & cons of this solution compared to your solution (updateStruct) which doesn't have these issues.

**Comment by khoinguyen90** [comment]
Oke thanks.
