### ISSUE TITLE
IcePHP_defineSequence() expects parameter 2 to be object, null given

### ISSUE THREAD

**Issue by lostmilky** [zeroc-ice/ice#412]
IcePHP_defineSequence() expects parameter 2 to be object, null given
"line": 113,
 "file": "/usr/share/php/Ice/BuiltinSequences.php",
 "class": "ErrorException",

Ice version 3.7.2

**Comment by pepone** [comment]
Can you provide some more info on how to reproduce this problem, the operating system you are using, and how you install Ice for PHP?

I think there problem might be a missing global definition in Ice_ns.php

can you check if defining these globals solves your problem?

You should add 
```
global $Ice__t_Value;
global $Ice__t_ObjectSeq;
global $Ice__t_LocalObject;
global $Ice__t_ObjectPrx;
global $Ice__t_ObjectProxySeq;
```
in https://github.com/zeroc-ice/ice/blob/2e2910756b5cfa220baab7cb0b482af4738f59a1/php/lib/Ice_ns.php#L117
