### ISSUE TITLE
C# Glacier2/router test failure on archlinux

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#426]
On ArchLinux the .NETCore Glacier2/router test failed when ran with wss/compress.

In the server log:
{code}
-- 7/2/19 11:31:51:978 server: Network: received wss data frame with payload length of 154 bytes
   local address = ::1:14100
   remote address = ::1:51200
-! 7/2/19 11:31:52:020 server: warning: connection exception:
   Ice.FeatureNotSupportedException
       unsupportedFeature = "Cannot uncompress compressed message: libbz2.so.1 not found"
      at Ice.ConnectionI.parseMessage(MessageInfo& info) in /home/vagrant/workspace/ice/3.7/csharp/src/Ice/ConnectionI.cs:line 2735
   local address = ::1:14100
   remote address = ::1:51200
-- 7/2/19 11:31:52:038 server: Network: closed wss connection
   local address = ::1:14100
   remote address = ::1:51200
   Ice.FeatureNotSupportedException
       unsupportedFeature = "Cannot uncompress compressed message: libbz2.so.1 not found"
      at Ice.ConnectionI.parseMessage(MessageInfo& info) in /home/vagrant/workspace/ice/3.7/csharp/src/Ice/ConnectionI.cs:line 2735
{code}

This is occurring when the client calls initiateCallback. The clients ends up hanging indefinitely in callbackOK because the oneway initialiteCallback is never dispatched by the server.

It would be better to not indefinitely wait for the callback but support a timeout. The compression issue still needs to be fixed however.

**Comment by pepone** [comment]
Fixed bzip2 loading in 26fedc61b19971a2636332d718e83fe6f0848066
