### ISSUE TITLE
Why does the Object2 and ObjectPrx generated by slice2java have static methods?

### ISSUE THREAD

**Issue by CrazyHZM** [zeroc-ice/ice#430]
Why does the Object and ObjectPrx generated by slice2java have static methods, such as `checkedCast`, can be changed to the default type? because the method with static type cannot be compiled when the interface is dynamically proxyed.

**Comment by pepone** [comment]
The static methods are part of the API an cannot be changed, what do you mean by:
> cannot be compiled when the interface is dynamically proxyed

**Comment by CrazyHZM** [comment]
I have already checked the problem, thanks
