### ISSUE TITLE
C++11  enum in struct error with compiled code

### ISSUE THREAD

**Issue by thansen24** [zeroc-ice/ice#458]
I'm using ICE 3.7.1 and trying to upgrade from the c++98 to the c++11 mapping but am having trouble with the generated code for some of my structures when they have a field that is happened to be named the same as the enum type.  Here is a sample to reproduce using the Demos

```
module Demo
{
    enum NumberType
    {
        HOME,
        OFFICE,
        CELL
    }

    struct Contact
    {
        string name;
        NumberType NumberType;
    }
}
```

This results in the following error:

```
./Contact.h:70:44: error: must use 'enum' tag to refer to type 'NumberType' in this scope
    std::tuple<const ::std::string&, const NumberType&> ice_tuple() const
                                           ^
                                           enum
./Contact.h:63:16: note: enum 'NumberType' is hidden by a non-type declaration of 'NumberType' here
    NumberType NumberType;
               ^
1 error generated.
```

**Comment by bernardnormier** [comment]
Thank you for this bug report and test-case. This is indeed a bug in the generated code, still present in Ice 3.7.2.

**Comment by thansen24** [comment]
Thanks for the quick response, I'll keep an eye out for the 3.7.3 release!

**Comment by thansen24** [comment]
I came across two more instances where I ran across a similar problem, but it's different enough that I thought I'd add it here for your test cases.

```
module Demo
{
    struct Address
    {
        string streetName;
        int zipCode;
    }

    struct Contact
    {
        string name;
        Address Address;
    }
}
```

and

```
module Demo
{
    sequence<long> PhoneNumbers;

    struct Contact
    {
        string name;
        PhoneNumbers PhoneNumbers;
    }
}
```

**Comment by pepone** [comment]
The first test also fail with C++98 mapping
```
test/Ice/scope/generated/Test.h:2268:16: error: declaration of ‘Test::NumberType Test::Contact::NumberType’ [-fpermissive]
     NumberType NumberType;
                ^~~~~~~~~~
test/Ice/scope/generated/Test.h:2258:6: error: changes meaning of ‘NumberType’ from ‘enum Test::NumberType’ [-fpermissive]
 enum NumberType
```

**Comment by thansen24** [comment]
Hmmm, that doesn't fail for me.  I'm using clang 8 on el7.  What compiler version are you using?  With what flags?

**Comment by pepone** [comment]
`gcc version 8.3.0 (Debian 8.3.0-6)` with C++98 mapping

**Comment by thansen24** [comment]
Ok yeah, I see that as a compiler warning with gcc 4.8.5 on el7 as well.

**Comment by pepone** [comment]
I think that for C++ we will be best of using C++ full qualified names everywhere

**Comment by pedia** [comment]
temporary or better, should change
```
        PhoneNumbers PhoneNumbers;
```
to 
```
        PhoneNumbers phoneNumbers;
```
