### ISSUE TITLE
icegrid/icestorm freezes when network link goes down

### ISSUE THREAD

**Issue by mirkow** [zeroc-ice/ice#463]
When switching off WiFi or just losing a connection or when shutting down a network interface, some/all Ice services that we use, freeze.
We are using IceGrid and IceStorm. We need to kill all ice processes and start them again.
However, this doesn't happen always, but frequently.

Is this known?

Ice Version: 3.7.0
This bug was already in Ice3.5.1

**Comment by externl** [comment]
Hi @mirkow 

What do you mean by "freezes when network link goes down"? Can you explain in more detail how to reproduce your issue (eg are you stopping and then starting restarting network services, etc) .

**Comment by mirkow** [comment]
It usually happens when losing the connection to a WiFi network. It also happened when (for some unknown reason) the network link of the LAN interface went down and up again.
But I couldnt reproduce it on purpose yet.

**Comment by bernardnormier** [comment]
Hi @mirkow,

Can you tell us exactly what happened when your Wifi/ethernet goes down? "Freezing" is not a clear description of an issue.

Obviously you can't reach any Ice service or server remotely when your computer is unreachable. If it's a temporary outage, the Ice server or service should respond to new requests when the network is back-up. 

Are you using DHCP and the IP address of your machine changes during this outage? Which OS and Ice distribution are you using? Why are you using Ice 3.7.0 and not the latest Ice 3.7, Ice 3.7.2?

Best regards,
Bernard

**Comment by mirkow** [comment]
Hi @bernardnormier,

everything is running on the local machine, so the network reachability shouldn't be a problem.
With "freezing" I mean that IceStorm topic publish-calls do not arrive at the subscribers. Also, the Ice services (icegridnode, icebox) cannot be stopped gracefully. Only "kill -9" works.
What other ways do you suggest to see if the services are still running properly?

On some machines, we use DHCP and others we don't.
We are using Ubuntu 18.04 and thus the Ice package coming with it (3.7.0)

Thanks for your fast responses @externl @bernardnormier 

Cheers
Mirko

**Comment by externl** [comment]
Were you able to reproduce with a DHCP IP change? Do the services become response again after stopping and starting network services?

**Comment by externl** [comment]
@mirkow you should consider using our Apt repository (see https://zeroc.com/downloads/ice#ubuntu) as it contains the the most recent patch release of Ice (3.7.2).

**Comment by mirkow** [comment]
Also, the IP change didn't freeze it. So far no freeze again. 
What are your suggestions on how to debug the problem, once it occurs again?

@externl We like to stick to the main repositories to have the installation as easy as possible.

**Comment by pepone** [comment]
Hi @mirkow , you should attach the debugger to the process once it freezes and get a stack trace of all the threads, this will give us a better idea of what's going on.

You should also enable protocol and network tracing to have a better idea of what were the services doing when this happen:
 * see https://doc.zeroc.com/ice/3.7/property-reference/ice-trace

Make sure you install the corresponding symbols packages (<package-name>-dbgsym) to get a meaningful stack trace
