### ISSUE TITLE
Android Test failing for WS

### ISSUE THREAD

**Issue by ReeceHumphreys** [zeroc-ice/ice#478]
Getting random SocketException error when switching between tests on Android on WS mode.
Can recreate by starting other tests and trying to quickly switch back to acm.

![Screenshot_1565366212](https://user-images.githubusercontent.com/14209515/62792625-b02ece00-ba9d-11e9-922c-01ba042c7a25.png)

**Comment by pepone** [comment]
Can you clarify how are you switching tests? are you hitting the back button while test are running and starting a new one?

**Comment by ReeceHumphreys** [comment]
Yes, I selected a random test from the list, pressed the back button and started the acm one as fast as possible but it took a few tries to get it to throw the error.

**Comment by ReeceHumphreys** [comment]
I believe this error can be caused on multiple tests, the acm was the only one I was able to recreate so far.

**Comment by pepone** [comment]
I think it is the test controller doesn't gracefully tear down tests when using the back button, will be better to disable it while a test is running, but I will no bother to fix this now if there isn't problems running the tests sequentially, or hitting back after they finish run.
