### ISSUE TITLE
slice2js: Typescript and forward declarations

### ISSUE THREAD

**Issue by alnr** [zeroc-ice/ice#483]
#97 documents limitations regarding forward declarations in slice files, which were lifted for 3.7.3.

Using forward declarations does not work with the `--typescript` flag to `slice2js`.

Minimal example
slice file: https://github.com/zeroc-ice/ice/blob/3.7/js/test/Ice/objects/Test.ice
```
$ npx slice2js --version
3.7.3
```
(build from current HEAD of `3.7` branch)
```
$ npx slice2js --typescript Test.ice 
/Users/aluenser/dev/slice2js-ts-forward/node_modules/slice2js/build/Release/slice2js: error:../ice/cpp/include/IceUtil/Handle.h:41: ::IceUtil::NullHandleException
```

**Comment by externl** [comment]
Thanks for reporting this issue, @alnr!
