### ISSUE TITLE
IceBox Java/C# service manager shutdown while start in progress

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#486]
Since the fix for #314 it's possible for the communicator shutdown to occur while `ServiceManagerI.run` is in progress. 

This might lead to some `ServiceManager: caught exception` messages if `CommunicatorDestroyedException` or `ObjectAdapterDeactivation` is raised since we don't catch them except toward the end or `run` when we create the admin OA or activate the service manager adapter...

We should either catch these or possibly move the installation of the shutdown hook / key interrupt handler after start completed like in C++.

**Comment by bernardnormier** [comment]
I think the desired behavior is to shutdown cleanly when the user sends SIGINT or similar during IceBox startup, and not ignore these signals during startup like we do in C++ (in Ice::Service, used by IceBox).

Furthermore in Java the ShutdownHook API is quite limited, and ignoring or deferring the processing of a signal is not doable.

**Comment by bentoi** [comment]
So we should fix the exception handling to except `_communicator` shutdown?

**Comment by bernardnormier** [comment]
> So we should fix the exception handling to expect `_communicator` shutdown?

Yes, and ignore any resulting exception.
