### ISSUE TITLE
Consider supporting SNI on the server side

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#493]
We should consider supporting SSL SNI extension on the server side if it's supported on the client side following the addition of https://github.com/zeroc-ice/ice/pull/482

**Comment by externl** [comment]
We only ever have one certificate at a time right mow, do we plan on changing this for 4.0? Add support for multiple certificates in one communicator.

**Comment by pepone** [comment]
Dup of #2090, keeping the new one as it targets the new PAI
