### ISSUE TITLE
Install from sources to /usr/local directory.

### ISSUE THREAD

**Issue by akabanov57** [zeroc-ice/ice#504]
Hello,
I installed ICE for c ++ to /usr/local directory. I changed prefix ?= /usr/local in config/Make.rules and executed sudo make CONFIGS=cpp11-shared install. The process completed successfully. But there is no slice directory in /usr/local. As result eclipse builder shows error. When I copied the slice directory to /usr /local manually, I was able to use ICE without any problems.

**Comment by pepone** [comment]
Slice files are installed only when using the top-level `Makefile`
