### ISSUE TITLE
Remove -lrt when building on Linux

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#533]
Linking with librt doesn't appear to be necessary anymore with recent Linux distributions. We could  risk removing it for 3.7.3 but keeping it doesn't really hurt either so I suggest that we remove it for 4.0 to be on the safe side.

**Comment by Lastique** [comment]
Note that librt is not a dummy library on Linux, it implements some frequently used functions, like `clock_*` family of functions. Unless you're actually not using POSIX Realtime extensions, you should not remove linking with librt.

**Comment by bentoi** [comment]
Yes, we'll only remove it if it's safe to remove 😃. We do use `clock_gettime` but my understanding is that these functions have been moved to the libc library a while ago, see https://sourceware.org/ml/libc-announce/2012/msg00001.html

**Comment by Lastique** [comment]
Although glibc is the most widespread libc in Linux systems, it's not the only one. I'm not sure how compatible ZeroC ICE is with other libc implementations, or whether they also allow to omit -lrt for `clock_gettime`, but doing so wouldn't be portable.

Given that you need pthreads anyway, I don't see the reason for omitting -lrt.
