### ISSUE TITLE
Ice multi-network card problem

### ISSUE THREAD

**Issue by wei804378140** [zeroc-ice/ice#543]
The server deploying ice has two network cards, one of which is used to access the external network. Sometimes when calling ice, the network card accessing the external network will go out of time. What is the solution?

**Comment by wei804378140** [comment]
#

**Comment by bentoi** [comment]
Can you provide more information on the problem? Some network tracing (enabled with `--Ice.Trace.Network=2`) showing the unexpected behavior could help to better understand your issue.

**Comment by wei804378140** [comment]
![image](https://user-images.githubusercontent.com/7237900/65317482-80abcf00-dbce-11e9-8405-887a07f951b1.png)

The red circle IP is the server's external network ip. If the request accessed through this IP is called, it will be timed out. Is there any way to get rid of this ip?
