### ISSUE TITLE
js(javascript) to build an ice server?

### ISSUE THREAD

**Issue by HarrisonSun1997** [zeroc-ice/ice#545]
At first, I used ice3.6 and c++ to develop the server, but now js is needed to build the server due to the simplified business. However, I have browsed ice3.5, ice3.6 and ice3.7, and it seems that no demo built by js can be found.Can js be used to build the server side of a service?

**Comment by bernardnormier** [comment]
Ice for JavaScript provides only limited "server-side" support through bi-directional connections: an Ice for JavaScript application cannot accept incoming connections.

So you should pick a programming language with full server-side support for your server, such as C++, C#, Java, Python or Swift.

**Comment by HarrisonSun1997** [comment]
> Ice for JavaScript通过双向连接仅提供有限的“服务器端”支持：Ice for JavaScript应用程序不能接受传入的连接。
> 
> 因此，您应该选择一种对服务器具有完全服务器端支持的编程语言，例如C ++，C＃，Java，Python或Swift。

I see. Thank you for your answer.
