### ISSUE TITLE
Windows 10 Chrome testing  Ice/defaultValue failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#554]
```
*** [7/28] Running js/Ice/defaultValue tests ***
[ running client test - 09/25/19 04:07:10 ]
- Config: Chrome,Debug,x64
controller clientConsole value:
unexpected exception while connecting to process controller registry:
::Ice::ConnectTimeoutException

browser log:

[{'level': 'SEVERE', 
'message': "http://127.0.0.1:8080/lib/Ice.js 19775 WebSocket 
   connection to 'ws://127.0.0.1:12011/'  failed: Error in connection 
    establishment: net::ERR_CONNECTION_REFUSED", 
'source': 'javascript', 
'timestamp': 1569384204141},
```

**Comment by pepone** [comment]
I cannot reproduce it, lets reopen if it shows up again

**Comment by bernardnormier** [comment]
Same failure again with the latest CI build.

**Comment by pepone** [comment]
This seems a problem with Chrome `77.0.3865.90 ` after running binding tests connection establishment is too slow, seems this version of chrome adds a delay to connection establishment after the failures caused in this test (they are expected).

As workaround running with `--all` were test suite alternate ws/wss endpoints seems to get things working.
