### ISSUE TITLE
xcode11 error: 'StreamTransceiver.h' file not found

### ISSUE THREAD

**Issue by chee1986** [zeroc-ice/ice#562]
xcode11 ios13.0 build error: 'StreamTransceiver.h' file not found 
tag: 3.7.3-beta.2+spm

**Comment by chee1986** [comment]
using xcode11's SPM

**Comment by chee1986** [comment]
after add above file by myself, the build says:
duplicate symbol '_createIceTCP' in:
    /Users/chenpei/Library/Developer/Xcode/DerivedData/TraceGo9102-fljlpylngctgpveaktkzyxdagaki/Build/Intermediates.noindex/Ice.build/Debug-iphonesimulator/IceCpp.build/Objects-normal/x86_64/StreamEndpointI.o
    /Users/chenpei/Library/Developer/Xcode/DerivedData/TraceGo9102-fljlpylngctgpveaktkzyxdagaki/Build/Intermediates.noindex/Ice.build/Debug-iphonesimulator/IceCpp.build/Objects-normal/x86_64/TcpEndpointI.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pepone** [comment]
Hi,

Can you provide the output of `swift build -v` for the original error, it shouldn't be necessary to update any files, I just verify that our[ SPM demo](https://github.com/zeroc-ice/ice-demos/tree/swift/swift/Manual/spm/printer) works fine with Xcode 11, I just have to make a minor update to the [Package.swift ](https://github.com/zeroc-ice/ice-demos/commit/ff454894313591d27b384ee727ea88b2810b0be6)to pick the exact version. 

By the way do you get this errors building Ice demos or building your own package, in the later case will be interesting to see your Package.swift file.

Cheers,
Jose

**Comment by chee1986** [comment]
I have build your SPM demo ,it's work fine.Maybe,my problems is :I am developing a swiftui app which running on IOS13 & MacOS Catalina. For that case ,i create a empty project in xcode11,just add the PromiseKit & ice dependencies using the xcode11‘s default gui tools,then the build system still report the error above.

**Comment by pepone** [comment]
I was able to reproduce the issue, we will upload a new version that is compatible with iOS builds.

**Comment by chee1986** [comment]
Thank you!

**Comment by pepone** [comment]
Hey chee,

 can you test with 3.7.3-beta.3+spm from  https://github.com/pepone/ice.git

I was able to build Swift UI project targeting in iOS, the fixes will be included in the upcoming 3.7.3 release.
