### ISSUE TITLE
iOS C++/Objective-C test controller doesn't respond to IceDiscovery on Catalina

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#564]
For some reasons the controller is often not responding to multicast discovery request after being launched the first time by `./allTests.py`. 

We added some retry to give it more time to be fully started by it doesn't help. When the retries are finally exhausted and the test fails, the next test restarts the controller and this time it works, the controller responds to the discovery requests almost immediately.

**Comment by bernardnormier** [comment]
I tried with the latest catalina VM (catalina-dev) for the Objective-C iphonesimulator test suite, and it worked fine.

I installed Ice for Python with pip: zeroc-ice version 3.7.2.

**Comment by externl** [comment]
Could it have been a bug with the old Catalina beta?

**Comment by bernardnormier** [comment]
Appears to work with the most recent Catalina vm
