### ISSUE TITLE
Yocto build should use the bitbake native/nativesdk compiler instead of g++ in PATH

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#566]
While building for Yocto 2.7 (warrior) I got this error:

```
| make[1]: *** [src/Slice/build/x86_64-build/static/CPlusPlusUtil.o] Error 1
| g++: error: unrecognized command line option '-fmacro-prefix-map=/home/vagrant/workspace/fsl-community-bsp/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/zeroc-ice/3.7.3+gitAUTOINC+cf67902d2c-r0=/usr/src/debug/zeroc-ice/3.7.3+gitAUTOINC+cf67902d2c-r0'
| Makefile:25: recipe for target 'src/Slice/build/x86_64-build/static/JavaUtil.o' failed
| make[1]: *** [src/Slice/build/x86_64-build/static/JavaUtil.o] Error 1
| make[1]: Leaving directory '/home/vagrant/workspace/fsl-community-bsp/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/zeroc-ice/3.7.3+gitAUTOINC+cf67902d2c-r0/git/cpp'
| Makefile:18: recipe for target 'srcs' failed
| make: *** [srcs] Error 1
| ERROR: oe_runmake failed
```

The issue is that when building for arm we first do a build of the slice compilers for x86_64 using the system's g++ compiler. Unfortunately the version on my system (7.4) does not support some of the flags set by `CXXFLAGS` (note this are also for ARM, not x64). 

The correct thing to do is do what we did for Ice 3.6 which is bootstrap the target (ARM in this case) build by building the native/nativesdk builds, then use those slice compilers.

See https://github.com/zeroc-ice/meta-zeroc/blob/fido/recipes-core/zeroc-ice/zeroc-ice_3.6.3.bb#L10

**Comment by bentoi** [comment]
I don't know how this works exactly but... would it help if I add support for ICE_BIN_DIST=translators to allow building the C++ sources using translators from another Ice installation?

**Comment by pepone** [comment]
Yes that will do, how we will set the location of this BIN_DIST, just setting ICE_HOME?

**Comment by bernardnormier** [comment]
We should use "slice compilers" consistently, and eliminate references to "translators".

**Comment by pepone** [comment]
Sounds fine to me with IceE we use to do `ICE_HOME=${STAGING_DIR_NATIVE}/usr` and this picket the Slice compilers build for the Yocto Host.

**Comment by pepone** [comment]
https://github.com/zeroc-ice/meta-zeroc/commit/8169d4a1e76d9a4198606ca422b1f3fbe7ad2b42
