### ISSUE TITLE
Remove cpp98 mapping

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#567]
- [x] remove Ice for Ruby
- [x] clone the cpp "core" into cpp98 and update the build of cpp98-based language mappings (Python, PHP) to use cpp98
- [x] remove IcePatch2
- [ ] in cpp: port all services (IceGrid, IceStorm etc.) and associated tests to use ICE_CPP11_MAPPING
- [ ] in cpp: update slice2cpp to generate code only for the C++11 mapping, and remove all use of ICE_CPP11_MAPPING 
- [ ] in cpp: replace all use of IceUtil::Thread, Mutex, Monitor by equivalent standard thread, mutex etc.
- [ ] port Ice for Python and Ice for PHP to the latest C++ mapping
- [ ] remove cpp98

**Comment by pepone** [comment]
Wondering it will be simpler to create a C++11 branch, and then:
* update slice2cpp to generate code only for the C++11 mapping, and remove all use of ICE_CPP11_MAPPING
* port all services (IceGrid, IceStorm etc.) and associated tests to use C++11 mapping, removing all uses  ICE_CPP11_MAPPING macros
* port Ice for Python and Ice for PHP to the latest C++ mapping
* merge back to master

I don't see the benefice of creating a temporary cpp98

**Comment by bernardnormier** [comment]
I anticipate this step:
- [ ] port Ice for Python and Ice for PHP to the latest C++ mapping

won't start soon, as we want to refine the C++ API before starting it. Furthermore, the "port" of Ice for Python and Ice for PHP to the latest C++ will itself take a significant time as we plan to refactor these C++-based mappings to be more like Ice for Swift.

**Comment by bernardnormier** [comment]
We decided to keep the c++98 mapping and un-deprecate it.
