### ISSUE TITLE
Ice 3.6.5 missing in https://github.com/zeroc-ice/ice/releases

### ISSUE THREAD

**Issue by grembo** [zeroc-ice/ice#576]
Would be great if you could tell github that 3.6.5 was released (beyond just tagging it), so it shows up in https://api.github.com/repos/zeroc-ice/ice/releases.

Thanks!

**Comment by pepone** [comment]
Hi @grembo 

Thanks for pointing this out, I just updated the releases to include 3.6.5

Cheers,
José

**Comment by grembo** [comment]
3.6.5 shows up as latest release now:
https://api.github.com/repos/zeroc-ice/ice/releases/latest

Shouldn't this still show 3.7.2?

**Comment by pepone** [comment]
```The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.```

https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by grembo** [comment]
> `The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.`
> 
> https://developer.github.com/v3/repos/releases/#get-the-latest-release

Okay, good to know. I'm currently looking into how freebsd/portscout determines the latest release and clearly that model won't work well in case there are multiple major releases maintained in parallel. Thanks!
