### ISSUE TITLE
Swift dispatch and invocation leaks

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#579]
The Objective-C code assumes that the Objective-C -> Swift bridging doesn't autorelease objects on the autorelease pool. 

This is not correct as we discovered while tracking the leak caused by NSData objects created for dispatch and invocations using initWithNoCopy. These objects ends up accumulating on the dispatch queue autorelease pool (see #578).

We should fix the Swift mapping Objective-C code to use auto release pools when calling into Swift code.

**Comment by externl** [comment]
I have the ObjC -> Swift parts of this complete locally. The places I found where we call user code from ObjC directly into Swift are:
1. the dispatch calls, 
2. heartbeat/close callbacks
3. sent callbacks

One thing I'm not sure about is how (if we even should) handle PromiseKit continuations which may occur on one of our DispatchQueue threads.

For example, https://github.com/zeroc-ice/ice/blob/3.7/swift/src/Ice/Proxy.swift#L636

Resolving or rejecting this seal might (or might not) be continued in the client thread pool thread (by passing nil). If the continuation creates an autoreleased object without a autorelease pool it may never get cleaned up.

We return lots of Promises, is it realistic for use to wrap all `seal.fufill` and `seal.reject` calls in `autocomplete` blocks? Do we want to do this? As far as I can tell this is an issue that PromiseKit ignores and leaves it up to the user.

**Comment by bernardnormier** [comment]
I would add these autorelease pools in the ObjC++ code, e.g. here:
https://github.com/zeroc-ice/ice/blob/3.7/swift/src/IceImpl/ObjectPrx.mm#L699

**Comment by bentoi** [comment]
The Objective-C mapping also adds autorelease pools for the logger calls (C++ -> Swift custom logger) in case the user logger implementation potentially adds autoreleased objects on the pool.
