### ISSUE TITLE
Improve OutgoingAsync to no longer throw exception_ptr

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#582]
The response callback from the generated can raise `current_exception()`. See also https://github.com/zeroc-ice/ice/blob/ed5621a53508274aad76a555e3df1f6ee42e089a/cpp/include/Ice/OutgoingAsync.h#L484 

It would be better to return the exception_ptr from the function instead.

**Comment by bernardnormier** [comment]
Fixed in 3.8.
