### ISSUE TITLE
Provide new Glacier2 helpers

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#59]
The Glacier2 helper class derives from `Ice::Application`, which is now essentially deprecated, and replaced by built-in language constructs (`CommunicatorHolder` and `CtrlCHandler` in C++).

We should provide Glacier2 helpers that don't depend on `Ice::Application`.

ICE-8688

**Comment by bentoi** [comment]
See also ICE-4486

**Comment by pepone** [comment]
We already provide non application helpers with [Glacier2::SessionHelper](https://doc.zeroc.com/api/ice/3.7/cpp11/classGlacier2_1_1SessionHelper.html)
