### ISSUE TITLE
IceGrid GUI fails to load with Java 13 on macOS Catalina

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#593]
The GUI doesn't load with Java 13 with the following error:
<img width="532" alt="Screen Shot 2019-10-17 at 11 40 31 AM" src="https://user-images.githubusercontent.com/2126835/67024777-f96d5080-f0d2-11e9-880c-878ac79fae91.png">

Trying to run the launcher manually results in:

```
❯ IceGrid\ GUI.app/Contents/MacOS/JavaAppLauncher --help
2019-10-17 11:25:18.307 JavaAppLauncher[55149:596767] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) Searching for a JRE.
2019-10-17 11:25:18.307 JavaAppLauncher[55149:596767] NSString *findJREDylib(int, _Bool, _Bool) JRE search exception: 'launch path not accessible'
2019-10-17 11:25:18.374 JavaAppLauncher[55149:596767] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) No matching JRE or JDK found.
2019-10-17 11:25:18.374 JavaAppLauncher[55149:596767] int launch(char *, int, char **) Launchpath: (null)
2019-10-17 11:25:18.376 JavaAppLauncher[55149:596767] int launch(char *, int, char **) Error launching JVM Runtime ((null)) Relative Path: '(null)' (dylib: (null))
  error: JRELoadError
```

Running the jar manually works `java -jar icegridgui.jar`

**Comment by externl** [comment]
I'm also setting this error with other Java apps, such as [JOSM](https://josm.openstreetmap.de). Looks to be an issue with the app bundler`com.panayotis:appbundler`.

**Comment by externl** [comment]
As of Java 14, Java includes an java app packaging tool, `jpackage`. We should probably switch to this tool once it's included in an LTS release (according to wikipedia this will be in 2021).

For now we should look for an updated app bundler that works with Java >= 13

**Comment by externl** [comment]
I have the build fixed to work with the incubating feature `jpackage` from Java 14. Should we error if Java > 14 is not installed or just skip building the app?

**Comment by pepone** [comment]
Whatever its simpler,  maybe remove the app from the default target, and fail if trying to build the app with Java < 14?

**Comment by externl** [comment]
Right now we like doing the build with the Java 11 LTS release.  Currently what I do is just search for a Java 14+ JDK and use the its `jpackage` command. That way we can still build with the LTS and just use Java 14+ for `jpackage`.

Currently my idea is to just skip creating the app, no error.

I'm not against also just switching to Java 14+ for the build in general.

**Comment by pepone** [comment]
To keep things simple we can remove the creation of the bundle from the gradle build, we will build just the regular or proguard JAR.

The bundle can be created as a separate step for the brew upload

**Comment by externl** [comment]
Ok, let's do that for now then.
