### ISSUE TITLE
IceGrid GUI warning on first launch on macOS

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#594]
The following warning appears on first launch on the GUI on macOS <img width="789" alt="Screen Shot 2019-10-17 at 11 36 46 AM" src="https://user-images.githubusercontent.com/2126835/67024644-bf03b380-f0d2-11e9-892e-62e0877bf668.png">

**Comment by pepone** [comment]
This was related to the appbundler used with 3.7.3, 3.7.4 will use jpackage
