### ISSUE TITLE
Allow AMD and non-AMD servants to be generated

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#60]
Right now, it's not possible to generate both an AMD and non-AMD version of the same servant. This is problematic for "callback" interfaces that are supposed to be implemented by users.

Take for example the `Glacier2::PermissionsVerifier` interface. We currently only ship a non-AMD servant in our libraries. It's not ideal because the user might very well want to implement this with AMD if the implementation needs to be async (it might need to send an HTTP request to a 3rd party for verification... such as Apple/Sony servers in case of a game).

Proposed solution:
--------------------
When the user specifies ["+amd"] in front an interface, we generate 2 servant base classes:

- the regular base class, that takes into account ["amd"] metadata data in front of operations (so it can get a mix of AMD and non-AMD operation implementations)
- a second base class named XxxAsync with all operations mapped to AMD
- regarding inheritance, an Async class would inherit from other Async class when available (meaning the base interfaces have also +amd); otherwise it derives from the regular non-Async C++ classes/Java interfaces etc.
The various OperationResult structs would stay only in the main servant base class - no duplication.

These two base classes are independent, and the user chooses which one to derive from. This is basically what we already do for Blobject, with Blobject and BlobjectAsync.

This would deal properly with the following scenario:

1. I want a mix of amd and non-amd operation on my servant implementation (has always worked)
2.  I need to implement one or more operation as amd, but the library with the servant base class did not generate them as amd => I regenerate with ["+amd"] added (small downside: I need to implement all operations as amd)
4. a library wants to provide both amd and non-amd base classes for the same interface (it uses ["+amd"] in front of the interface)

ICE-5516

**Comment by pepone** [comment]
I think that a solution where sync is implemented in terms of async gives more flexibility and avoid the needs for the metadata

```
// Base servant class provide a default not implemented sync version
// and an async version that forwards the call to the sync version, 
// Ice run-time always dispatch to the async version
class ShopingCart
{
    virtual bool addProduct(int id)
    {
        throw NotImplementedException();
    }

    virtual future<bool>
    addProductAsync(int id)
    {
        promise<bool> result;
        try
        {
            result.set_value(addProduct());
        }
        catch(...)
        {
            result.set_exception(current_exception());
        }
        return result.get_future();
    }
};

// The user can decide to implement a method as sync or async and 
// no need to change metadata
class ShopingCartI
{
    virtual bool addProduct(int id, const Ice::Current&)
    {
        return true;
    }
};

class ShopingCartAsyncI
{
    virtual future<bool>
    addProductAsync(int id)
    {
        ....
    }
};
```

The solution provides more flexibility as users can decide to reimplemt a method as synchrons or asynchronous without requiring to change the Slice metadata, that is interesting when the generated code is provided as a library mixed with non generated code.

The major downside I see for this solution is the extra async call for synchronous dispatch

**Comment by bentoi** [comment]
Another idea for this issue could be to improve the code generation by allowing generating multiple servant versions.
```
["servant[AsyncPermissionsVerifier]:amd"] interface PermissionsVerifier
{
    ["nonmutating", "cpp:const", "format:sliced"]
    idempotent bool checkPermissions(string userId, string password, out string reason)
        throws PermissionDeniedException;
}
```
The above would generate the default servant `PermissionsVerifier` and another `AsyncPermissionsVerifier` (generated with the "amd" metadata). This metadata could be allowed at the operation level as well.

We could also eventually support generating only a specific servant version out a set of Slice files (using a slice compiler option `--generate "::Glacier2::PermissionsVerifier#servant[HelloAsync]"`). 

We could extend this mechanism to proxy generation as well to allow for example generating a different proxy class/interface with multiple operations for a same slice operation but with different custom types.
