### ISSUE TITLE
Incorrect uses of empty() instead of clear()

### ISSUE THREAD

**Issue by Lastique** [zeroc-ice/ice#605]
gcc-9 in C++17 mode shows a few errors about result of `empty()` being unused. In these instances, it seems `clear()` should have been called instead of `empty()`.

I showed the suggested fix in https://github.com/zeroc-ice/ice/pull/604.

**Comment by Lastique** [comment]
Note that this is a bug, so it should probably be fixed in the 3.7 branch as well.

**Comment by externl** [comment]
This was fixed in 28aaa71beb3cce13cec366528ba19413269219b8
