### ISSUE TITLE
Remove __SUNPRO_CC C++ support

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#608]
The ifdef macros to support  `__SUNPRO_CC` can be removed, we will no longer support this compiler.

**Comment by bernardnormier** [comment]
Same for `__ibmxl__`, `__IBMCPP__` and  `__MINGW32__` on the master branch.

**Comment by pepone** [comment]
We should also review `_MSC_VER` checks with 4.x we only need to support `1910` or greater, so we can get rid of code that is only to support earlier versions
