### ISSUE TITLE
Rework test util Application

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#62]
(From @bentoi)

Our tests need some helpers to:
- hide differences between platforms (Java CLI vs Android, C++ CLI vs iOS vs UWP, etc).
  - output should either go to stdout, be buffered, go to a GUI
  - the server readiness logic is different between a CLI server and a server bundled into a shared library started by a GUI
- reduce the boilerplate code needed for setting up the communicator, parsing properties, etc.

Right now, we have an application class for the following language mappings:
- Java/Java-Compat: test.util.Application (most likely introduced with the Android support)
- C#: TestCommon.Application (I believe it was introduced with the Silverlight support)

For C++/Objective-C, we use a number of functions and macros from TestCommon.h to help with the communicator initialization and the "wait/ready" logic required for the driver to wait for server readiness. Many of these were introduced for the iOS / UWP support.

For Python, Ruby, PHP we don't use any helpers.

For JavaScript, clients/servers do follow a number of conventions (they export some variables such as _test, _server, _clientAllTests, _runServer... which are used by the test controller / runner to start the client or server).

Obviously, we didn't pay much attention to consistency across mappings for the test helpers .

Python/Ruby/PHP and JavaScript don't support being run concurrently with other tests because they don't support the --Test.BasePort property which allows to specify the base port that the client or server should use. Adding support for this would be good and some helpers could be useful to more easily get test endpoints, ports, etc.

So if we want to revisit this for tests, I see two options:
1.  get rid of the application class and replace it with some other helper(s)
2.  embrace the test application class and port/use it consistently with all the mappings

I'm not a big fan of classes with static methods and static data members... I'd rather keep an application class which can easily be instantiated to run a client or server.

ICE-8531

**Comment by pepone** [comment]
Implemented TestHelper in all language mappings excluding Objective-C
