### ISSUE TITLE
Refactor slice2matlab CodeVisitor

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#625]
I think we should refactor the MATLAB CodeVisitor probably split it in serveral visitor for proxies/values/etc

For example https://github.com/zeroc-ice/ice/blob/f858d073b76e0fa040382f4a3d5b3fec343f691e/cpp/src/slice2matlab/Main.cpp#L1614

That methods deals with all generate code for proxies/values and operations, should be simpler to maintain if we use separate visitors.

**Comment by bernardnormier** [comment]
The only example is no longer applicable.
