### ISSUE TITLE
cannot install zeroc-ice3.7 in Centos 7 

### ISSUE THREAD

**Issue by kangkangv5** [zeroc-ice/ice#640]
my server version is
 cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

and I try to install icegrid,
it all bad done, error infos are:
------
Error: Package:libicestorm3.7-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package:icegrid-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libssl.so.1.1(OPENSSL_1_1_0)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libcrypt.so.1(XCRYPT_2.0)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package:icegrid-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package:ice-utils-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package:icegrid-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package:ice-utils-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package:libicestorm3.7-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package:libicestorm3.7-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libcrypto.so.1.1(OPENSSL_1_1_0)(64bit)
Error: Package:ice-utils-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.11)(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libcrypto.so.1.1()(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libssl.so.1.1()(64bit)
Error: Package:libice3.7-c++-3.7.3-1.el8.x86_64 (zeroc-ice3.7)
          requires：libstdc++.so.6(CXXABI_1.3.8)(64bit)

-------

it must be dependent on el8 ?
but I install it by using
sudo yum install https://zeroc.com/download/ice/3.7/el7/ice-repo-3.7.el7.noarch.rpm

**Comment by bentoi** [comment]
I can't reproduce. Can you try the following:
```
$ sudo rpm -e ice-repo
<ensure there's no ZeroC repository file in the /etc/yum.repos.d directory>
$ yum install https://zeroc.com/download/ice/3.7/el7/ice-repo-3.7.el7.noarch.rpm
```
And then check that the installed `/etc/yum.repos.d/zeroc-ice3.7.repo` file correctly points to the EL7 repository?

**Comment by kangkangv5** [comment]
oh yes , it's my fault . sorry for the trouble
