### ISSUE TITLE
When did you support golang?

### ISSUE THREAD

**Issue by zhanlanghun** [zeroc-ice/ice#67]
I think ice is very good, we are using it, but when do we support golang?

**Comment by bernardnormier** [comment]
Ice provides many language mappings, but presently no Ice for Go mapping. I believe creating an Ice for Go is doable ... it just depends on customer demand. For example, we recently added [Ice for MATLAB](https://zeroc.com/downloads/ice#matlab) with the support of ETAS GmbH.
