### ISSUE TITLE
Ice.ThreadPool.Client.SizeMax  parameters are not in effect

### ISSUE THREAD

**Issue by wei804378140** [zeroc-ice/ice#670]
Ice1.ThreadPool.Client.Size=20
Ice1.ThreadPool.Client.SizeMax=200

Do these two parameters take effect on the client?It doesn't seem to increase the number of threads at this point.

**Comment by bentoi** [comment]
You shouldn't use the Ice1 prefix but just use Ice instead:
```
Ice.ThreadPool.Client.Size=20
Ice.ThreadPool.Client.SizeMax=200
```

**Comment by wei804378140** [comment]
Sorry, that's wrong, that's this argument, this is under what conditions does it add threads。

Ice.ThreadPool.Client.Size=20
Ice.ThreadPool.Client.SizeMax=200

**Comment by bentoi** [comment]
Yes, it does add thread to the client thread pool. You can check it out by attaching to the process with a debugger. Is adding threads to the client thread pool what you are looking for however? This is mostly useful to increase the number of asynchronous reply callbacks that can be executed in parallel.

If you are looking into increasing the number of threads in an Ice server for servant dispatch, you should instead use the properties prefixed with `Ice.ThreadPool.Server`.

See [the Ice documentation on thread pools](https://doc.zeroc.com/ice/3.7/client-server-features/the-ice-threading-model) for additional information on this.

**Comment by wei804378140** [comment]
Now we have encountered a problem. When the message size exceeds the client's 1M limit, the call timeout will be reported. At that time, the server's memory, CPU, and GC were normal. Now it is suspected that the number of client threads is not enough, but Ice.ThreadPool .Client.SizeMax parameter added feels not working

**Comment by bentoi** [comment]
I'm not sure I understand your problem. If the client receives a reply that exceeds [the Ice.MessageSizeMax limit](https://doc.zeroc.com/ice/3.7/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.7-Ice.MessageSizeMax) it should raise `Ice.MemoryLimitException` and close the connection. Isn't this what you're observing?

**Comment by wei804378140** [comment]
Two exceptions will be reported during this time, Ice.MemoryLimitException and
![image](https://user-images.githubusercontent.com/7237900/71248132-1cc3ae80-2355-11ea-9ff1-df8a6fd6ffc9.png)

**Comment by wei804378140** [comment]
If it exceeds the limit, it should only report Ice.MemoryLimitException, but there will be 
![image](https://user-images.githubusercontent.com/7237900/71248278-6ad8b200-2355-11ea-8bdd-d095ebb34da6.png)

**Comment by bentoi** [comment]
Can you post the trace of `Ice.MemoryLimitException`? 

The `Ice.InvocationTimeoutException` indicates that the invocation timed-out. Is the invocation retried after failing the first time with `Ice.MemoryLimitException`? 

Try enabling network, protocol and retry tracing to observe what the Ice runtime is doing for this invocation:
```
Ice.Trace.Network=2
Ice.Trace.Retry=1
Ice.Trace.Protocol=1
```
