### ISSUE TITLE
At present, after the number of server threads exceeds the maximum, processing is delayed, Can it be set to not delay processing?

### ISSUE THREAD

**Issue by wei804378140** [zeroc-ice/ice#673]
At present, after the number of server threads exceeds the maximum, processing is delayed, Can it be set to not delay processing? Or set to something else

**Comment by bentoi** [comment]
No it's not possible to change Ice's behavior when all the threads from the thread pool are busy dispatching incoming invocations or AMI callbacks. When this occurs, Ice stops reading data from the connections associated with the thread pool (an in general this cause the client to stop sending more data thanks to the transport flow control mechanism).

What alternative behavior would you prefer?

If you need more advanced thread pool scheduling, one option is to use [Ice blobjects](https://doc.zeroc.com/ice/3.7/client-server-features/dynamic-ice/dynamic-invocation-and-dispatch/dynamic-invocation-and-dispatch-overview) to queue incoming invocations and dispatch them with a custom thread pool that you would implement. This way, the Ice thread pool never blocks but just continues to queue incoming requests on your thread pool's queue (which can eventually decide to reject queuing new incoming requests).

**Comment by wei804378140** [comment]
When the server thread is full, can I disconnect the client connection and switch to another service?

**Comment by bentoi** [comment]
Disconnecting the client connection could be problematic if the client has other requests being processed by the same server, these requests would fail and potentially trigger a retry.

Can you describe your use case a little more and the problem you are trying to solve? 

If your application consist of a client-server app where a client invokes long running operations on servers and where each server should only dispatch a limited number of concurrent operations, the easiest is probably to implement your own strategy for scheduling these long running jobs on servers. One possibility could be to use [IceGrid allocation mechanism](https://doc.zeroc.com/ice/3.7/ice-services/icegrid/resource-allocation-using-icegrid-sessions).
