### ISSUE TITLE
Ice.SocketException running JavaScript test suite

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#68]
On Windows when run the JavaScript test suite with `--browser Firefox` geckodriver.exe keeps running after the tests finish and a second attempt to run the test suite will fail with `Ice.SocketException`

Environment:
 - selenium-gecko-driver 0.20.1
 - Firefox 59.0.2
 - Windows 10

**Comment by pepone** [comment]
Fixing the `PATH` solves the problem

**Comment by bentoi** [comment]
Ok, it's an environment issue. I reported the issue on the selenium-geckodriver chocolatey page.
