### ISSUE TITLE
IceDiscovery missing documentation comments

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#697]
https://github.com/zeroc-ice/ice/blob/75c59c888363c2f5d54c923a8035e9c9335e40cd/slice/IceDiscovery/IceDiscovery.ice#L27

The missing comments cause warnings in the generated proxy code at least in C#, will be good to add comments here

**Comment by bernardnormier** [comment]
Note that the Slice definitions for both IceDiscovery and IceLocatorDiscovery are internal to these plugins, and neither plugin provides a public API. We can nevertheless add documentation comments to avoid warnings in the generated code.
