### ISSUE TITLE
icestorm bug

### ISSUE THREAD

**Issue by jinyuttt** [zeroc-ice/ice#713]
When icestorm is started through windows service, some clients will not receive the data

**Comment by bernardnormier** [comment]
Could you be more specific?

For example, is this a problem you can reproduce with an IceStorm demo? Which version of Ice are you using?

Best regards,
Bernard

**Comment by jinyuttt** [comment]
Windows Server 2012,When the system starts, there is a service startup, which is used to start icestorm. After running for a period of time, some clients can't receive data. We will reproduce it here, but it will run for a period of time, which is accidental.
ice3.7

**Comment by bentoi** [comment]
Did you manage this reproduce the issue? If you still have the problem, please re-open this bug.
