### ISSUE TITLE
oneway operation metadata

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#747]
Proposal: add a new oneway operation metadata or keyword. An operation with this metadata/keyword would be sent oneway (i.e. no response) even when called on a proxy with an invocation mode set to two-way.

With this enhancement, most applications would not need to create oneway proxies, even if they make oneway calls.

Related PR: https://github.com/zeroc-ice/ice/pull/746

Re: metadata vs keyword, in practice it would be very similar to idempotent (a keyword) - a bool/enum sent with each invocation. The main difference is idempotent expresses a guarantee given by the server, and the server verifies the client does not incorrectly believe a non-idempotent operation is idempotent (i.e. there is an idempotent mismatch in the client and server Slice definitions). For oneway, the server implementation should usually behave the same for oneway and twoway calls, or can easily support both invocation modes; a mismatch between the client and server definitions would not break anything. So I think metadata is more appropriate for oneway.

**Comment by pepone** [comment]
I don't think that is a practical solution to harcode in Slice than an operation can only be call as oneway.

A alternative will be to add a oneway optional parameter that allows to override the proxy invocation mode, but I'm not convinced that we need an alternate , creating a oneway proxy seems good enough to me.

**Comment by bernardnormier** [comment]
On the contrary, I think it's very practical and common. Most of time, it's a design decision whether an operation should be called oneway all the time as opposed to the default (twoway). So you can express this decision in your Slice with this oneway metadata, and no matter the proxy you use, this operation will be called oneway.

Now, in the rare situation where your client applications call an operation sometimes oneway and sometimes twoway, you don't use any metadata and you get oneway or twoway behavior based on the type of proxy you use. That's the Ice behavior in Ice 3.7 and earlier.

With this metadata, many - arguably most - applications won't need oneway proxies. They can just use the default twoway proxies for everything and still get oneway semantics for operation marked oneway.

**Comment by InsertCreativityHere** [comment]
This was added into the C# mapping in #811, but still needs to be done in the other mappings.
