### ISSUE TITLE
ICE3.5.1 Ice::FileException: file exception: Permission denied IN VMWARE

### ISSUE THREAD

**Issue by tongbenchuan** [zeroc-ice/ice#768]
I test my grid config in real centos everything is ok, but when i deploy them to a virtual machine with centos , ifstream seems not worked, there is the exception in the log:
icegridnode: Activator: activating server `1.Glacier2'
glacier2router: error: createProperties failed: PropertiesI.cpp:407: Ice::FileException:
file exception: Permission denied
path: /root/trunk/grid/node/servers/1.Glacier2/config/config

i had give chmod 777 -R ./  to all grid config files but still errored!
chown used too, but still on.

i try just test ifstream with my test code  on vmware is ok
code:
#include <iostream>
#include <istream>
#include <fstream>

using namespace std;

typedef std::string String;

void loadDirect(const String& filename)
{
	
	std::ifstream fp;
	fp.open(filename.c_str(), std::ios::in);
	cout<<fp.rdbuf();
	fp.clear();
	if(!fp)
	{
		cout<<"failed";
	}
	
	
}

int main()
{
	cout<<"Hello\n";
	loadDirect("/root/trunk/grid/node/servers/1.Glacier2/config/config");
	return 0;
}

how can i fix it? thanks

**Comment by bernardnormier** [comment]
Ice 3.5.1 is pretty old, you should upgrade.

When you execute `icegridnode` as `root`, the servers are by default started using `nobody`. See `user` at https://doc.zeroc.com/ice/3.7/ice-services/icegrid/icegrid-xml-reference/server-descriptor-element

**Comment by tongbenchuan** [comment]
thank you，it work fine now ！i add a new user for my grid ，
i have a puzzle，why i also use root in my local machine with centos everything is ok
but in virtual machine like vmware it not work？
