### ISSUE TITLE
Add JavaScript test for escaped names

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#77]
From http://www.zeroc.com/forums/help-center/6351-ice-javascript-compiling-murmur-ice-errors.html

We fixed this in https://github.com/zeroc-ice/ice/commit/f6c47535e2270ac3bf297f5cadc84ef292293c24 but did not add any tests. We should add a test somewhere to ensure invocations with escaped names correctly work at runtime as well.

See ICE-6072

**Comment by pepone** [comment]
This was already fix and test in `Slice/escape` test
