### ISSUE TITLE
what should i do if i donot want to install test files? 

### ISSUE THREAD

**Issue by luoshuxiao** [zeroc-ice/ice#772]
dont want to install test files

**Comment by bentoi** [comment]
Can you be more specific? Are you building Ice from source or installing it from one of our binary packages? On which platform and which test files in particular?

On Unix platforms, running "make install" doesn't install test files.

**Comment by luoshuxiao** [comment]
Thanks a lot, bro.After reading the source code, I found the way to solve this problem,Just comment out the code about test in Makefile and Make.rules.

**Comment by luoshuxiao** [comment]
> Can you be more specific? Are you building Ice from source or installing it from one of our binary packages? On which platform and which test files in particular?
> 
> On Unix platforms, running "make install" doesn't install test files.



> Can you be more specific? Are you building Ice from source or installing it from one of our binary packages? On which platform and which test files in particular?
> 
> On Unix platforms, running "make install" doesn't install test files.

Thanks a lot, bro.After reading the source code, I found the way to solve this problem,Just comment out the code about test in Makefile and Make.rules.

**Comment by bentoi** [comment]
Ok in theory you shouldn't have to edit our Makefile if you use `make install` to install Ice.

**Comment by luoshuxiao** [comment]
I did but nothings has changed and saw a lot of test installations. After editing the Makefile and  Make.rules, it  worked. Anyway thank you very mach

**Comment by luoshuxiao** [comment]
I did but nothings has changed and saw a lot of test installations. After editing the Makefile and Make.rules, it worked. Anyway thank you very mach.

**Comment by luoshuxiao** [comment]
> Ok in theory you shouldn't have to edit our Makefile if you use `make install` to install Ice.

I did but nothings has changed and saw a lot of test installations. After editing the Makefile and Make.rules, it worked. Anyway thank you very mach

**Comment by luoshuxiao** [comment]
I did but nothings has changed and saw a lot of test installations. After editing the Makefile and Make.rules, it worked. Anyway thank you very mach.
