### ISSUE TITLE
Inline comments in slice file triggers a syntax error in Ice 4.0

### ISSUE THREAD

**Issue by dennsporcic** [zeroc-ice/ice#791]
Hi Team,
I'm testing with Ice 4.0 against my test codebase and have found that my slice files no longer compile.
I have found that inline comments now trigger a syntax error. 
Is this new going forward with Ice 4.0 ? or a regression ?

 **#pragma once
 module test { // c
    struct foo // c
    {
       int a; // this is an int
       int b; // this is an int  
    } // end struct
 } // end module**

**Comment by InsertCreativityHere** [comment]
Hey dennsporcic! If it's new it's definitely unintentional!

Can you give me a copy of the errors the compiler outputs, and let me know which compiler (slice2cpp, slice2cs,...) it is you're using?

I just tried compiling the code you wrote, and it worked fine for me with the most recent version of Ice. What's the commit ID of the version of Ice you're testing on?

**Comment by dennsporcic** [comment]
Hi,

My dev environment is 
macos 10.15
Apple clang version 11.0.3 (clang-1103.0.32.29)
Compiled from master branch
commit 9ec80f04fba72d854754298d47bf3df81622c397
Using slice2cpp 
Error is:
test.ice:4: syntax error

cheers

**Comment by pepone** [comment]
@dennsporcic how did you build mcpp, there is an old bug in mcpp that eats line with single line comment. If you are building mcpp from source the best is to use our fork in https://github.com/zeroc-ice/mcpp

**Comment by dennsporcic** [comment]
Thanks pepone, using https://github.com/zeroc-ice/mcpp now works :)
many thanks
