### ISSUE TITLE
why can't my vs2010 project compiled shows "LINK : fatal error LNK1104: cannot open file 'Ice37D.lib'"?

### ISSUE THREAD

**Issue by senses1** [zeroc-ice/ice#83]
I simply create a test project using vc++, dialog based. I add include file path to directory settings，it worked well.
but I put the libs of ice to a folder named "lib", whether I set the lib path or use"#pragma comment(lib,"../lib/win32/debug/ice37d.lib")"  ,there is always a link error,except I put all the lib files under the project dir.

But I use a dll written by my self , the method went well with the test project.

please help me with this problem, thanks a lot!!!

**Comment by pepone** [comment]
The recommended approach is to use Ice Visual Studio 2010 NuGet package [zeroc.ice.v100](https://www.nuget.org/packages/zeroc.ice.v100/) Installing the package to your project should be enough, header and library directories are automatically configure with the package.

You should also look into [zeroc.icebuilder.msbuild ](https://www.nuget.org/packages/zeroc.icebuilder.msbuild/) if you are not using it yet, the builder takes care of building Slice files, and will automatically detect the `zeroc.ice.v100` package and use the Slice compilers provided by it.

Note you never need to add `#pragma` comments to link with Ice libraries this is already handle by Ice headers on Windows.

**Comment by senses1** [comment]
@pepone thank you for your answer, but I still don't know how to use icebuilder. but I do know how to use slice tool.
another question is that I could not open the ice csharp project to compile the ice.dll, ether  using vs2010 or  vs2017. please help me again.
thanks.

**Comment by pepone** [comment]
Regarding icebuilder review the [README](https://github.com/zeroc-ice/ice-builder-msbuild/blob/master/README.md) everything is documented there.

With respect to build CSharp we document the process in the corresponding [README](https://github.com/zeroc-ice/ice/blob/3.7/csharp/README.md) file. There is also an binary package available [zeroc.ice.net](https://www.nuget.org/packages/zeroc.ice.net/) NuGet package.

**Comment by senses1** [comment]
thanks a lot. @pepone . I finally solved it under vs2017 and installed the .net core SDK 2.0 to compile the whole solution.
