### ISSUE TITLE
Successfully built but failed to install...

### ISSUE THREAD

**Issue by jiapei100** [zeroc-ice/ice#832]
**ENV**:
Ubuntu 18.04.4

During the installation, I got the following **ERROR** message:

```console
(Reading database ... 525775 files and directories currently installed.)
Preparing to unpack .../ice/ice_3.7.4-6_amd64.deb ...
Unpacking ice (3.7.4-6) ...
dpkg: error processing archive ....../ice/ice_3.7.4-6_amd64.deb (--install):
 unable to create '/proc/self/coredump_filter.dpkg-new' (while processing './proc/self/coredump_filter'): No such file or directory
Errors were encountered while processing:
 ....../ice/ice_3.7.4-6_amd64.deb
/var/tmp/tmp.KayXFggIpQ/dpkginstall.log (END)
```

Cheers

**Comment by pepone** [comment]
Hey,

How did you build this package? the latest version released for Ubuntu was 3.7.3-1, seems that some how your build include "/proc/self/coredump_filter.dpkg-new"

We are preparing 3.7.4 packages and they will be available soon

**Comment by jiapei100** [comment]
@pepone 

Hi, Thank you for replying promptly.

I just **make** directly, with the coming **Makefile** ... Would be better if a **CMake** or **configure** is provided????

**Comment by pepone** [comment]
Where did you get the sources for `ice_3.7.4-6`? We haven't release such version. 

If you want to build Ice packages from source just check https://github.com/zeroc-ice/ice-debian-packaging/blob/master/debian/BuildInstructions.md

If you just need the latest packages for Ubuntu 18.04 they are available from ZeroC repositories see
https://zeroc.com/downloads/ice/3.7/cpp#ubuntu
