### ISSUE TITLE
 what is the difference between using ice and using websocket only to receive server data

### ISSUE THREAD

**Issue by Tiramisupxl** [zeroc-ice/ice#857]
Hello，I'm new in Javascript.Because ice with javascript is using websocket to communicate width   browser and server,  what is the difference between using ice and using websocket only to receive server data.

**Comment by pepone** [comment]
You should take a look at the docs, I think you can start with the following:
- https://doc.zeroc.com/ice/3.7/ice-overview/ice-architecture
- https://doc.zeroc.com/ice/3.7/hello-world-application/writing-an-ice-application-with-javascript

**Comment by Tiramisupxl** [comment]
> You should take a look at the docs, I think you can start with the following:
> 
> * https://doc.zeroc.com/ice/3.7/ice-overview/ice-architecture
> * https://doc.zeroc.com/ice/3.7/hello-world-application/writing-an-ice-application-with-javascript

Thanks for you reply. I haved written a demo use javascript to link the websocket server form Ice official website.I am just confused, communicating with server in Ice is using websocket , and just communicating with server using websocket in javascript，what is the advantage to use ice rather than using javascript? Maybe I am ask a stupid question, please forgive me.

**Comment by pepone** [comment]
If you directly use JavaScript and WebSockets to communicate between server and client, is up to you how the data is encoded, how the messages are dispatched, and everything else.

With Ice you get an Object-Oriented RPC that is well proven, Ice will take care of all the networking details, retries, timeout , serialization and deserializing of the data and more.

**Comment by Tiramisupxl** [comment]
> If you directly use JavaScript and WebSockets to communicate between server and client, is up to you how the data is encoded, how the messages are dispatched, and everything else.
> 
> With Ice you get an Object-Oriented RPC that is well proven, Ice will take care of all the networking details, retries, timeout , serialization and deserializing of the data and more.

Is it faster use ice with javascript communicating between server and client  than to use JavaScript and WebSockets?

**Comment by pepone** [comment]
Ice for JavaScript use websockets, so what are you trying to compare it with. you must check the Ice for JavaScript [demos ](https://github.com/zeroc-ice/ice-demos/tree/3.7/js) there is throughput and latency demos those should give you and idea of Ice for JavaScript performance.

**Comment by Tiramisupxl** [comment]
> Ice for JavaScript use websockets, so what are you trying to compare it with, you must check the Ice for JavaScript [demos ](https://github.com/zeroc-ice/ice-demos/tree/3.7/js) there is throughput and latency demos those should give you and idea of Ice for JavaScript performance.

OK，Thank you very much for your reply.
