### ISSUE TITLE
TypeError: r.abort is not a function

### ISSUE THREAD

**Issue by zhengtulymGh** [zeroc-ice/ice#86]
version:  nodejs     ice3.6.4      ice3.7.0

```
const Ice = require("ice").Ice
const Demo = require("./FDFS").Demo
let ic
const env = require(__base + './config/env').env

const checkedCast = Ice.Promise.try(() => {
   try {
        ic = Ice.initialize()
        const base = ic.stringToProxy(`FDFS:default -h ${env.ip.ice_inner} -p 11000`)
        return Demo.FDFSPrx.checkedCast(base)
    } catch (e) {
        console.log(e.toString())
    }
})
```

FDFS.js
```
// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file \'FDFS.ice\'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Demo = _ModuleRegistry.module("Demo");

    Slice.defineSequence(Demo, "s1Helper", "Ice.ByteHelper", true);

    Demo.FDFSException = class extends Ice.UserException
    {
        constructor(reason = "", _cause = "")
        {
            super(_cause);
            this.reason = reason;
        }

        static get _parent()
        {
            return Ice.UserException;
        }

        static get _id()
        {
            return "::Demo::FDFSException";
        }

        _mostDerivedType()
        {
            return Demo.FDFSException;
        }

        _writeMemberImpl(ostr)
        {
            ostr.writeString(this.reason);
        }

        _readMemberImpl(istr)
        {
            this.reason = istr.readString();
        }
    };

    const iceC_Demo_FDFS_ids = [
        "::Demo::FDFS",
        "::Ice::Object"
    ];

    Demo.FDFS = class extends Ice.Object
    {
    };

    Demo.FDFSPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Demo.FDFS, Demo.FDFSPrx, iceC_Demo_FDFS_ids, 0,
    {
        "upload": [, , , , [7], [["Demo.s1Helper"], [3], [7]], ,
        [
            Demo.FDFSException
        ], , ],
        "append": [, , , , [4], [[7], ["Demo.s1Helper"], [3]], ,
        [
            Demo.FDFSException
        ], , ],
        "size": [, , , , [4], [[7]], ,
        [
            Demo.FDFSException
        ], , ],
        "delete": ["_delete", , , , , [[7]], ,
        [
            Demo.FDFSException
        ], , ],
        "download": [, , , , ["Demo.s1Helper"], [[7], [4], [4]], ,
        [
            Demo.FDFSException
        ], , ]
    });
    exports.Demo = Demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
```

I change both  the Slice-2-JavaScript compiler version and Ice version to 3.6.4 ，and  another  error  occurs
node: v8.4.0
operating system: win7 

`E:\project\paasCage\Amber\server\controllers\ice\FDFS.js:27
    var Demo = __M.module("Demo");
                  ^

TypeError: Cannot read property 'module' of undefined
    at E:\project\paasCage\Amber\server\controllers\ice\FDFS.js:27:19
    at Object.<anonymous> (E:\project\paasCage\Amber\server\controllers\ice\FDFS                                      .js:85:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\project\paasCage\Amber\server\controllers\ice\inde                                      x.js:9:14)
[nodemon] app crashed - waiting for file changes before starting...
`

`// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FDFS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var Demo = __M.module("Demo");
    Slice.defineSequence(Demo, "s1Helper", "Ice.ByteHelper", true);

    Demo.FDFSException = Slice.defineUserException(
        function(reason, _cause)
        {
            Ice.UserException.call(this, _cause);
            this.reason = reason !== undefined ? reason : "";
        },
        Ice.UserException,
        "Demo::FDFSException",
        function(__os)
        {
            __os.writeString(this.reason);
        },
        function(__is)
        {
            this.reason = __is.readString();
        },
        false,
        false);

    Demo.FDFS = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 0,
        [
            "::Demo::FDFS",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    Demo.FDFSPrx = Slice.defineProxy(Ice.ObjectPrx, Demo.FDFS.ice_staticId, undefined);

    Slice.defineOperations(Demo.FDFS, Demo.FDFSPrx,
    {
        "upload": [, , , , , [7], [["Demo.s1Helper"], [3], [7]], , 
        [
            Demo.FDFSException
        ], , ],
        "append": [, , , , , [4], [[7], ["Demo.s1Helper"], [3]], , 
        [
            Demo.FDFSException
        ], , ],
        "size": [, , , , , [4], [[7]], , 
        [
            Demo.FDFSException
        ], , ],
        "delete": ["_delete", , , , , , [[7]], , 
        [
            Demo.FDFSException
        ], , ],
        "download": [, , , , , ["Demo.s1Helper"], [[7], [4], [4]], , 
        [
            Demo.FDFSException
        ], , ]
    });
    exports.Demo = Demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
`

**Comment by pepone** [comment]
FDFS.js was generated with slice2js 3.7.1, you should use ice 3.7.1 not 3.7.0 not 3.6.4, the Slice-2-JavaScript compiler version and Ice version you use should be the same.

If thing still fail with 3.7.1 can you provide the stack trace for the failure use

```
console.log(e.stack)
```

Can you also clarify the NodeJS version and operating system that you are using?

**Comment by zhengtulymGh** [comment]
I have updated the issue according to your advice

**Comment by zhengtulymGh** [comment]
i'm sorry , is my npm install wrong lead to the problem.
