### ISSUE TITLE
Ice.ConnectionRefusedException when using an android emulator

### ISSUE THREAD

**Issue by NellyIS** [zeroc-ice/ice#863]
Setup: Mac OS 10.14.5, Appium version 1.16.0 , Testing on Android emulator (API 29), emulator IP address is 10.0.2.16.

Issue: I’m trying to run a test application from InteliJ using host 10.0.2.16 and port 8888 and it seems the emulator is unable to connect to ICE (Ice.ConnectionRefusedException). 
I tried changing the IP address to 127.0.0.1, 10.0.2.2 and my local network (192.168.1.x) but nothing seems to work.
When using a real device, the app is running fine, and ICE connection succeeds as expected.

**Comment by pepone** [comment]
Hi Nelly,

are you trying to connect from android emulator to an application in you development computer? We do that with our test suite

When working on the emulator to connect to a server in the development computer the server should be setup to listen on 127.0.0.1 and the client should use 10.0.2.2

**Comment by NellyIS** [comment]
Thanks @pepone for your reply!

Just to clarify, I’m running a java application on my computer, using ice for RPC between the computer and the android application that is running on the Android device (the 2 apps are connected to the same wifi network and listen to same port).
when I replace the real device with an emulator, and replace the ip address to the emulator ip address, I’m getting the Ice.ConnectionRefusedException.

Any advice?

**Comment by pepone** [comment]
If you want to open a connection from the emulator to your local computer you use the special address 10.0.2.2

If you want to open a connection from the development machine to the android emulator you have to setup a redirection see https://developer.android.com/studio/run/emulator-networking#redirection

**Comment by NellyIS** [comment]
Thanks @pepone 
So basically if I’m using the local computer wifi IP address (i.e 192.168.1.2) and a port (i.e 4000)
when using the emulator - I need to run the following command:
**redir add tcp:4000:4000**
What I don’t get is how I connect the hosts? (my local IP is 192.168.1.2 and my emulator local IP is 10.0.2.15)

**Comment by pepone** [comment]
From the emulator  192.168.1.2 should work, I just tested this with our hello demo, there is no special setup required to connect from the emulator to your local network.

**Comment by pepone** [comment]
You should keep in mind that a setup like this, where you need connect from your PC to a mobile device works well when both peers are in the same local network, but this can be problematic if your device is running on a 4G network,  in this case the device IP can be changing or worst your internet provider might block all incoming connections over 4G.

In such case is better to design you application to use [bidirectional connections](https://doc.zeroc.com/ice/3.7/client-server-features/connection-management/bidirectional-connections)

**Comment by NellyIS** [comment]
Hi @pepone , thank you for your answers!
I’ll try to explain again what configuration we actually need.
Today we use:
Machine network ip: 192.168.1.X
ICE port: 10000
With real device, it’s enough to connect the device proxy to machine ip.
With emulator, we’ve tried different combinations of configuration, but always get Ice.ConnectTimeoutException.
The questions is what configuration is actually needed for this setup:
- What emulator proxy should we use (via emulator settings)?
- Does special APN need to be configured?
- Do we need extra configurations or command-line executions for it to work?
- Do we need a specific Android version?
Thanks!

**Comment by pepone** [comment]
Hi @NellyIS 

You don't need any special configuration for this, the emulator should be able to connect to the server in your local network. You should try enabling network tracing to check the client is trying to connect to the expected address
