### ISSUE TITLE
C# send byte array from ArrayPool<byte>

### ISSUE THREAD

**Issue by thansen24** [zeroc-ice/ice#904]
I'm trying to send rather large byte arrays from a client to server and the current C# ice implementation doesn't really lend itself to avoid copying.  Here is a sample to show what I'm trying to do.  Ideally in my sample, I wouldn't need to use the trimmedBuffer, because there would be some way to send the sharedBuffer, but also include the offset and length for ice to copy into it's own internal buffer.

I think something like this could be done maybe by a slice2cs.exe switch that will allow when a byte[] is used as a method argument it'll be replaced with ReadOnlySpan\<byte> or alternatively a wrapper class that will know the Length and Offset.  Not sure what your thoughts are on the this, or if this is already on your roadmap.

```
module NoCopySample
{
  sequence<byte> HugeRequest;

  interface INoCopySample
  {
    void SendHugeRequest(HugeRequest request);
  };
};
```

```
private static void Main(string[] args)
{
    const int numByesToSendOver = 1000000;

    byte[] sharedBuffer = System.Buffers.ArrayPool<byte>.Shared.Rent(numByesToSendOver);

    // actually fill out sharedBuffer with data

    byte[] trimmedBuffer = new byte[numByesToSendOver];

    System.Buffer.BlockCopy(sharedBuffer, 0, trimmedBuffer, 0, numByesToSendOver);  // Need to trim the sharedBuffer since it's likely larger than numByesToSendOver

    INoCopySamplePrx prx = null;
    prx.SendHugeRequest(trimmedBuffer);

    System.Buffers.ArrayPool<byte>.Shared.Return(sharedBuffer);
}
```

**Comment by bernardnormier** [comment]
If you're adventurous, you could try to build master and see how it works there.

Your `SendHugeRequest` is mapped to the proxy method:
```
void SendHugeRequest(global::System.ReadOnlyMemory<byte> request, global::System.Collections.Generic.IReadOnlyDictionary<string, string>? context = null) 
```

That's the new default mapping. So can supply an `ArraySegment<byte>` that is implicitly converted into this `ReadOnlyMemory<byte>`.

Cheers,
Bernard

**Comment by thansen24** [comment]
Thanks!  I'll give that a try

**Comment by thansen24** [comment]
so I just tried, but it looks like in the ice.csproj there is only a target for netcoreapp3.1, is support for .Net Standard 2.0 being dropped?  I ran `msbuild msbuild\ice.proj` per the readme, but only see a netcoreapp3.1 folder in the csharp/lib folder.  Maybe I'm building it wrong?

**Comment by thansen24** [comment]
@bernardnormier, I'm running from .net framework 4.7.  Is the intention that master will work only with .net core?

**Comment by bernardnormier** [comment]
Yes, master currently requires .NET core 3.1. We won't support .NET 4.7 with Ice 4.0.

**Comment by pepone** [comment]
@thansen24 master only works with .NET Core, eventually with .NET 5 when it is released, but we want to start using some APIs that were not available with netstandard2.0

**Comment by thansen24** [comment]
Ohhh wow, ok.  We are quite a ways off from having the ability to upgrade everything to net core.  Are you guys open to a pull request to try and solve this on the 3.7.X branch?  After reading through the code, it seems to me that just some specializations would be needed in the OutputStream.cs and InputStream.cs

**Comment by thansen24** [comment]
@pepone @bernardnormier I added a pull request to show you what this would look like.  It's not fully fleshed out because I wanted to make sure you guys would accept it before I fully incorporated it.  But it does compile with the new code gen and .ice file.

https://github.com/zeroc-ice/ice/pull/912
