### ISSUE TITLE
Better handle shutdown of IceGrid registry from the GUI

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#91]
If you shutdown the IceGrid registry the GUI is connected to, a connection lost dialog shows up. If not too complicated,  we should consider handling the shutdown more gracefully and instead just disconnect the GUI from the registry.

**Comment by pepone** [comment]
This will require to check that the registry/node being shutdown is the one hosting the current session and ignore the session lost error in this case.

When the registry runs collocated with the node there isn't a way to figure the registry name. I just updated the session lost message to be more informative.
