### ISSUE TITLE
AMI callback in a wrong thread

### ISSUE THREAD

**Issue by bruce1125** [zeroc-ice/ice#94]
I use ice-box in my app,that can start some different services at one process.
Sometimes,for example,I accept client request in serviceA first.Then the request handle logic may invoke a AMI api to serviceB.Once the AMI callback is running ,I find a problem:
**the running thread is I created for the serviceB in the app initializing.**

I try to remove serviceB to another process,but the thread above change to which belong to serviceC.Only if the serviceA is in a seperate process alone,the callback is running in my expect thread.
It looks like different communicator which has different dispatch thread,will share for each other in a same process?

My envirment is jdk 1.7 and ice 3.6.3.The code i use to dispatch to my thread is:
initData.dispatcher = new Dispatcher() {
			@Override
			public void dispatch(Runnable runnable, Connection con) {
				execute(runnable);
			}
		};
		this.customCommunicator = Util.initialize(initData);

**Comment by bruce1125** [comment]
sorry every one,the problem discusses in the forums maybe more suitable but I cannot register account by the note:The captcha was not completed correctly. Please try again.
But I have never see any captcha on the page.

**Comment by bentoi** [comment]
Hi,

I'm not sure I understand your issue. If you create 3 communicators with each communicator having their own dispatcher and execution thread, each communicator should use its dedicated dispatcher and not use a dispatcher from another communicator.

AMI callbacks should be executed through the dispatcher associated with the communicator that created the proxy used to make the AMI invocation.

Could you perhaps provide us a sample test case showing the problem? This would help us to better understand what you are trying to do.

Cheers,
Benoit.

**Comment by bruce1125** [comment]
Hi Bentoi,thanks for the feedback.I have found the reason,which is generated by my logic code.
When I preparing the test case,I review some logic code.Because I use a masterService that has some same functions like a locator,and when some different services are running,they share one proxy for the masterService,which is created with the first communicator in the service initializing.Then while using the proxy later,the logic always uses the shared proxy.That is all.Thank you very much.
