### ISSUE TITLE
build failure on macOS

### ISSUE THREAD

**Issue by AndreasFMueller** [zeroc-ice/ice#96]
3.7.1 seems not be able to build on macOS, the generated slice2cpp finds a syntax error in Election.ice:

```
make prefix=/usr/local/Ice-3.7.1 V=1 					\
	CONFIGS="shared cpp11-shared" 					\
	PLATFORMS=all 							\
	SKIP="slice2confluence slice2py slice2rb slice2js" 		\
	LANGUAGES=cpp
...
making all in cpp
rm -f src/IceStorm/generated/IceStorm/Election.h src/IceStorm/generated/Election.cpp
bin/slice2cpp -Isrc --include-dir IceStorm -I../slice --depend ../cpp/src/IceStorm/Election.ice | sed 's|\(.*:\)|src/IceStorm/generated/IceStorm/Election.h src/IceStorm/generated/Election.cpp:|' > src/IceStorm/generated/Election.ice.d
bin/slice2cpp -Isrc --include-dir IceStorm -I../slice --output-dir src/IceStorm/generated ../cpp/src/IceStorm/Election.ice
/usr/local/src/ice-3.7.1/cpp/src/IceStorm/Election.ice:308: syntax error
make[1]: *** [src/IceStorm/generated/Election.cpp] Error 1
make: *** [all] Error 1
```

**Comment by pepone** [comment]
Hi,

Sounds like your system mcpp library is missing some of the required patches, on macOS we are using the homebrew `mcpp` package.

The required patch is available here https://raw.githubusercontent.com/Homebrew/formula-patches/3fd7fba/mcpp/2.7.2.patch

see also https://forums.zeroc.com/discussion/5445/mishap-in-slice-compilers

**Comment by AndreasFMueller** [comment]
Ok, it does compile and work with the patched mcpp. However, it is impossible to compile it with the -std=c++11 flag, which some applications require. I experience subtle crashes on an application that uses auto pointers, which are not supported without the -std=c++11 flag on macos, and I suspect I should compile Ice-3.7.1 with that flag also. The reason for the compile failure is that throw() should be replaced by noexcept, but the combination of compiler flags -Wdeprecated -Werror terminates the build:

```
c++ -std=c++11 -MT src/Ice/build/macosx/shared/pic/Communicator.o -MMD -MP -MF  src/Ice/build/macosx/shared/pic/Communicator.Td -Wall -Wdeprecated -Wstrict-prototypes -Werror -pthread -O2 -DNDEBUG -Isrc -Isrc/Ice/generated -Iinclude -Iinclude/generated -DICE_BUILDING_SRC -DICE_API_EXPORTS -mmacosx-version-min=10.9 -arch x86_64 -fPIC -fvisibility=hidden  -c src/Ice/generated/Communicator.cpp -o src/Ice/build/macosx/shared/pic/Communicator.o
In file included from src/Ice/generated/Communicator.cpp:24:
In file included from include/generated/Ice/Communicator.h:32:
In file included from include/Ice/Proxy.h:30:
In file included from include/Ice/OutgoingAsync.h:24:
include/generated/Ice/LocalException.h:3924:40: error: dynamic exception specifications are deprecated [-Werror,-Wdeprecated-dynamic-exception-spec]
    virtual ~InitializationException() throw();
                                       ^~~~~~~
include/generated/Ice/LocalException.h:3924:40: note: use 'noexcept' instead
    virtual ~InitializationException() throw();
                                       ^~~~~~~
...
```

**Comment by bentoi** [comment]
Did you run into any issues when using the Ice library built with the C++98 mode with a binary built with the C++11 mode? I looked closer into this and I don't think you need to rebuild Ice with `-std=c++11` on macOS or Linux x86/x64 platforms. I was able to run our test suite built with `-std=c++11` against the Ice libraries built with the default `-std=c++98`. 

I think this is only needed for platforms where GCC atomic builtins aren't available which is the case of ARM/Linux platforms. See also https://github.com/zeroc-ice/ice/blob/3.7/cpp/include/IceUtil/Atomic.h#L28

**Comment by bentoi** [comment]
@AndreasFMueller, can we close this issue? On macOS, you shouldn't need to rebuild Ice with `-std=c++11`.

**Comment by AndreasFMueller** [comment]
yes, I have recompiled everything (to make sure there are no old objects lying around) and it now works.
