### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by nanodesu88** [zeroc-ice/ice#99]
What about typescript slice compiler? Typescript is much better than basic js. Where can i read about?

**Comment by pepone** [comment]
there is not Slice to typescript compiler, but you can use Ice for JavaScript with typescript.

**Comment by nanodesu88** [comment]
It is, but typescript entices more and more javascript developers, typescript have a good typesystem, better declarations and better ide support. Not all typescript projects can use pure generated js right, because you need write declarations manually any time you change a ice declarations.

**Comment by aikoven** [comment]
@nanodesu88 Check out https://github.com/aikoven/slice2ts

Also here are the typings for Ice runtime: https://github.com/aikoven/typed-ice

**Comment by externl** [comment]
@aikoven @nanodesu88 would either of you be interested creating a new PR for this feature?

**Comment by externl** [comment]
I think that best approach would be to add a new flag to `slice2js` to generate the TS declarations.

**Comment by aikoven** [comment]
I tried to add this functionality directly to `slice2js`, but I'm not experienced enough with C++ and yacc.

**Comment by pepone** [comment]
Hi @aikoven @nanodesu88,

We have added support for slice2js to generate `TypeScript` declarations using --typescript command line option. We have also include `TypeScript` declaration files for the non-generated code.

This will be included in the upcoming 3.7.2 release, let us know how this work for you.

Cheers,
José
